; Acquistion installer script

;-----------------------------------------------------------------------------------------
; Check command-line arguments.

#ifndef BUILD_DIR
#error "BUILD_DIR must be defined using the /D command-line parameter to run this script."
#endif

#ifndef DEPLOY_DIR
#error "DEPLOY_DIR must be defined using the /D command-line parameter to run this script."
#endif

;-----------------------------------------------------------------------------------------
; Load and check the version defines.

#define VERSION_H BUILD_DIR + "\version_defines.h"
#include VERSION_H

#ifndef APP_NAME
#error "APP_NAME not defined in " + VERSION_H
#endif

#ifndef APP_VERSION_STRING
#error "APP_VERSION_STRING not defined in " + VERSION_H
#endif

#ifndef APP_PUBLISHER
#error "APP_PUBLISHER not defined in " + VERSION_H
#endif

#ifndef APP_URL
#error "APP_URL not defined in " + VERSION_H
#endif

;-----------------------------------------------------------------------------------------

#pragma message "BUILD_DIR = " + BUILD_DIR
#pragma message "DEPLY_DIR = " + DEPLOY_DIR
#pragma message "VERSION_H = " + VERSION_H

#pragma message "APP_NAME           = " + APP_NAME
#pragma message "APP_VERSION_STRING = " + APP_VERSION_STRING
#pragma message "APP_PUBLISHER      = " + APP_PUBLISHER
#pragma message "APP_URL            = " + APP_URL

;-----------------------------------------------------------------------------------------
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
;
; This is the same GUID as the testpushpleaseignore fork of Acquisition:
AppId={{53E25C0C-0305-47BB-9884-F0F202297AF4}
AppName={#APP_NAME}
AppVersion={#APP_VERSION_STRING}
AppPublisher={#APP_PUBLISHER}
AppPublisherURL={#APP_URL}
;AppSupportURL={#AppURL}
AppUpdatesURL={#APP_URL}
DefaultDirName={autopf}\{#APP_NAME}
DisableProgramGroupPage=yes
LicenseFile=LICENSE
OutputBaseFilename={#APP_NAME}_setup_{#APP_VERSION_STRING}
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
RestartIfNeededByRun=yes
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
MinVersion=10.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; Flags: unchecked

[InstallDelete]
; Remove unsupported app-local MSVC runtime files left by older or manual installs.
Type: files; Name: "{app}\msvcp140*.dll"
Type: files; Name: "{app}\vcruntime140*.dll"
Type: files; Name: "{app}\concrt140.dll"

[Files]
Source: "{#DEPLOY_DIR}\*"; DestDir: "{app}"; Excludes: "vc_redist.x64.exe"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#DEPLOY_DIR}\vc_redist.x64.exe"; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#APP_NAME}"; Filename: "{app}\{#APP_NAME}.exe"
Name: "{autodesktop}\{#APP_NAME}"; Filename: "{app}\{#APP_NAME}.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\{#APP_NAME}.exe"; Description: "{cm:LaunchProgram,{#StringChange(APP_NAME, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  VCRedistSuccess = 0;
  VCRedistAnotherVersionInstalled = 1638;
  VCRedistRebootInitiated = 1641;
  VCRedistRebootRequired = 3010;

var
  VCRedistNeedsRestart: Boolean;

function InstallVCRedist: String;
var
  RedistPath: String;
  LogDirectory: String;
  LogPath: String;
  Parameters: String;
  ResultCode: Integer;
begin
  Result := '';
  LogDirectory := ExpandConstant('{localappdata}\{#APP_NAME}\installer-logs');
  LogPath := LogDirectory + '\vc_redist-{#APP_VERSION_STRING}.log';

  if not ForceDirectories(LogDirectory) then
  begin
    Result :=
      'Setup could not create the Visual C++ Runtime log directory:' + #13#10 +
      LogDirectory;
    Exit;
  end;

  WizardForm.StatusLabel.Caption :=
    'Installing Microsoft Visual C++ Runtime...';

#ifdef VC_REDIST_TEST_EXIT_CODE
  ResultCode := {#VC_REDIST_TEST_EXIT_CODE};
  Log('Using synthetic Microsoft Visual C++ Runtime exit code ' +
    IntToStr(ResultCode) + '.');
#else
  try
    ExtractTemporaryFile('vc_redist.x64.exe');
  except
    Result :=
      'Setup could not extract the Microsoft Visual C++ Runtime installer.';
    Exit;
  end;

  RedistPath := ExpandConstant('{tmp}\vc_redist.x64.exe');
  Parameters := '/install /quiet /norestart /log "' + LogPath + '"';

  if not Exec(RedistPath, Parameters, '', SW_SHOWNORMAL,
    ewWaitUntilTerminated, ResultCode) then
  begin
    Result :=
      'Setup could not start the Microsoft Visual C++ Runtime installer.' + #13#10 +
      'Windows error: ' + IntToStr(ResultCode) + #13#10 +
      'Log: ' + LogPath;
    Exit;
  end;
#endif

  case ResultCode of
    VCRedistSuccess:
      Log('Microsoft Visual C++ Runtime installation succeeded.');
    VCRedistAnotherVersionInstalled:
      Log('A newer Microsoft Visual C++ Runtime is already installed.');
    VCRedistRebootInitiated, VCRedistRebootRequired:
      begin
        Log('Microsoft Visual C++ Runtime installation requires a restart.');
        VCRedistNeedsRestart := True;
      end;
  else
    Result :=
      'Microsoft Visual C++ Runtime installation failed with exit code ' +
      IntToStr(ResultCode) + '.' + #13#10 +
      'See the installation log for details:' + #13#10 + LogPath;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := InstallVCRedist;
end;

function NeedRestart: Boolean;
begin
  Result := VCRedistNeedsRestart;
end;
