//! `MCP-REFERENCE.md` is generated from the server's own `initialize`
//! instructions and `tools/list` — every tool, its description and its
//! arguments as the schema declares them — and this test keeps the
//! committed copy equal to it. A golden file, not a frozen one (P5):
//! drift fails here, and
//! `ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-mcp --test mcp_reference`
//! rewrites it. An agent reads the file without building; the writer
//! builds anyway. The CLI's counterpart is `CLI-REFERENCE.md`.

mod harness;

use harness::Mcp;
use serde_json::Value;

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../MCP-REFERENCE.md");

/// Doc comments arrive with their source line breaks; one line per field.
fn flat(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn render(instructions: &str, tools: &[Value]) -> String {
    let mut out = String::from(
        "# `acq-mcp` — tool reference\n\n\
         Generated by `crates/acquisition-mcp/tests/mcp_reference.rs` from the \
         server's own `initialize` instructions and `tools/list`; a golden file \
         the test keeps equal to the binary. Do not edit: change the tool's \
         attributes in `crates/acquisition-mcp/src/main.rs` and regenerate with \
         `ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-mcp --test mcp_reference`. \
         The CLI's verbs are `CLI-REFERENCE.md`.\n\n\
         ## Instructions (sent at `initialize`)\n\n",
    );
    out.push_str(&flat(instructions));
    out.push_str("\n\n## Tools\n\n");
    for tool in tools {
        let name = tool["name"].as_str().unwrap_or("?");
        let desc = flat(tool["description"].as_str().unwrap_or(""));
        out.push_str(&format!("### `{name}`\n\n{desc}\n\n"));
        let schema = &tool["inputSchema"];
        let required: Vec<&str> = schema["required"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        match schema["properties"].as_object() {
            Some(props) if !props.is_empty() => {
                let mut names: Vec<&String> = props.keys().collect();
                names.sort();
                for arg in names {
                    let p = &props[arg];
                    let ty = match &p["type"] {
                        Value::String(t) => t.clone(),
                        Value::Array(ts) => ts
                            .iter()
                            .filter_map(Value::as_str)
                            .collect::<Vec<_>>()
                            .join(" | "),
                        _ => "object".to_string(),
                    };
                    let req = if required.contains(&arg.as_str()) {
                        ", required"
                    } else {
                        ""
                    };
                    let d = flat(p["description"].as_str().unwrap_or(""));
                    let sep = if d.is_empty() { "" } else { " — " };
                    out.push_str(&format!("- `{arg}` ({ty}{req}){sep}{d}\n"));
                }
                out.push('\n');
            }
            _ => out.push_str("No arguments.\n\n"),
        }
    }
    out
}

#[test]
fn the_reference_matches_the_server() {
    let base = std::env::temp_dir().join(format!("acq-mref-{}", std::process::id()));
    std::fs::create_dir_all(&base).unwrap();
    let mut mcp = Mcp::start(&base, &[]);
    let tools = mcp.list_tools();
    let actual = render(&mcp.instructions, &tools);
    let _ = mcp.child.kill();
    let _ = std::fs::remove_dir_all(&base);
    assert!(tools.len() >= 10, "tools/list returned {}", tools.len());
    if std::env::var_os("ACQ_UPDATE_FIXTURES").is_some() {
        std::fs::write(PATH, &actual).unwrap();
    }
    let expected = std::fs::read_to_string(PATH).unwrap_or_else(|e| panic!("{PATH}: {e}"));
    assert!(
        expected == actual,
        "MCP-REFERENCE.md no longer matches the server; regenerate with \
         ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-mcp --test mcp_reference"
    );
}
