#!/usr/bin/env python3
"""cpp-search F2: the catalogue's min/max accessors run over a real corpus, and the fetch's computed defences checked.

Inputs: the two stores `../item-facts/scripts/census.py` reads (its loaders, its dedupe: newest fetch wins), and
the owner's trade `fetch` captures under `../trade-query/raw/searches/` (local only).

Part 1 — data/accessor-census.csv: one row per min/max filter (data/filters.toml): items where the accessor's
property or field is present, items where the C++ parse (QString::toDouble / toInt: the whole string, else 0)
yields a number, items present but parsed as 0, and an example of each string shape. The DPS family reports
the presence of its inputs; sockets and links the derived count.

Part 2 — stdout: for every fetched item carrying `extended.ar`/`ev`/`es`, the property value with the item's own
quality taken out and 20 % put in (the filter tips' quality), against the value the site computed, within one.
"""

import collections
import csv
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(TRACK, "..", "item-facts", "scripts"))
import census  # noqa: E402

HEADER = "# generated by scripts/accessor-census.py from " + census.HEADER[len("# generated by scripts/census.py from "):]
DOUBLE = re.compile(r"^\s*[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*$")
INT = re.compile(r"^\s*[+-]?\d+")  # QString::toInt: the whole string; a trailing non-digit fails it
INT_FULL = re.compile(r"^\s*[+-]?\d+\s*$")

PROPERTY_FILTERS = [  # caption, property name, absent-rule (skip = present() false, zero = default 0)
    ("Crit.", "Critical Strike Chance", "skip"), ("APS", "Attacks per Second", "skip"),
    ("Armour", "Armour", "skip"), ("Evasion", "Evasion Rating", "skip"), ("Shield", "Energy Shield", "skip"),
    ("Block", "Chance to Block", "skip"), ("Quality", "Quality", "zero"), ("Level", "Level", "skip"),
    ("Map Tier", "Map Tier", "skip"),
]


def cpp_properties(item):
    """The C++ `m_properties` map: name -> values[0][0], last wins, Elemental Damage excluded, three cleanups."""
    out = {}
    for p in item.get("properties") or []:
        vals = p.get("values") or []
        if not vals or p.get("name") == "Elemental Damage":
            continue
        s = str(vals[0][0])
        name = p.get("name", "")
        if name == "Quality":
            s = s.removeprefix("+").removesuffix("%")
        elif name == "Level" and s.endswith("(Max)"):
            s = s[:-6]
        out[name] = s
    return out


def to_double(s):
    return float(s) if DOUBLE.match(s) else 0.0


def avg(s):
    parts = s.split("-")
    return to_double(s) if len(parts) < 2 else (to_double(parts[0]) + to_double(parts[1])) / 2


def main():
    by_id = {}
    for rec in list(census.spike_records()) + list(census.cpp_records()):
        old = by_id.get(rec.id)
        if old is None or rec.fetched > old.fetched:
            by_id[rec.id] = rec
    items = [r.json for r in by_id.values()]
    n = len(items)
    rows = []
    for caption, prop, rule in PROPERTY_FILTERS:
        present = parsed = zeroed = 0
        ex_ok = ex_zero = None
        for it in items:
            props = cpp_properties(it)
            if prop not in props:
                continue
            present += 1
            s = props[prop]
            if DOUBLE.match(s) and to_double(s) != 0:
                parsed += 1
                ex_ok = ex_ok or s
            else:
                zeroed += 1
                ex_zero = ex_zero or s
        rows.append([caption, prop, rule, present, parsed, zeroed, ex_ok or "", ex_zero or ""])
    # requirements: values[0][0].toInt(), last wins, 0 when absent
    for caption, name in (("R. Level", "Level"), ("R. Str", "Str"), ("R. Dex", "Dex"), ("R. Int", "Int")):
        present = parsed = zeroed = 0
        ex_ok = ex_zero = None
        for it in items:
            reqs = {}
            for r in it.get("requirements") or []:
                if r.get("values"):
                    reqs[r.get("name")] = str(r["values"][0][0])
            if name not in reqs:
                continue
            present += 1
            s = reqs[name]
            if INT_FULL.match(s) and int(s) != 0:
                parsed += 1
                ex_ok = ex_ok or s
            else:
                zeroed += 1
                ex_zero = ex_zero or s
        rows.append([caption, f"requirements[{name}]", "zero", present, parsed, zeroed, ex_ok or "", ex_zero or ""])
    # the DPS family: both inputs present and non-zero
    for caption, dmg in (("pDPS", "Physical Damage"), ("cDPS", "Chaos Damage")):
        present = parsed = 0
        ex_ok = None
        for it in items:
            props = cpp_properties(it)
            if dmg in props and "Attacks per Second" in props:
                present += 1
                v = to_double(props["Attacks per Second"]) * avg(props[dmg])
                if v:
                    parsed += 1
                    ex_ok = ex_ok or f'{props[dmg]} x {props["Attacks per Second"]}'
        rows.append([caption, f"{dmg} x APS", "zero", present, parsed, present - parsed, ex_ok or "", ""])
    present = parsed = 0
    ex_ok = None
    for it in items:
        props = cpp_properties(it)
        ele = [p for p in it.get("properties") or [] if p.get("name") == "Elemental Damage"]
        if ele and "Attacks per Second" in props:
            present += 1
            v = to_double(props["Attacks per Second"]) * sum(avg(str(x[0])) for x in ele[0].get("values") or [])
            if v:
                parsed += 1
                ex_ok = ex_ok or ";".join(str(x[0]) for x in ele[0]["values"])
    rows.append(["eDPS", "Elemental Damage x APS", "zero", present, parsed, present - parsed, ex_ok or "", ""])
    # sockets and links
    present = parsed = 0
    links_hist = collections.Counter()
    for it in items:
        sockets = it.get("sockets") or []
        if not sockets:
            continue
        present += 1
        run = best = 0
        prev = None
        for s in sockets:
            g = s.get("group")
            run = run + 1 if g == prev else 1
            prev = g
            best = max(best, run)
        links_hist[best] += 1
        if any("attr" in s or "sColour" in s for s in sockets):
            parsed += 1
    rows.append(["Sockets", "sockets.length", "zero", present, present, 0, "", ""])
    rows.append(["Links", "longest consecutive group run", "zero", present, parsed, present - parsed,
                 ";".join(f"{k}:{v}" for k, v in sorted(links_hist.items())), "sockets without attr/sColour (PoE2)"])
    rows.append(["ilvl", "ilvl", "field", sum(1 for it in items if "ilvl" in it), sum(1 for it in items if it.get("ilvl")), sum(1 for it in items if "ilvl" in it and not it.get("ilvl")), "", ""])
    with open(os.path.join(TRACK, "data", "accessor-census.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["filter", "reads", "absent_rule", "items_present", "items_parsed_nonzero", "items_present_but_zero", "example_parsed", "example_zeroed"])
        w.writerows(rows)
    print(f"items {n:,}")
    for r in rows:
        print("  " + " | ".join(str(x) for x in r))

    # Part 2: the fetch's computed defences against the property x 1.2
    print("\nfetch extended.ar/ev/es against property / (1 + q) x 1.2, within one:")
    ok = bad = 0
    for path in sorted(glob.glob(os.path.join(TRACK, "..", "trade-query", "raw", "searches", "q*-fetch.json"))):
        if os.path.getsize(path) == 0:
            continue
        for r in json.load(open(path))["result"]:
            it = r["item"]
            ext = it.get("extended") or {}
            props = cpp_properties(it)
            for key, prop in (("ar", "Armour"), ("ev", "Evasion Rating"), ("es", "Energy Shield")):
                if key not in ext:
                    continue
                base = to_double(props.get(prop, "0"))
                q = to_double(props.get("Quality", "0"))
                pred = base / (1 + q / 100) * 1.2  # the item's own quality taken out, 20 % put in
                hit = abs(ext[key] - pred) <= 1  # the property is itself rounded, so the site's number can differ by one
                ok += hit
                bad += not hit
                print(f"  {os.path.basename(path)} {it.get('name')} {it.get('typeLine')}: {prop}={props.get(prop)} q={q:g} aug={ext.get(key + '_aug')} site={ext[key]} pred={pred:.1f} {'ok' if hit else 'MISS'}")
    print(f"  agree {ok}, disagree {bad}")


if __name__ == "__main__":
    sys.exit(main())
