#!/usr/bin/env python3
"""Extract the C++ app's pseudomod summing table as TOML.

Input: `git show <commit>:src/pseudomods.cpp` (default commit: master).
Output: data/pseudomods.toml on stdout — one [[pseudomod]] per entry of
PseudoModManager::SUMMING_MODS, in source order, with the templates it
sums (duplicates kept, as the source lists them: the summed value counts
a contributing line once per listing).

    scripts/extract-pseudomods.py [commit] > data/pseudomods.toml
"""
import re
import subprocess
import sys

commit = sys.argv[1] if len(sys.argv) > 1 else "master"
src = subprocess.run(
    ["git", "show", f"{commit}:src/pseudomods.cpp"], check=True, capture_output=True, text=True
).stdout
short = subprocess.run(
    ["git", "rev-parse", "--short=8", commit], check=True, capture_output=True, text=True
).stdout.strip()

body = src.split("SUMMING_MODS = {", 1)[1].split("};", 1)[0]
# Strip comments, then read every string literal in order; an entry is a
# `{ "<name>", { "<template>", ... } }` block.
body = re.sub(r"//[^\n]*", "", body)
entries = []
for block in re.finditer(r"\{\s*\"([^\"]+)\"\s*,\s*\{([^}]*)\}\s*\}", body):
    name = block.group(1)
    sums = re.findall(r"\"([^\"]+)\"", block.group(2))
    entries.append((name, sums))

print(f"# generated by scripts/extract-pseudomods.py from master@{short} src/pseudomods.cpp")
print(f"# {len(entries)} pseudomods. Rule (modlist.cpp:374-392 at the commit): present on an item exactly when at least")
print("# one of its lines (any bucket: implicit, explicit, crafted, fractured, mutated, enchant) normalises to a listed template;")
print("# value = the sum over those lines of each line's value (the mean of the line's numbers), a template listed N times")
print("# contributing N times (the all-Elemental line counts 3x into '+#% total Elemental Resistance').")
for name, sums in entries:
    print()
    print("[[pseudomod]]")
    print(f'name = "{name}"')
    print("sums = [")
    for s in sums:
        print(f'  "{s}",')
    print("]")
