#!/usr/bin/env python3
"""Invert data/conditions.csv: for every C++ filter and every trade filter that
reads an item, does GGG's filter language name the same thing, and under what
name?  (BRIEF's acceptance test.)

Inputs: data/conditions.csv (this track), ../cpp-search/data/filters.toml,
        ../trade-query/data/grammar.json.
Output: data/coverage.csv.

`condition` is inverted from conditions.csv; `kind` is hand-kept here (exact =
the same quantity under a different spelling at most; divergent = a related but
different quantity, see the note; none = the filter language has no condition
for it) and must be present for exactly the keys the inversion names.
"""

import csv
import json
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CONDS = os.path.join(TRACK, "data", "conditions.csv")
CPP = os.path.join(SEARCH, "cpp-search", "data", "filters.toml")
GRAMMAR = os.path.join(SEARCH, "trade-query", "data", "grammar.json")
OUT = os.path.join(TRACK, "data", "coverage.csv")

HEADER = (
    "# generated by scripts/coverage.py from data/conditions.csv, "
    "../cpp-search/data/filters.toml, ../trade-query/data/grammar.json. "
    "One row per C++ filter and per trade filter that reads an item; trade's status_filters "
    "and trade_filters groups are excluded (they read a listing, not an item). "
    "`condition` is the inversion of conditions.csv; `kind` is hand-kept."
)

# trade groups whose filters read a listing, not an item
NOT_ITEM_GROUPS = {"status_filters", "trade_filters"}

KIND = {
    # --- C++ captions the filter language also names
    ("cpp", "Name"): ("divergent", "BaseType matches a base-type name; the C++ Name filter is a case-insensitive substring over name+typeLine together, so it also matches unique names, which no condition does."),
    ("cpp", "Category"): ("divergent", "Class names an item class; the C++ Category substring-matches RePoE class display names. Different vocabularies for the same axis."),
    ("cpp", "Rarity"): ("divergent", "Rarity is ORDERED in the filter language (Rarity > Magic); the C++ combo is an unordered choice."),
    ("cpp", "Sockets"): ("exact", "Sockets; the C++ Colors filter is the same condition's colour letters."),
    ("cpp", "Colors"): ("exact", "The colour half of the Sockets condition (R/G/B/A/D/W)."),
    ("cpp", "Links"): ("exact", "LinkedSockets."),
    ("cpp", "Linked"): ("exact", "The colour half of SocketGroup."),
    ("cpp", "Quality"): ("exact", ""),
    ("cpp", "Level"): ("exact", "GemLevel."),
    ("cpp", "Map Tier"): ("exact", ""),
    ("cpp", "ilvl"): ("exact", "ItemLevel."),
    ("cpp", "Unidentified"): ("exact", "Identified, negated."),
    ("cpp", "Influenced"): ("divergent", "One boolean over six influences; the filter language names each influence separately (HasInfluence, ShaperItem, ElderItem)."),
    ("cpp", "Enchanted"): ("exact", "AnyEnchantment."),
    ("cpp", "Corrupted"): ("exact", ""),
    ("cpp", "Fractured"): ("exact", "FracturedItem."),
    ("cpp", "Synthesized"): ("exact", "SynthesisedItem — GGG spells it with an s."),
    ("cpp", "Mutated"): ("exact", "Foulborn is GGG's word for the same flag."),
    ("cpp", "Mods"): ("divergent", "HasExplicitMod takes a count over a set of named mods and no numeric range on the mod's own value; the C++ mod filter ranges a mod's value."),
    # --- C++ captions with no condition
    ("cpp", "Tab"): ("none", "Location is not an item property; the filter language runs at drop time."),
    ("cpp", "Crit."): ("none", "No condition for a weapon's critical strike chance."),
    ("cpp", "DPS"): ("none", "No derived-DPS condition of any kind."),
    ("cpp", "pDPS"): ("none", ""),
    ("cpp", "eDPS"): ("none", ""),
    ("cpp", "cDPS"): ("none", ""),
    ("cpp", "APS"): ("none", ""),
    ("cpp", "Armour"): ("none", "BaseArmour is the BASE value; there is no condition for the total after mods."),
    ("cpp", "Evasion"): ("none", "As Armour: only BaseEvasion."),
    ("cpp", "Shield"): ("none", "As Armour: only BaseEnergyShield."),
    ("cpp", "Block"): ("none", ""),
    ("cpp", "R. Level"): ("none", "No condition for any requirement."),
    ("cpp", "R. Str"): ("none", ""),
    ("cpp", "R. Dex"): ("none", ""),
    ("cpp", "R. Int"): ("none", ""),
    ("cpp", "Alt. art"): ("none", ""),
    ("cpp", "Priced"): ("none", "A buyout is Acquisition's own state, not GGG's."),
    ("cpp", "Crafted"): ("none", "No condition for a crafted mod, though trade has one."),
    ("cpp", "Split"): ("none", ""),
}

TRADE_KIND = {
    "category": ("divergent", "Class; trade's categories are coarser than the class names (repoe class-to-trade-category.csv)."),
    "rarity": ("divergent", "Rarity; the filter's four values are ordered, trade adds uniquefoil and nonunique."),
    "sockets": ("exact", "Sockets."),
    "links": ("exact", "LinkedSockets and SocketGroup."),
    "base_defence_percentile": ("exact", "BaseDefencePercentile — the same name and the same definition."),
    "map_tier": ("exact", "MapTier."),
    "area_level": ("divergent", "AreaLevel names the level of the area the item DROPPED in, not a map's own area level."),
    "map_blighted": ("exact", "BlightedMap."),
    "map_uberblighted": ("exact", "UberBlightedMap."),
    "quality": ("exact", ""),
    "ilvl": ("exact", "ItemLevel."),
    "gem_level": ("exact", "GemLevel."),
    "gem_transfigured": ("exact", "TransfiguredGem, which can also name the gem."),
    "fractured_item": ("exact", "FracturedItem."),
    "gem_imbued": ("exact", "Imbued."),
    "synthesised_item": ("exact", "SynthesisedItem."),
    "searing_item": ("divergent", "HasSearingExarchImplicit compares an implicit TIER 1-6; the trade filter is yes/no."),
    "tangled_item": ("divergent", "HasEaterOfWorldsImplicit compares an implicit TIER 1-6; the trade filter is yes/no."),
    "identified": ("exact", ""),
    "corrupted": ("exact", ""),
    "mirrored": ("exact", ""),
    "vestigial": ("exact", ""),
    "memory_level": ("exact", "MemoryStrands."),
    "stack_size": ("exact", "StackSize."),
    "scourge_tier": ("divergent", "Scourged is yes/no; the trade filter compares a tier."),
    "crucible_item": ("exact", "HasCruciblePassiveTree."),
    "mutated": ("exact", "Foulborn."),
}

TRADE_NONE = {
    "damage": "No condition for any computed weapon number.",
    "aps": "",
    "crit": "",
    "dps": "",
    "pdps": "",
    "edps": "",
    "ar": "Only BaseArmour, the base value before mods.",
    "ev": "Only BaseEvasion.",
    "es": "Only BaseEnergyShield.",
    "ward": "Only BaseWard.",
    "block": "",
    "lvl": "No condition for any requirement.",
    "str": "",
    "dex": "",
    "int": "",
    "class": "Character class requirement; the filter language's Class is the ITEM class, a different axis.",
    "gem_level_progress": "",
    "gem_vaal": "IsVaalUnique is a PoE2 unique flag, not a Vaal gem.",
    "veiled": "",
    "foreseeing": "",
    "intangibility": "",
    "stored_experience": "",
    "alternate_art": "AlternateQuality is gem quality, not alternate art.",
    "foil_variation": "",
    "corpse_type": "",
    "split": "",
    "crafted": "",
    "map_packsize": "",
    "map_iiq": "",
    "map_iir": "",
    "map_gold": "",
    "chart_sulphur": "",
    "chart_shape": "",
    "map_series": "",
    "map_completion_reward": "",
}


def main():
    with open(CONDS) as fh:
        conds = list(csv.DictReader(line for line in fh if not line.startswith("#")))
    by_cpp, by_trade = {}, {}
    for c in conds:
        if c["cpp_filter"]:
            by_cpp.setdefault(c["cpp_filter"], []).append(c["condition"])
        t = c["trade_filter"]
        if t and not t.startswith(("stat:", "query.")):
            by_trade.setdefault(t, []).append(c["condition"])
    # the two socket conditions cover the C++ colour filters too
    by_cpp.setdefault("Colors", []).append("Sockets")
    by_cpp.setdefault("Linked", []).extend(["SocketGroup"])

    cpp = tomllib.load(open(CPP, "rb"))
    grammar = json.load(open(GRAMMAR))

    rows = []
    problems = []
    for f in cpp["filter"]:
        cap = f["caption"]
        names = sorted(set(by_cpp.get(cap, [])))
        if ("cpp", cap) not in KIND:
            problems.append(f"no hand-kept kind for cpp filter {cap!r}")
            continue
        kind, note = KIND[("cpp", cap)]
        if bool(names) != (kind != "none"):
            problems.append(f"cpp {cap!r}: kind {kind!r} disagrees with inversion {names}")
        rows.append(["cpp", cap, f["group"], "; ".join(names), kind, note])

    for g in grammar["filter_groups"]:
        if g["id"] in NOT_ITEM_GROUPS:
            continue
        for f in g["filters"]:
            fid = f["id"]
            names = sorted(set(by_trade.get(fid, [])))
            if fid in TRADE_KIND:
                kind, note = TRADE_KIND[fid]
            elif fid in TRADE_NONE:
                kind, note = "none", TRADE_NONE[fid]
            elif g["id"] in ("heist_filters", "sanctum_filters", "ultimatum_filters"):
                kind, note = "none", "League-mechanic number; the filter language names none of them."
            else:
                problems.append(f"no hand-kept kind for trade filter {fid!r}")
                continue
            if bool(names) != (kind != "none"):
                problems.append(f"trade {fid!r}: kind {kind!r} disagrees with inversion {names}")
            rows.append(["trade", fid, g["id"], "; ".join(names), kind, note])

    if problems:
        for p in problems:
            print("FAIL:", p, file=sys.stderr)
        return 1

    with open(OUT, "w", newline="") as fh:
        fh.write(HEADER + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["side", "filter", "group", "condition", "kind", "note"])
        w.writerows(rows)

    from collections import Counter

    print(len(rows), "rows;", Counter((r[0], r[4]) for r in rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
