#!/usr/bin/env python3
"""The class vocabulary the item-filter page gives, joined to the export's
class names and the trade categories.

Inputs: raw/Path of Exile - Item Filters.html (page save, MANIFEST.md),
        ../repoe/data/class-to-trade-category.csv.
Output: data/class-names.csv.

The page enumerates no class list: `Class` is documented as taking an "Item
class name" and one example uses one. So the script does the only thing the
evidence supports — it scans the documentation region for every token that is
an export class name or class id, and marks whether the page uses it as a value
of the `Class` condition (`class_value`) or the token merely occurs elsewhere
(`incidental`, with the phrase it occurs in).
"""

import csv
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
PAGE = os.path.join(TRACK, "raw", "Path of Exile - Item Filters.html")
CLASSES = os.path.join(SEARCH, "repoe", "data", "class-to-trade-category.csv")
OUT = os.path.join(TRACK, "data", "class-names.csv")

HEADER = (
    "# generated by scripts/extract-class-names.py from raw/Path of Exile - Item Filters.html "
    "(page save, MANIFEST.md) and ../repoe/data/class-to-trade-category.csv. "
    "The page lists NO class vocabulary; `Class` takes an \"Item class name\" and one example "
    "uses one. role=class_value means the page uses the token as a Class value; "
    "role=incidental means the token only occurs in other prose or examples."
)


def main():
    page = open(PAGE, encoding="utf-8", errors="replace").read()
    body = re.sub(r"(?is)<script.*?</script>", "", page)
    body = re.sub(r"(?is)<style.*?</style>", "", body)
    start = body.find('class="item-filter-document-title"')
    doc = body[start: body.rfind("</pre>") + 400]
    visible = " ".join(html.unescape(re.sub(r"(?s)<[^>]+>", " ", doc)).split())

    # values the page actually gives to the Class condition, from its examples
    class_values = set()
    for pre in re.findall(r"<pre>(.*?)</pre>", doc, re.S):
        for line in html.unescape(re.sub(r"(?s)<[^>]+>", "", pre)).splitlines():
            m = re.match(r"\s*Class\s+(?:[=!<>]+\s*)?(.+?)\s*$", line)
            if m:
                class_values.update(
                    v for a, b in re.findall(r'"([^"]+)"|(\S+)', m.group(1)) for v in (a, b) if v
                )

    with open(CLASSES) as fh:
        rows = list(csv.DictReader(line for line in fh if not line.startswith("#")))

    out = []
    for r in rows:
        for column in ("class_name", "item_class"):
            token = r[column]
            if not token:
                continue
            m = re.search(r"(?:^|\W)" + re.escape(token) + r"(?:\W|$)", visible)
            if not m:
                continue
            role = "class_value" if token in class_values else "incidental"
            context = visible[max(0, m.start() - 18): m.end() + 18].strip()
            row = [token, column, role, r["class_name"], r["export_category"], r["trade_id"], context]
            if row not in out:
                out.append(row)
            break

    out.sort(key=lambda x: (x[2] != "class_value", x[0]))
    with open(OUT, "w", newline="") as fh:
        fh.write(HEADER + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(
            ["page_token", "matched_column", "role", "export_class_name", "export_category", "trade_id", "page_context"]
        )
        w.writerows(out)

    print(f"{len(out)} tokens; class values used by the page: {sorted(class_values) or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
