#!/usr/bin/env python3
"""Extract GGG's item-filter conditions and actions from the saved page.

Inputs (absolute paths below):
  raw/Path of Exile - Item Filters.html   the page save (MANIFEST.md)
  ../cpp-search/data/filters.toml         the C++ catalogue, for the cpp_filter join
  ../trade-query/data/grammar.json        the trade filter groups, for the trade_filter join
  ../trade-query/data/stats-2026-09-12.json   trade stat ids, for `stat:` join values
  ../item-facts/data/field-census.csv     export field paths, for the item_field column

Outputs: data/conditions.csv, data/actions.csv.

The page's own columns (name, ribbon, values, example, description) are parsed.
`operand_type`, `operators`, `item_field`, `cpp_filter`, `trade_filter` and
`notes` are hand-kept here and checked against the sibling extracts: an unknown
caption, filter id, stat id or field path aborts the run.
"""

import csv
import html
import os
import re
import sys
import tomllib
import json

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
PAGE = os.path.join(TRACK, "raw", "Path of Exile - Item Filters.html")
CPP = os.path.join(SEARCH, "cpp-search", "data", "filters.toml")
GRAMMAR = os.path.join(SEARCH, "trade-query", "data", "grammar.json")
STATS = os.path.join(SEARCH, "trade-query", "data", "stats-2026-09-12.json")
FIELDS = os.path.join(SEARCH, "item-facts", "data", "field-census.csv")
OUT_C = os.path.join(TRACK, "data", "conditions.csv")
OUT_A = os.path.join(TRACK, "data", "actions.csv")

HEADER_C = (
    "# generated by scripts/extract-conditions.py from raw/Path of Exile - Item Filters.html "
    "(page save, MANIFEST.md), ../cpp-search/data/filters.toml, ../trade-query/data/grammar.json, "
    "../trade-query/data/stats-2026-09-12.json, ../item-facts/data/field-census.csv. "
    "condition/ribbon/values/example are the page's own vocabulary; its prose descriptions are NOT "
    "copied here (BRIEF) and `notes` paraphrases what they add. operand_type, operators, item_field, "
    "cpp_filter, trade_filter and notes are hand-kept and validated against those files. "
    "operators is derived: the page states ONE operator table (= ! != < <= > >= ==) and no "
    "per-condition restriction, so this column records the set that is meaningful for the operand."
)
HEADER_A = (
    "# generated by scripts/extract-conditions.py from raw/Path of Exile - Item Filters.html. "
    "Actions do not read an item; they are listed by name only (BRIEF)."
)

# ---------------------------------------------------------------- page parsing


def visible(fragment):
    fragment = re.sub(r"(?s)<br\s*/?>", " ", fragment)
    fragment = re.sub(r"(?s)<[^>]+>", " ", fragment)
    return " ".join(html.unescape(fragment).split())


def parse_entries(segment):
    entries = []
    starts = [m.start() for m in re.finditer(r'<div class="item-filter-document-body">', segment)]
    starts.append(len(segment))
    for a, b in zip(starts, starts[1:]):
        chunk = segment[a:b]
        ribbon = re.search(r'class="corner-ribbon[^"]*">([^<]*)<', chunk)
        name = re.search(r'class="item-filter-document-name">(.*?)</div>', chunk, re.S)
        desc = re.search(r'class="item-filter-document-description[^"]*">(.*?)$', chunk, re.S)
        body = desc.group(1) if desc else ""
        lead = re.split(r"<div class=", body, maxsplit=1)[0]
        values = re.search(r">Values\s*</h5>(.*?)</div>", body, re.S)
        pres = re.findall(r"<pre>(.*?)</pre>", body, re.S)
        entries.append(
            {
                "ribbon": visible(ribbon.group(1)) if ribbon else "",
                "name": visible(name.group(1)) if name else "",
                "description": visible(lead),
                "values": visible(values.group(1)) if values else "",
                "example": " ; ".join(" ".join(html.unescape(p).split()) for p in pres),
            }
        )
    return entries


def sections(page):
    body = re.sub(r"(?is)<script.*?</script>", "", page)
    body = re.sub(r"(?is)<style.*?</style>", "", body)
    titles = [
        (m.start(), visible(m.group(1)))
        for m in re.finditer(r'class="item-filter-document-title"[^>]*>(.*?)</h[34]>', body, re.S)
    ]
    bounds = {}
    for i, (pos, title) in enumerate(titles):
        end = titles[i + 1][0] if i + 1 < len(titles) else len(body)
        bounds[title] = (pos, end)
    return body, bounds


# ------------------------------------------------------------- the hand join
# condition -> (operand_type, operators, item_field, cpp_filter, trade_filter, notes)
# operators: "cmp" = the full table is meaningful (ordered operand);
#            "eq"  = only equality/negation is meaningful (boolean or set operand).
# item_field: a path in ../item-facts/data/field-census.csv, or absent:<reason>,
#             or derived:<from>.  ";" separates fields, "|" alternatives.
B = "boolean"
N = "numeric"
JOIN = {
    "AlternateQuality": (B, "eq", "absent:no export field for alternate gem quality", "", "", "Gem alternate quality. The trade capture has no filter for it either."),
    "AlwaysShow": (B, "eq", "absent:drop-time UI state", "", "", "PoE2-only ribbon. A drop-label property, not an item property."),
    "AnyEnchantment": (B, "eq", "enchantMods[]", "Enchanted", "", "cpp reads item.enchanted(); trade has an `enchant` stat category but no boolean filter."),
    "ArchnemesisMod": ("name", "eq", "absent:no export field", "", "", "Names an Archnemesis modifier on a monster-modifier item."),
    "AreaLevel": (N, "cmp", "absent:drop context, not on the item", "", "area_level", "SAME SPELLING, DIFFERENT REFERENT: the filter reads the level of the area the item dropped in; trade's area_level reads a map's own area level."),
    "BaseArmour": (N, "cmp", "base-data:RePoE base_items properties", "", "", "Base value before mods. cpp `Armour` and trade `ar` both read the TOTAL."),
    "BaseDefencePercentile": (N, "cmp", "derived:base defence rolls, averaged", "", "base_defence_percentile", "Exact agreement with trade, name and meaning. The page: zero for non-equipment, 100 by default for equipment, otherwise the average percentile of the base defence values. Nothing in the export carries it."),
    "BaseEnergyShield": (N, "cmp", "base-data:RePoE base_items properties", "", "", "Base, not total; cpp `Shield` and trade `es` read the total."),
    "BaseEvasion": (N, "cmp", "base-data:RePoE base_items properties", "", "", "Base, not total; cpp `Evasion` and trade `ev` read the total."),
    "BaseType": ("name", "eq", "baseType|typeLine", "Name", "query.type", "The page states only that == is \"Exact match\"; what a bare value matches is NOT stated (Q1). cpp `Name` is a case-insensitive substring over name+typeLine together, so it also matches unique names. trade's `type` is a query field, not a filter-group id."),
    "BaseWard": (N, "cmp", "base-data:RePoE base_items properties", "", "", "Base, not total; trade `ward` reads the total."),
    "BlightedMap": (B, "eq", "derived:no export field / candidate is the map item name", "", "map_blighted", "The export carries no blighted flag (Q2)."),
    "Class": ("name", "eq", "derived:base type -> item class", "Category", "category", "Three taxonomies: the filter's class names, the C++ `Category` (RePoE class display names, substring-matched), trade's `category` ids (coarser; repoe class-to-trade-category.csv)."),
    "Corrupted": (B, "eq", "corrupted", "Corrupted", "corrupted", "All three name it, same word."),
    "CorruptedMods": (N, "cmp", "absent:corrupted-implicit count not exported", "", "", ""),
    "DropLevel": (N, "cmp", "base-data:RePoE base_items drop_level", "", "", "The level the base starts dropping at; no export field, no cpp filter, no trade filter."),
    "ElderItem": (B, "eq", "influences.elder|elder", "Influenced", "stat:pseudo.pseudo_has_elder_influence", "cpp `Influenced` is one boolean over all six influences; the filter names each separately; trade puts influence in pseudo stats, not a filter."),
    "ElderMap": (B, "eq", "absent:no export field", "", "", ""),
    "EnchantmentPassiveNode": ("name", "eq", "enchantMods[]", "Mods", "stat:enchant.*", "Cluster-jewel enchantment by name."),
    "EnchantmentPassiveNum": (N, "cmp", "derived:enchantMods 'Adds # passive skills'", "Mods", "stat:enchant.*", "The page states it counts only the \"Adds X passive skills\" modifiers."),
    "Exceptional": (B, "eq", "absent:no export field", "", "", "New ribbon. Exceptional gems."),
    "Foulborn": (B, "eq", "mutated", "Mutated", "mutated", "THREE NAMES, ONE THING: GGG's filter says Foulborn, the C++ caption says Mutated, the trade id is `mutated` with the display text \"Foulborn\"; the export field is `mutated`."),
    "FracturedItem": (B, "eq", "fractured", "Fractured", "fractured_item", ""),
    "GemLevel": (N, "cmp", "properties[]", "Level", "gem_level", "cpp reads the \"Level\" property; the export carries it as a property row."),
    "GemQualityType": ("enum", "eq", "derived:no export field / candidate is the typeLine prefix", "", "", "Deleted ribbon: the page marks this condition removed. No trade filter in the 2026-09-12 capture either."),
    "HasCruciblePassiveTree": (B, "eq", "crucible", "", "crucible_item", ""),
    "HasEaterOfWorldsImplicit": (N, "cmp", "tangled", "", "tangled_item", "TIER vs BOOLEAN: the filter compares an implicit tier 1-6, which the page glosses Lesser/Greater/Grand/Exceptional/Exquisite/Perfect; trade's `tangled_item` and the export's `tangled` are yes/no."),
    "HasEnchantment": ("numeric+name", "eq", "enchantMods[]", "Enchanted", "stat:enchant.*", "Takes an optional count and one or more enchantment names."),
    "HasExplicitMod": ("numeric+name", "eq", "explicitMods[]", "Mods", "stat:explicit.*", "The page: 'mod name with numeric condition for number of modifiers', example `HasExplicitMod >=2` over three names. Whether the count is over the named set or over all mods is not stated (Q1). The C++ mod filter ranges a mod VALUE instead; a trade stat group counts matches."),
    "HasImplicitMod": (B, "eq", "implicitMods[]", "", "", "Only \"has at least one\"; no count, no name."),
    "HasInfluence": ("enum", "eq", "influences", "Influenced", "stat:pseudo.pseudo_has_influence_count", "Values: Shaper, Elder, Crusader, Hunter, Redeemer, Warlord, None. The filter names the six; cpp collapses them to one boolean; trade has a pseudo stat per influence and a count."),
    "HasSearingExarchImplicit": (N, "cmp", "searing", "", "searing_item", "Tier 1-6 under the same six names as the Eater implicit; trade's `searing_item` and the export's `searing` are yes/no."),
    "HasVaalUniqueMod": (B, "eq", "absent:no export field", "", "", "PoE2-only ribbon."),
    "Height": (N, "cmp", "h", "", "", "ONLY THE FILTER LANGUAGE NAMES IT: the export carries `h` on every item; neither the C++ app nor trade offers a filter."),
    "Identified": (B, "eq", "identified", "Unidentified", "identified", "cpp's caption is the negation."),
    "Imbued": (B, "eq", "absent:no export field", "", "gem_imbued", ""),
    "IsVaalUnique": (B, "eq", "absent:no export field", "", "", "PoE2-only ribbon. Not trade's `gem_vaal`, which is a Vaal skill gem."),
    "ItemLevel": (N, "cmp", "ilvl", "ilvl", "ilvl", "All three name it."),
    "LinkedSockets": (N, "cmp", "sockets[].group", "Links", "links", "Size of the largest linked group."),
    "MapTier": (N, "cmp", "properties[]", "Map Tier", "map_tier", "All three name it; the export carries it as a property row."),
    "MemoryStrands": (N, "cmp", "memoryItem", "", "memory_level", ""),
    "MirageMap": (B, "eq", "absent:no export field", "", "", "New ribbon."),
    "Mirrored": (B, "eq", "duplicated", "", "mirrored", "No export field is named `mirrored`; `duplicated` is the candidate and GGG's field reference documents names only, so the identification is unverified (Q2). The C++ catalogue has no filter for it."),
    "Quality": (N, "cmp", "properties[]", "Quality", "quality", "All three name it."),
    "Rarity": ("enum", "cmp", "frameType|rarity", "Rarity", "rarity", "ORDERED vs SET: the filter's four values are ordered, so `Rarity > Magic` is legal; cpp's combo and trade's `rarity` option are unordered, and trade adds uniquefoil and nonunique."),
    "Replica": (B, "eq", "replica", "", "", "Only the filter language names it, though the export carries `replica`."),
    "Scourged": (B, "eq", "scourged.tier", "", "scourge_tier", "Boolean vs tier: the filter asks yes/no, trade compares a tier, the export carries the tier."),
    "ShapedMap": (B, "eq", "absent:no export field", "", "", ""),
    "ShaperItem": (B, "eq", "influences.shaper|shaper", "Influenced", "stat:pseudo.pseudo_has_shaper_influence", "As ElderItem."),
    "SocketGroup": ("numeric+colours", "cmp", "sockets[].group;sockets[].sColour", "Linked", "links", "Colours within ONE linked group. Letters: R:Red G:Green B:Blue A:Abyss D:Delve W:White."),
    "Sockets": ("numeric+colours", "cmp", "sockets[];sockets[].sColour", "Sockets", "sockets", "Colours anywhere on the item. cpp splits the count (`Sockets`) from the colours (`Colors`); trade's `sockets` filter carries both shapes."),
    "StackSize": (N, "cmp", "stackSize", "", "stack_size", "The page scopes it to Currency."),
    "SynthesisedItem": (B, "eq", "synthesised", "Synthesized", "synthesised_item", "SPELLING: GGG and trade write Synthesised, the C++ caption writes Synthesized; the export field is `synthesised`."),
    "TransfiguredGem": ("boolean+name", "eq", "derived:no export field / candidate is the typeLine", "", "gem_transfigured", "Updated ribbon: True matches any transfigured gem, or name one."),
    "TwiceCorrupted": (B, "eq", "absent:no export field", "", "", "PoE2-only ribbon."),
    "UberBlightedMap": (B, "eq", "derived:no export field / candidate is the map item name", "", "map_uberblighted", "As BlightedMap (Q2)."),
    "UnidentifiedItemTier": (N, "cmp", "absent:no export field", "", "", "PoE2-only ribbon."),
    "Vestigial": (B, "eq", "absent:no export field", "", "vestigial", "New ribbon."),
    "WaystoneTier": (N, "cmp", "absent:PoE2 field, not in the PoE1 census", "", "", "PoE2-only ribbon; PoE2's name for MapTier."),
    "Width": (N, "cmp", "w", "", "", "As Height: the export has `w` on every item, neither other surface filters on it."),
    "ZanaMemory": (B, "eq", "absent:no export field", "", "", ""),
}

OPERATORS = {
    "cmp": "= ! != < <= > >= ==",
    "eq": "= ! != ==",
}


def main():
    page = open(PAGE, encoding="utf-8", errors="replace").read()
    body, bounds = sections(page)

    a, b = bounds["Conditions"]
    conditions = parse_entries(body[a:b])
    actions = []
    for title in ("Drop Sound", "Other Actions"):
        a, b = bounds[title]
        for e in parse_entries(body[a:b]):
            actions.append((e["name"], title))

    # ---- validate the hand join against the sibling extracts
    cpp = tomllib.load(open(CPP, "rb"))
    captions = {f["caption"] for f in cpp["filter"]}
    grammar = json.load(open(GRAMMAR))
    trade_ids = {f["id"] for g in grammar["filter_groups"] for f in g["filters"]}
    stats = json.load(open(STATS))
    stat_ids = {e["id"] for g in stats["result"] for e in g["entries"]}
    stat_prefixes = {g["id"] for g in stats["result"]}
    fields = set()
    with open(FIELDS) as fh:
        for row in csv.DictReader(line for line in fh if not line.startswith("#")):
            fields.add(row["path"])

    names = [c["name"] for c in conditions]
    problems = []
    if set(names) != set(JOIN):
        problems.append(f"page conditions != hand join: {set(names) ^ set(JOIN)}")
    for name, (_t, _o, field, cppf, tradef, _n) in JOIN.items():
        if cppf and cppf not in captions:
            problems.append(f"{name}: cpp_filter {cppf!r} is not a caption in filters.toml")
        if tradef:
            if tradef.startswith("stat:"):
                sid = tradef[5:]
                ok = sid in stat_ids or (sid.endswith(".*") and sid[:-2] in stat_prefixes)
                if not ok:
                    problems.append(f"{name}: trade stat {sid!r} unknown")
            elif tradef.startswith("query."):
                if tradef[6:] not in grammar["query_shape"]:
                    problems.append(f"{name}: query shape key {tradef!r} unknown")
            elif tradef not in trade_ids:
                problems.append(f"{name}: trade_filter {tradef!r} is not a filter id in grammar.json")
        for tok in field.split(";"):
            tok = tok.strip()
            for alt in tok.split("|"):
                if alt.startswith(("absent:", "derived:", "base-data:")) or not alt:
                    continue
                if alt not in fields:
                    problems.append(f"{name}: item_field {alt!r} is not a path in field-census.csv")
    if problems:
        for p in problems:
            print("FAIL:", p, file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    with open(OUT_C, "w", newline="") as fh:
        fh.write(HEADER_C + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(
            [
                "condition", "ribbon", "operand_type", "operators", "values", "example",
                "item_field", "cpp_filter", "trade_filter", "notes",
            ]
        )
        for c in conditions:
            t, o, field, cppf, tradef, note = JOIN[c["name"]]
            w.writerow(
                [
                    c["name"], c["ribbon"], t, OPERATORS[o], c["values"], c["example"],
                    field, cppf, tradef, note,
                ]
            )

    with open(OUT_A, "w", newline="") as fh:
        fh.write(HEADER_A + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["action", "section"])
        for name, section in actions:
            w.writerow([name, section])

    print(f"conditions: {len(conditions)}  actions: {len(actions)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
