#!/usr/bin/env python3
"""repoe, added extract: the per-base defence ranges the export carries, for the base-defence percentile.

Inputs (read-only; the clone must sit at the manifest's commit or this refuses to run):
  ../../../../../poe1/data/base_items.json   every base: name, class, release state, domain and
                                             `properties.armour` / `.evasion` / `.energy_shield` / `.ward`
                                             as `{min, max}` or null, and `.block` as a number or null

Outputs (data/, regenerable; the first line names this script and its input):
  base-defences.csv   one row per export base entry carrying at least one non-null defence or block value,
                      keyed by its metadata id: the four ranges as min/max pairs and block, empty where
                      null. A base with every one null is left out. Rows are export entries, not names: a
                      name with several metadata entries (Two-Toned Boots) keeps one row per entry, its
                      own ranges on each, told apart by `metadata_id`.

Printed: bases with any non-null defence (the CSV's row count), and a per-class count of them.
"""

import collections
import csv
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))
POE1 = os.path.join(CLONES, "poe1")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
DATA = os.path.join(TRACK, "data")
HEADER = "# generated by scripts/base-defences.py from poe1/data/base_items.json @ e2bd511a"

RANGES = ("armour", "evasion", "energy_shield", "ward")  # each `{min, max}` or null


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def defences(b):
    """(the four `{min, max}` or None, block or None) for one base entry."""
    p = b.get("properties") or {}
    return [p.get(k) for k in RANGES], p.get("block")


def main():
    pinned(POE1, POE1_COMMIT)
    os.makedirs(DATA, exist_ok=True)
    bases = json.load(open(os.path.join(POE1, "data", "base_items.json")))

    rows = []
    per_class = collections.Counter()
    for key, b in sorted(bases.items(), key=lambda kv: (kv[1]["name"], kv[0])):
        ranges, block = defences(b)
        if not any(r is not None for r in ranges) and block is None:
            continue
        cells = []
        for r in ranges:
            cells += ["", ""] if r is None else [r["min"], r["max"]]
        rows.append([key, b["name"], b["item_class"], b["release_state"], b["domain"]] + cells +
                    ["" if block is None else block])
        per_class[b["item_class"]] += 1

    with open(os.path.join(DATA, "base-defences.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["metadata_id", "name", "item_class", "release_state", "domain",
                    "armour_min", "armour_max", "evasion_min", "evasion_max",
                    "energy_shield_min", "energy_shield_max", "ward_min", "ward_max", "block"])
        w.writerows(rows)

    print(f"export base entries: {len(bases)}; with a non-null defence or block: {len(rows)} "
          f"({len({r[1] for r in rows})} distinct names)")
    print("  per class:", ", ".join(f"{c} {n}" for c, n in per_class.most_common()))
    counts = [f"{k} {sum(1 for r in rows if r[5 + 2 * i] != '')}" for i, k in enumerate(RANGES)]
    counts.append(f"block {sum(1 for r in rows if r[13] != '')}")
    print("  with a non-null:", ", ".join(counts))


if __name__ == "__main__":
    main()
