#!/usr/bin/env python3
"""repoe step 3: the export's base and class taxonomy against the trade site's categories and the corpus.

Inputs (read-only; the clone must sit at the manifest's commit or this refuses to run):
  ../../../../../poe1/data/base_items.json      every base: name, item class, tags, release state, domain
  ../../../../../poe1/data/item_classes.json    the 103 classes: display name, category
  ../trade-query/data/items-2026-09-12.json     the trade site's 22 base-type categories (3,733 base types)
  ../trade-query/data/filters-2026-09-12.json   the trade site's 83 category ids (`type_filters.category`)
  ../item-facts/raw/spike-GERWARIC_7694-2026-09-13.db, ../item-facts/raw/cpp-userstore-GERWARIC_7694-2026-09-13.db
                                                 the corpus's `baseType` values (local only; skipped when absent)
  ../trade-query/raw/searches/*-fetch.json      the `Item Class:` line of listed items (local only; skipped when absent)

Outputs (data/, regenerable; the first line names this script and its inputs):
  base-taxonomy.csv         one row per export base name: class, class name, export category, tags, release state,
                            the trade coarse category items.json gives the name, the trade category id this table
                            predicts and the basis of the prediction, corpus items and frame types carrying it
  class-to-trade-category.csv   one row per export class: its trade category id (or none), the basis, bases, corpus items

Printed: the 83 ids by how they are generated, the coarse-category agreement, corpus coverage, the fetch check.
"""

import collections
import csv
import glob
import json
import os
import sqlite3
import subprocess
import sys
import base64

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))
POE1 = os.path.join(CLONES, "poe1")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
DATA = os.path.join(TRACK, "data")
TQ = os.path.join(SEARCH, "trade-query", "data")
RAW_SPIKE = os.path.join(SEARCH, "item-facts", "raw", "spike-GERWARIC_7694-2026-09-13.db")
RAW_CPP = os.path.join(SEARCH, "item-facts", "raw", "cpp-userstore-GERWARIC_7694-2026-09-13.db")
FETCHES = os.path.join(SEARCH, "trade-query", "raw", "searches", "*-fetch.json")
HEADER = "# generated by scripts/base-taxonomy.py from poe1/data/base_items.json and item_classes.json @ e2bd511a, ../trade-query/data/items-2026-09-12.json and filters-2026-09-12.json, the item-facts raw stores (local)"

# The export's class -> the trade site's category id. `basis` says what decides it: the class alone, the class plus a
# name rule (below), the items.json join for classes whose bases the site files elsewhere, or nothing (not listed).
CLASS_TO_TRADE = {
    "Claw": "weapon.claw", "Dagger": "weapon.basedagger", "Rune Dagger": "weapon.runedagger", "Wand": "weapon.wand",
    "One Hand Sword": "weapon.basesword", "Thrusting One Hand Sword": "weapon.rapier", "One Hand Axe": "weapon.oneaxe",
    "One Hand Mace": "weapon.basemace", "Sceptre": "weapon.sceptre", "Bow": "weapon.bow", "Staff": "weapon.basestaff",
    "Warstaff": "weapon.warstaff", "Two Hand Sword": "weapon.twosword", "Two Hand Axe": "weapon.twoaxe",
    "Two Hand Mace": "weapon.twomace", "FishingRod": "weapon.rod",
    "Body Armour": "armour.chest", "Boots": "armour.boots", "Gloves": "armour.gloves", "Helmet": "armour.helmet",
    "Shield": "armour.shield", "Quiver": "armour.quiver",
    "Amulet": "accessory.amulet", "Belt": "accessory.belt", "Ring": "accessory.ring", "Trinket": "accessory.trinket",
    "Active Skill Gem": "gem.activegem", "Support Skill Gem": "gem.supportgem",
    "Jewel": "jewel.base", "AbyssJewel": "jewel.abyss",
    "LifeFlask": "flask", "ManaFlask": "flask", "HybridFlask": "flask", "UtilityFlask": "flask", "UtilityFlaskCritical": "flask",
    "Map": "map", "MapKey": "map", "MapFragment": "map.fragment", "LabyrinthMapItem": "map.fragment", "Breachstone": "map.breachstone",
    "MiscMapItem": "map", "VaultKey": "map", "InstanceLocalItem": "map",
    "StackableCurrency": "currency", "Currency": "currency", "Gold": "currency", "UniqueFragment": "currency.piece",
    "DelveSocketableCurrency": "currency.resonator", "DelveStackableSocketableCurrency": "currency.resonator",
    "Incubator": "currency.incubator", "IncubatorStackable": "currency.incubator", "HeistObjective": "currency.heistobjective",
    "Leaguestone": "leaguestone", "MemoryLine": "memoryline", "DivinationCard": "card", "ItemisedCorpse": "corpse",
    "HeistEquipmentWeapon": "heistequipment.heistweapon", "HeistEquipmentTool": "heistequipment.heisttool",
    "HeistEquipmentUtility": "heistequipment.heistutility", "HeistEquipmentReward": "heistequipment.heistreward",
    "HeistContract": "heistmission.contract", "HeistBlueprint": "heistmission.blueprint", "ExpeditionLogbook": "logbook",
    "ItemisedSanctum": "sanctum.research", "Relic": "sanctum.relic", "SanctumSpecialRelic": "sanctum.relic",
    "Tincture": "tincture", "AtlasRelic": "idol", "RemovedItem": "graft", "BrequelFruit": "wombgift",
    "CocoonedItem": "enshrouded", "DeepwaterChart": "chart",
}
# (class, predicate on the base name) -> the finer id; the first that fires wins
NAME_RULES = [
    ("Support Skill Gem", lambda n: n.startswith("Awakened "), "gem.supportgemplus"),
    ("Jewel", lambda n: n.endswith("Cluster Jewel"), "jewel.cluster"),
    ("MapFragment", lambda n: "Scarab" in n, "map.scarab"),
    ("MiscMapItem", lambda n: "Invitation" in n, "map.invitation"),
    ("StackableCurrency", lambda n: n.endswith(" Fossil"), "currency.fossil"),
    ("StackableCurrency", lambda n: n.startswith("Omen of "), "currency.omen"),
    ("StackableCurrency", lambda n: n.startswith("Tattoo of "), "currency.tattoo"),
]
NOT_GENERABLE = {"monster.beast", "monster.yellowbeast", "monster.redbeast"}  # itemised beasts are not bases
PARENTS = {  # union ids the site derives from the leaves
    "weapon", "weapon.one", "weapon.onemelee", "weapon.twomelee", "weapon.dagger", "weapon.onesword", "weapon.onemace",
    "weapon.staff", "armour", "accessory", "gem", "jewel", "heistequipment", "heistmission",
}


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def predict(cls, name):
    for c, pred, fine in NAME_RULES:
        if c == cls and pred(name):
            return fine, "class + name rule"
    if cls in CLASS_TO_TRADE:
        return CLASS_TO_TRADE[cls], "class"
    return "", "none"


def corpus():
    """baseType -> Counter(frameTypeId) over both stores, deduped by item id (the spike's fetch wins)."""
    seen = {}
    if os.path.exists(RAW_SPIKE):
        db = sqlite3.connect(f"file:{RAW_SPIKE}?mode=ro", uri=True)
        for iid, realm, js in db.execute("SELECT id, realm, json FROM items"):
            if realm == "pc":
                j = json.loads(js); seen[iid] = (j.get("baseType"), j.get("frameTypeId"))
    if os.path.exists(RAW_CPP):
        db = sqlite3.connect(f"file:{RAW_CPP}?mode=ro", uri=True)
        for table in ("stashes", "characters"):
            for realm, js in db.execute(f"SELECT realm, json_data FROM {table} WHERE json_data IS NOT NULL"):
                if realm != "pc":
                    continue
                for it in json.loads(js).get("items", []):
                    seen.setdefault(it["id"], (it.get("baseType"), it.get("frameTypeId")))
                    for s in it.get("socketedItems", []) or []:
                        seen.setdefault(s["id"], (s.get("baseType"), s.get("frameTypeId")))
    out = collections.defaultdict(collections.Counter)
    for bt, ft in seen.values():
        out[bt][ft] += 1
    return out


def fetch_classes():
    out = {}
    for f in glob.glob(FETCHES):
        try:
            d = json.load(open(f))
        except ValueError:
            continue
        for r in d.get("result", []):
            it = r["item"]; t = it.get("extended", {}).get("text")
            if t:
                first = base64.b64decode(t).decode("utf-8", "replace").split("\n")[0].rstrip("\r")  # the clipboard text is CRLF
                if first.startswith("Item Class: "):
                    out[it.get("baseType")] = first[len("Item Class: "):]
    return out


def main():
    pinned(POE1, POE1_COMMIT)
    os.makedirs(DATA, exist_ok=True)
    bases = json.load(open(os.path.join(POE1, "data", "base_items.json")))
    classes = json.load(open(os.path.join(POE1, "data", "item_classes.json")))
    trade_items = json.load(open(os.path.join(TQ, "items-2026-09-12.json")))["result"]
    filters = json.load(open(os.path.join(TQ, "filters-2026-09-12.json")))["result"]
    ids83 = [o["id"] for g in filters for f in g["filters"] if f["id"] == "category" for o in f["option"]["options"] if o["id"]]
    coarse = collections.defaultdict(set)
    for c in trade_items:
        for e in c["entries"]:
            coarse[e["type"]].add(c["id"])

    # one row per name: prefer a released base, then the first seen
    by_name = {}
    for key, b in bases.items():
        cur = by_name.get(b["name"])
        if cur is None or (cur["release_state"] != "released" and b["release_state"] == "released"):
            by_name[b["name"]] = dict(b, key=key)

    corp = corpus()
    fetch = fetch_classes()

    rows = []; agree = collections.Counter(); per_class = collections.defaultdict(lambda: {"bases": 0, "items": 0, "released": 0})
    for name, b in sorted(by_name.items()):
        cls = b["item_class"]; fine, basis = predict(cls, name)
        tc = sorted(coarse.get(name, ()))
        items = sum(corp.get(name, {}).values())
        frames = " ".join(f"{k}:{v}" for k, v in sorted(corp.get(name, {}).items(), key=lambda kv: -kv[1]))
        if tc:
            agree["listed, agrees" if fine and fine.split(".")[0] in tc else "listed, disagrees" if fine else "listed, no prediction"] += 1
        else:
            agree["not listed by the site"] += 1
        per_class[cls]["bases"] += 1; per_class[cls]["items"] += items; per_class[cls]["released"] += b["release_state"] == "released"
        rows.append([name, cls, classes[cls]["name"], classes[cls]["category"] or "", b["release_state"], b["domain"],
                     " ".join(b["tags"]), " ".join(tc), fine, basis, items, frames])

    with open(os.path.join(DATA, "base-taxonomy.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["name", "item_class", "class_name", "export_category", "release_state", "domain", "tags",
                    "trade_coarse_by_name", "trade_id_predicted", "basis", "corpus_items", "corpus_frames"])
        w.writerows(rows)
    with open(os.path.join(DATA, "class-to-trade-category.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["item_class", "class_name", "export_category", "trade_id", "basis", "name_rules", "bases", "released", "corpus_items"])
        for cls in classes:
            rules = " ".join(fine for c, _, fine in NAME_RULES if c == cls)
            w.writerow([cls, classes[cls]["name"], classes[cls]["category"] or "", CLASS_TO_TRADE.get(cls, ""),
                        "class" if cls in CLASS_TO_TRADE else "none", rules, per_class[cls]["bases"], per_class[cls]["released"], per_class[cls]["items"]])

    generated = {fine for fine, _ in (predict(c, "") for c in classes)} | {fine for _, _, fine in NAME_RULES}
    generated.discard("")
    leaves = [i for i in ids83 if i not in PARENTS]
    print(f"trade category ids: {len(ids83)}; parents (unions of leaves): {len(PARENTS & set(ids83))}; leaves {len(leaves)}")
    print(f"  leaves generated by a class: {sum(1 for i in leaves if i in generated and i not in {f for _, _, f in NAME_RULES})}; "
          f"by a class plus a name rule: {sum(1 for i in leaves if i in {f for _, _, f in NAME_RULES})}; "
          f"not generable from bases: {sorted(i for i in leaves if i in NOT_GENERABLE)}; "
          f"neither: {sorted(i for i in leaves if i not in generated and i not in NOT_GENERABLE)}")
    print(f"export classes: {len(classes)}, with a trade id: {len(CLASS_TO_TRADE)}, without: {sorted(c for c in classes if c not in CLASS_TO_TRADE)}")
    print(f"export base names: {len(by_name)}; coarse-category agreement with items.json: {dict(agree)}")
    dis = [r for r in rows if r[7] and r[8] and r[8].split('.')[0] not in r[7].split()]
    for r in dis[:20]:
        print("   disagrees:", r[0], r[1], "site:", r[7], "predicted:", r[8])
    site_names = set(coarse)
    print(f"site base types: {len(site_names)}; in the export by name: {sum(1 for n in site_names if n in by_name)}; "
          f"not: {collections.Counter(next(iter(coarse[n])) for n in site_names if n not in by_name)}")

    # the corpus
    total = sum(sum(c.values()) for c in corp.values())
    if total:
        matched = {bt: c for bt, c in corp.items() if bt in by_name}
        transfigured = {bt: c for bt, c in corp.items() if bt not in by_name and " of " in (bt or "") and bt.rsplit(" of ", 1)[0] in by_name}
        unmatched = {bt: c for bt, c in corp.items() if bt not in by_name and bt not in transfigured}
        print(f"corpus (pc): {total} items, {len(corp)} distinct baseType; joined to an export base: {sum(sum(c.values()) for c in matched.values())} items "
              f"({len(matched)} names); transfigured gems joined by stripping ' of …': {sum(sum(c.values()) for c in transfigured.values())} ({len(transfigured)}); "
              f"unmatched: {sum(sum(c.values()) for c in unmatched.values())} ({len(unmatched)} names)")
        um = collections.Counter()
        for bt, c in unmatched.items():
            for ft, n in c.items(): um[(ft, bt)] += n
        print("  largest unmatched:", um.most_common(12))
        by_id = collections.Counter()
        for bt, c in matched.items():
            fine, _ = predict(by_name[bt]["item_class"], bt); by_id[fine or "(no trade id)"] += sum(c.values())
        print("  corpus items by predicted trade id:", by_id.most_common(40))
    if fetch:
        ok = sum(1 for bt, cn in fetch.items() if bt in by_name and classes[by_name[bt]["item_class"]]["name"] == cn)
        bad = [(bt, cn, classes[by_name[bt]["item_class"]]["name"] if bt in by_name else "?") for bt, cn in fetch.items() if not (bt in by_name and classes[by_name[bt]["item_class"]]["name"] == cn)]
        print(f"fetch check: {len(fetch)} listed base types; the export's class name equals the clipboard's `Item Class:` for {ok}; differs: {bad}")


if __name__ == "__main__":
    main()
