#!/usr/bin/env python3
"""repoe step 2: the Path of Building hash experiment, run as a join because the export lacks the hashes.

Path of Building derives a trade stat id as MurmurHash2 (seed 0x02312233) over the concatenated
little-endian `Stats.dat` hashes of the stats a mod line renders (`src/Export/Scripts/mods.lua`), and
its generated `src/Data/Mod*.lua` tables carry the result per mod id as `tradeHashes`. RePoE's export
does not carry the `Stats.dat` hash column (`stats.json` holds locality and aliases only), so the
recipe cannot be re-run from the export. What can be checked, mod by mod, is whether the export's
text join (`stat_translations.json`, `trade_stats`) names the same trade id Path of Building's hash
does — and, where it does not, why.

Inputs (read-only; each clone must sit at the manifest's commit or this refuses to run):
  ../../../../../PathOfBuilding/src/Data/Mod*.lua   one mod per line: id, description lines, tradeHashes
  ../../../../../poe1/data/mods.json                 mod id -> ordered stats (id, min, max), domain, generation type
  ../../../../../poe1/data/stat_translations.json    stat ids -> English strings and the text-joined trade ids
  ../trade-query/data/stats-2026-09-12.json          the trade capture, for the ids' categories

Outputs (data/, regenerable; the first line names this script and its inputs):
  hash-check.csv    one row per (trade number, stat group, class): the class under the acceptance rule —
                    `reproduced`, `explained` with its reason, or `unexplained` — the export's numbers for the
                    group, how many Path of Building mods carry it and one of them with its description
  stat-hashes.csv   one row per stat id whose trade number is a single-stat hash: the `Stats.dat` hash
                    recovered by inverting MurmurHash2 on the 4-byte key (a bijection), its source trade id,
                    and whether the export or Path of Building supplied the attribution

Printed: the class counts and the reason table the README quotes.
"""

import collections
import csv
import json
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))
POE1 = os.path.join(CLONES, "poe1")
POB = os.path.join(CLONES, "PathOfBuilding")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
POB_COMMIT = "16de4b82d57f1c0de6eb40f37143c32d4da36a02"  # MANIFEST.md
DATA = os.path.join(TRACK, "data")
CAPTURE = os.path.join(SEARCH, "trade-query", "data", "stats-2026-09-12.json")
HEADER = "# generated by scripts/hash-check.py from PathOfBuilding/src/Data/Mod*.lua @ 16de4b82, poe1/data/mods.json and stat_translations.json @ e2bd511a, ../trade-query/data/stats-2026-09-12.json"

SEED = 0x02312233
M32 = 0xFFFFFFFF
MUL = 0x5BD1E995


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def murmur2(data: bytes, seed: int) -> int:
    """MurmurHash2, 32-bit (Appleby); checked against SMHasher's verification value 0x27864C1E."""
    ln = len(data); h = (seed ^ ln) & M32; i = 0
    while ln >= 4:
        k = int.from_bytes(data[i:i + 4], "little")
        k = (k * MUL) & M32; k ^= k >> 24; k = (k * MUL) & M32
        h = (h * MUL) & M32; h ^= k
        i += 4; ln -= 4
    if ln:
        h ^= int.from_bytes(data[i:] + b"\0" * (4 - ln), "little"); h = (h * MUL) & M32
    h ^= h >> 13; h = (h * MUL) & M32; h ^= h >> 15
    return h


MUL_INV = pow(MUL, -1, 1 << 32)


def unxorshift(v, s):
    r = v
    for _ in range(32 // s + 1):
        r = v ^ (r >> s)
    return r & M32


def inverse4(num: int, seed: int = SEED) -> int:
    """The 4-byte key whose MurmurHash2 is `num`: every step of the 4-byte case is invertible."""
    h = unxorshift(num, 15); h = (h * MUL_INV) & M32; h = unxorshift(h, 13)
    k = h ^ (((seed ^ 4) * MUL) & M32)
    k = (k * MUL_INV) & M32; k = unxorshift(k, 24); k = (k * MUL_INV) & M32
    return k


LINE = re.compile(r'^\t\["(?P<id>[^"]+)"\] = \{ (?P<body>.*) \},$')
HASHES = re.compile(r"tradeHashes = \{ (?P<hashes>.*) \}$")
ONE = re.compile(r'\[(?P<num>\d+)\] = \{ (?P<desc>(?:"[^"]*"(?:, "[^"]*")*)?) \}, ')


def pob_mods():
    """(table, mod id, {trade number: [description lines]}) per mod line in every Mod*.lua."""
    for name in sorted(os.listdir(os.path.join(POB, "src", "Data"))):
        if not (name.startswith("Mod") and name.endswith(".lua")):
            continue
        for line in open(os.path.join(POB, "src", "Data", name), encoding="utf-8"):
            m = LINE.match(line.rstrip("\r\n"))
            if not m:
                continue
            h = HASHES.search(m["body"])
            if not h:
                continue
            hashes = {int(o["num"]): [d.strip('"') for d in re.findall(r'"[^"]*"', o["desc"])] for o in ONE.finditer(h["hashes"] + " ")}
            yield name[:-4], m["id"], hashes


def number(trade_id: str) -> int | None:
    key = trade_id.split(".", 1)[1].split("|", 1)[0]
    return int(key[5:]) if key.startswith("stat_") and key[5:].isdigit() else None


def groups(stats):
    """The recipe's grouping of a mod's ordered stats: a `minimum` stat followed by a `maximum` one hashes as a pair."""
    out = []; i = 0
    while i < len(stats) and i < 6:
        sid = stats[i]["id"]
        if "minimum" in sid and i + 1 < len(stats) and "maximum" in stats[i + 1]["id"]:
            out.append((sid, stats[i + 1]["id"])); i += 2
        else:
            out.append((sid,)); i += 1
    return out


def main():
    pinned(POE1, POE1_COMMIT); pinned(POB, POB_COMMIT)
    os.makedirs(DATA, exist_ok=True)
    mods = json.load(open(os.path.join(POE1, "data", "mods.json")))
    entries = json.load(open(os.path.join(POE1, "data", "stat_translations.json")))
    capture_cats = collections.defaultdict(set)
    for c in json.load(open(CAPTURE))["result"]:
        for e in c["entries"]:
            n = number(e["id"])
            if n is not None:
                capture_cats[n].add(c["id"])

    # translation entries by the exact set of stat ids they render, and by each single id
    by_ids = collections.defaultdict(list)
    for n, e in enumerate(entries):
        by_ids[frozenset(e["ids"])].append(n)

    def numbers_for(group):
        """The trade numbers the export's text join gives a stat group, and the entries consulted."""
        ns = set(); ents = list(by_ids.get(frozenset(group), []))
        if not ents and len(group) == 1:  # a single stat rendered only inside a multi-id entry
            ents = [n for ids, ns_ in by_ids.items() if group[0] in ids for n in ns_]
        for n in ents:
            for ts in entries[n].get("trade_stats") or []:
                v = number(ts["id"])
                if v is not None:
                    ns.add(v)
        return ns, ents

    classes = collections.Counter(); reasons = collections.Counter(); rows = 0
    attributed = {}  # trade number -> (stat id, source) for single-stat groups
    resolved = 0     # export gave several numbers for the group, Path of Building's picks one
    examples = collections.defaultdict(list); distinct = collections.defaultdict(set)
    agg = {}  # (number, group, class, reason) -> [mods, first table, first mod, description, export numbers, categories, english]
    if True:
        for table, mod_id, hashes in pob_mods():
            mod = mods.get(mod_id)
            gs = groups(mod["stats"]) if mod else []
            per_group = [(g,) + numbers_for(g) for g in gs]
            for num, desc in sorted(hashes.items()):
                cls = reason = ""; grp = (); export_nums = set(); estr = ""; ents = []
                in_capture = num in capture_cats
                if mod is None:
                    cls, reason = "explained", "mod id not in the export"
                else:
                    hit = [(g, ns, e) for g, ns, e in per_group if num in ns]
                    if hit:
                        grp, export_nums, ents = hit[0]
                        cls = "reproduced"
                        if len(export_nums) > 1:
                            reason = "export text join ambiguous; the hash picks one"; resolved += 1
                        if len(grp) == 1:
                            attributed.setdefault(num, (grp[0], "export+pob"))
                    elif not in_capture:
                        # the recipe minted a number the site does not have: checkable against the capture
                        cls, reason = "explained", "number not in the capture (recipe output the site lacks)"
                        grp = per_group[0][0] if per_group else ()
                    else:
                        untranslated = [(g, ns, e) for g, ns, e in per_group if not e]
                        unjoined = [(g, ns, e) for g, ns, e in per_group if e and not ns]
                        if untranslated:
                            grp, export_nums, ents = untranslated[0]; cls, reason = "explained", "stat group has no translation entry"
                        elif unjoined:
                            grp, export_nums, ents = unjoined[0]; cls, reason = "explained", "translation entry has no trade_stats (text join failed); the hash supplies it"
                        else:
                            cls, reason = "unexplained", "in the capture, every group text-joined, none to this number"
                            grp, export_nums, ents = per_group[0] if per_group else ((), set(), [])
                        if len(grp) == 1 and cls == "explained" and num not in attributed:
                            attributed[num] = (grp[0], "pob")
                if ents:
                    estr = entries[ents[0]]["English"][0]["string"]
                classes[cls] += 1; reasons[(cls, reason)] += 1; rows += 1; distinct[(cls, reason)].add(num)
                if len(examples[(cls, reason)]) < 12:
                    examples[(cls, reason)].append((table, mod_id, num, grp, sorted(export_nums), desc, estr, sorted(capture_cats.get(num, ()))))
                key = (num, "|".join(grp), cls, reason)
                if key not in agg:
                    agg[key] = [0, table, mod_id, " / ".join(desc), " ".join(str(n) for n in sorted(export_nums)),
                                " ".join(sorted(capture_cats.get(num, ()))) or "not in capture", estr.replace("\n", "\\n")]
                agg[key][0] += 1
    with open(os.path.join(DATA, "hash-check.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["trade_number", "group", "class", "reason", "mods", "table", "mod", "pob_description", "export_numbers", "capture_categories", "export_string"])
        for (num, grp, cls, reason), v in sorted(agg.items()):
            w.writerow([num, grp, cls, reason] + v)

    # single-stat hashes recovered from the export's own join, no Path of Building needed
    from_export = {}
    for e in entries:
        if len(e["ids"]) == 1:
            for ts in e.get("trade_stats") or []:
                v = number(ts["id"])
                if v is not None:
                    from_export.setdefault(v, e["ids"][0])
    with open(os.path.join(DATA, "stat-hashes.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["stat_id", "stats_dat_hash", "trade_number", "attributed_by"])
        seen = {}
        for num, sid in sorted(from_export.items()):
            seen[sid] = (num, "export")
        for num, (sid, src) in sorted(attributed.items()):
            seen.setdefault(sid, (num, src))
        conflicts = 0
        for sid, (num, src) in sorted(seen.items()):
            h = inverse4(num)
            assert murmur2(struct.pack("<I", h), SEED) == num
            w.writerow([sid, h, num, src])
        # a stat id attributed to two different numbers is a conflict worth printing
        by_sid = collections.defaultdict(set)
        for num, sid in from_export.items(): by_sid[sid].add(num)
        for num, (sid, _) in attributed.items(): by_sid[sid].add(num)
        conflicts = {s: ns for s, ns in by_sid.items() if len(ns) > 1}

    print(f"rows: {rows}; classes: {dict(classes)}")
    for (cls, reason), n in sorted(reasons.items(), key=lambda kv: -kv[1]):
        print(f"  {n:6} rows  {len(distinct[(cls, reason)]):5} distinct numbers  {cls:12} {reason}")
    all_nums = set().union(*distinct.values())
    print(f"distinct numbers Path of Building minted: {len(all_nums)}; in the capture: {sum(1 for n in all_nums if n in capture_cats)}")
    print(f"reproduced rows where the export's text join was ambiguous and the hash picks one: {resolved}")
    print(f"stat ids with a recovered Stats.dat hash: {len(seen)} (export alone: {len(from_export)} numbers)")
    export_conf = {s_: ns for s_, ns in by_sid.items() if len({n for n in ns if from_export.get(n) == s_}) > 1}
    pob_pick = {s_: {n for n in ns if attributed.get(n, ("", ""))[0] == s_} for s_, ns in export_conf.items()}
    print(f"stat ids the export's text join gives several numbers: {len(export_conf)}; "
          f"of these the hash attributes exactly one: {sum(1 for v in pob_pick.values() if len(v) == 1)}, none: {sum(1 for v in pob_pick.values() if not v)}")
    print(f"stat ids attributed to more than one trade number (export and hash together): {len(conflicts)}", dict(list(conflicts.items())[:6]))
    if "--examples" in sys.argv:
        for key, exs in examples.items():
            print("\n==", key)
            for ex in exs:
                print("  ", ex)


if __name__ == "__main__":
    main()
