#!/usr/bin/env python3
"""repoe step 5: the export's mods as one flat index — mod -> stats, domain, generation type, tags, weights.

Inputs (read-only; the clone must sit at the manifest's commit or this refuses to run):
  ../../../../../poe1/data/mods.json   every mod the game defines (40,355 at e2bd511a)

Outputs (data/, regenerable; the first line names this script and its input):
  mod-stat-index.csv   one row per mod whose domain can reach an item a stash holds (the item, flask,
                       jewel, charm, tincture, graft, crafted, veiled and unveiled domains, minus unique and crucible mods): id, name, type
                       (the mod group), domain, generation type, required level, stats as id:min:max,
                       spawn weights as tag:weight, the tags it adds and implies (the rendered text stays in mods.json)

Printed: mods per domain and generation type in the index, and what was left out.
"""

import collections
import csv
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))
POE1 = os.path.join(CLONES, "poe1")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
DATA = os.path.join(TRACK, "data")
HEADER = "# generated by scripts/mod-stat-index.py from poe1/data/mods.json @ e2bd511a"
ITEM_DOMAINS = ("item", "flask", "abyss_jewel", "affliction_jewel", "affliction_charm", "tincture", "brequel_graft",
                "crafted", "veiled", "unveiled", "mercenary")
# left out by generation type: a unique's mods are its own lines and the unique is known by name (10,838 mods);
# the crucible trees are retired content (2,634)
SKIP_GENERATION = ("unique", "crucible_tree", "crucible_unique_tree")


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def main():
    pinned(POE1, POE1_COMMIT)
    mods = json.load(open(os.path.join(POE1, "data", "mods.json")))
    os.makedirs(DATA, exist_ok=True)
    kept = collections.Counter(); left = collections.Counter(); gen = collections.Counter(); n = 0
    with open(os.path.join(DATA, "mod-stat-index.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["id", "name", "type", "domain", "generation_type", "required_level", "n_stats", "stats", "spawn_weights",
                    "generation_weights", "adds_tags", "implicit_tags", "essence_only"])
        for mid, m in mods.items():
            if m["domain"] not in ITEM_DOMAINS:
                left[m["domain"]] += 1; continue
            if m["generation_type"] in SKIP_GENERATION:
                left[m["generation_type"]] += 1; continue
            kept[m["domain"]] += 1; gen[m["generation_type"]] += 1; n += 1
            w.writerow([mid, m["name"], m["type"], m["domain"], m["generation_type"], m["required_level"], len(m["stats"]),
                        " ".join(f"{s['id']}:{s['min']}:{s['max']}" for s in m["stats"]),
                        " ".join(f"{s['tag']}:{s['weight']}" for s in m["spawn_weights"]),
                        " ".join(f"{s['tag']}:{s['weight']}" for s in m["generation_weights"]),
                        " ".join(m["adds_tags"]), " ".join(m["implicit_tags"]), "yes" if m["is_essence_only"] else ""])
    print(f"mods in the index: {n} of {len(mods)}; by domain {dict(kept)}; by generation type {dict(gen.most_common())}")
    print(f"left out, by domain or generation type: {dict(left.most_common())}")
    print("bytes:", os.path.getsize(os.path.join(DATA, "mod-stat-index.csv")))


if __name__ == "__main__":
    main()
