#!/usr/bin/env python3
"""repoe step 4: can a private-API display line be given GGG's stat identity through the export?

item-facts' census reduced every mod line the stores hold to a template (`#` for each number,
`data/mod-templates.csv`); RePoE's translations render stat ids to strings with positional
placeholders. Both are brought to one canonical form here — `[Tag|Display]` markup collapsed to its
display text, a sign directly before a placeholder dropped, placeholders `#` — and matched exactly,
whole template first, then line by line for the multi-line templates. A template that matches one
translation entry names its stat ids; one that matches several is ambiguous without more context
(the `(Local)` twins the trade site disambiguates by suffix, and any other stats that render alike).

Inputs (read-only; the clone must sit at the manifest's commit or this refuses to run):
  ../item-facts/data/mod-templates.csv                  the census: array, template, items, lines
  ../../../../../poe1/data/stat_translations.json       the export's translations and trade ids

Outputs (data/, regenerable; the first line names this script and its inputs):
  template-vs-translation.csv   one row per census template of a translated array: the match kind,
                                the entries matched, their stat ids, the trade ids they carry

Printed: coverage by templates and by lines for the head (the templates covering 90 % of explicit
lines) and the tail, and the ambiguity counts.
"""

import collections
import csv
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))
POE1 = os.path.join(CLONES, "poe1")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
CENSUS = os.path.join(SEARCH, "item-facts", "data", "mod-templates.csv")
DATA = os.path.join(TRACK, "data")
HEADER = "# generated by scripts/template-vs-translation.py from ../item-facts/data/mod-templates.csv and poe1/data/stat_translations.json @ e2bd511a"
ARRAYS = ("explicitMods", "implicitMods", "enchantMods", "utilityMods", "scourgeMods", "crucibleMods", "veiledMods", "runeMods", "bondedMods")
HEAD_SHARE = 0.90

MARKUP = re.compile(r"\[([^\[\]|]*)\|([^\[\]]*)\]")
PLACEHOLDER = re.compile(r"\{\d+(?::[^}]*)?\}")


def canon(text):
    t = MARKUP.sub(lambda m: m.group(2), text)
    t = PLACEHOLDER.sub("#", t)
    t = re.sub(r"[+-]#", "#", t)
    return t.strip()


EQUIPMENT = {"Normal", "Magic", "Rare", "Unique", "Foil", "SupporterFoil"}
ITEM_FACTS_SCRIPTS = os.path.join(SEARCH, "item-facts", "scripts")


def frame_split():
    """(array, template) -> Counter(frameTypeId) of lines, by the census's own template rule over the raw stores
    (local only; empty when the stores are absent). Deduped by id, the newer fetch winning, as the census does."""
    try:
        sys.path.insert(0, ITEM_FACTS_SCRIPTS)
        import census  # noqa: the item-facts census, imported for `template`, `spike_records`, `cpp_records`
    except Exception as e:  # pragma: no cover
        print("frame split skipped:", e); return {}
    if not (os.path.exists(census.os.path.join(census.RAW, census.SPIKE)) and os.path.exists(census.os.path.join(census.RAW, census.CPP))):
        print("frame split skipped: raw stores absent"); return {}
    best = {}
    for rec in list(census.spike_records()) + list(census.cpp_records()):
        cur = best.get(rec.id)
        if cur is None or (rec.fetched or 0) > (cur.fetched or 0):
            best[rec.id] = rec
    out = collections.defaultdict(collections.Counter)
    for rec in best.values():
        fr = rec.json.get("frameTypeId", "?")
        for arr in ARRAYS:
            for line in rec.json.get(arr) or []:
                text = line.get("description", "") if isinstance(line, dict) else (line if isinstance(line, str) else "")
                out[(arr, census.template(text))][fr] += 1
    return out


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def main():
    pinned(POE1, POE1_COMMIT)
    entries = json.load(open(os.path.join(POE1, "data", "stat_translations.json")))
    by_canon = collections.defaultdict(set)    # canonical whole string -> entry indexes
    by_line = collections.defaultdict(set)     # canonical line of a multi-line string -> entry indexes
    for n, e in enumerate(entries):
        for s in e["English"]:
            c = canon(s["string"])
            by_canon[c].add(n)
            if "\n" in c:
                for ln in c.split("\n"):
                    by_line[ln.strip()].add(n)

    rows = [r for r in csv.DictReader(l for l in open(CENSUS) if not l.startswith("#")) if r["array"] in ARRAYS]
    out = []
    for r in rows:
        tpl = r["template"].replace("\\n", "\n")
        c = canon(tpl)
        hit = by_canon.get(c)
        kind = "exact" if hit else ""
        if not hit and "\n" in c:
            parts = [by_canon.get(ln.strip()) or by_line.get(ln.strip()) for ln in c.split("\n")]
            if all(parts):
                hit = set().union(*parts); kind = "lines"
        if not hit:
            # a single line of the census that is one line of a multi-line translation
            hit = by_line.get(c)
            kind = "line-of" if hit else "none"
        ents = sorted(hit or ())
        ids = ["|".join(entries[n]["ids"]) for n in ents]
        tids = sorted({ts["id"] for n in ents for ts in (entries[n].get("trade_stats") or [])})
        out.append({"array": r["array"], "template": r["template"], "items": int(r["items"]), "lines": int(r["lines"]),
                    "match": kind, "n_entries": len(ents), "entry_ids": ";".join(ids[:6]), "n_trade_ids": len(tids),
                    "trade_ids": " ".join(tids[:8]), "has_trade_ids": "yes" if tids else ""})

    frames = frame_split()
    for r in out:
        fr = frames.get((r["array"], r["template"].replace("\\n", "\n")), {})
        r["equipment_lines"] = sum(v for k, v in fr.items() if k in EQUIPMENT)
        r["gem_lines"] = fr.get("Gem", 0)
        r["other_lines"] = sum(v for k, v in fr.items() if k not in EQUIPMENT and k != "Gem")

    os.makedirs(DATA, exist_ok=True)
    with open(os.path.join(DATA, "template-vs-translation.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.DictWriter(f, fieldnames=list(out[0].keys()), lineterminator="\n")
        w.writeheader(); w.writerows(out)

    def report(label, rs):
        n = len(rs); lines = sum(r["lines"] for r in rs)
        if not n:
            return
        by_kind = collections.Counter(r["match"] for r in rs)
        lines_kind = collections.Counter()
        for r in rs: lines_kind[r["match"]] += r["lines"]
        uniq = sum(1 for r in rs if r["n_entries"] == 1); uniq_l = sum(r["lines"] for r in rs if r["n_entries"] == 1)
        amb = sum(1 for r in rs if r["n_entries"] > 1); amb_l = sum(r["lines"] for r in rs if r["n_entries"] > 1)
        traded = sum(r["lines"] for r in rs if r["has_trade_ids"])
        print(f"{label:34} templates {n:5}  lines {lines:7} | matched {n - by_kind['none']:5} ({100 * (n - by_kind['none']) / n:5.1f} %) "
              f"lines {lines - lines_kind['none']:7} ({100 * (lines - lines_kind['none']) / lines:5.1f} %) | one entry {uniq:5} / {uniq_l:7} lines; "
              f"several {amb:4} / {amb_l:6} lines | with trade ids {traded:7} lines | kinds {dict(by_kind)}")

    if frames:
        eq = [dict(r, lines=r["equipment_lines"]) for r in out if r["array"] == "explicitMods" and r["equipment_lines"]]
        eq.sort(key=lambda r: -r["lines"]); total = sum(r["lines"] for r in eq); acc = 0; head = []
        for r in eq:
            if acc >= HEAD_SHARE * total: break
            head.append(r); acc += r["lines"]
        report(f"explicit, equipment frames, head ({len(head)})", head); report("explicit, equipment frames, tail", eq[len(head):]); report("explicit, equipment frames", eq)
        report("explicit, gem frames", [dict(r, lines=r["gem_lines"]) for r in out if r["array"] == "explicitMods" and r["gem_lines"]])
        report("explicit, other frames", [dict(r, lines=r["other_lines"]) for r in out if r["array"] == "explicitMods" and r["other_lines"]])
        report("implicit, equipment frames", [dict(r, lines=r["equipment_lines"]) for r in out if r["array"] == "implicitMods" and r["equipment_lines"]])
        print("largest unmatched explicit templates on equipment frames:")
        for r in sorted((r for r in eq if r["match"] == "none"), key=lambda r: -r["lines"])[:20]:
            print(f"  {r['lines']:6}  {r['template'][:110]}")
    for arr in ARRAYS:
        rs = [r for r in out if r["array"] == arr]
        if not rs:
            continue
        if arr == "explicitMods":
            rs.sort(key=lambda r: -r["lines"]); total = sum(r["lines"] for r in rs); acc = 0; head = []
            for r in rs:
                if acc >= HEAD_SHARE * total: break
                head.append(r); acc += r["lines"]
            report(f"{arr} head ({len(head)})", head); report(f"{arr} tail", rs[len(head):])
        report(arr, rs)
    unmatched = sorted((r for r in out if r["match"] == "none" and r["array"] == "explicitMods"), key=lambda r: -r["lines"])
    print("largest unmatched explicit templates:")
    for r in unmatched[:25]:
        print(f"  {r['lines']:6}  {r['template'][:110]}")
    amb = sorted((r for r in out if r["n_entries"] > 1 and r["array"] == "explicitMods"), key=lambda r: -r["lines"])
    print("largest ambiguous explicit templates:")
    for r in amb[:15]:
        print(f"  {r['lines']:6}  {r['n_entries']}  {r['template'][:70]}  ->  {r['entry_ids'][:120]}")


if __name__ == "__main__":
    main()
