#!/usr/bin/env python3
"""repoe step 1: the export's trade_stats join against the trade site's stats capture.

Inputs (read-only; the clone must sit at the manifest's commit or this refuses to run):
  ../../../../../poe1/data/stat_translations.json   RePoE's PoE1 export at POE1_COMMIT: per translation
                                                     entry, `ids` (stat ids), `English` strings and the
                                                     `trade_stats` its generator joined by rendered text
  ../trade-query/data/stats-2026-09-12.json          the trade site's stats vocabulary, the owner's capture

Outputs (data/, regenerable; the first line names this script and its inputs):
  trade-stat-map.csv   one row per (trade id, translation entry) pair the export carries: category, stat key,
                       the trade text, the entry's stat ids and English string, whether the capture knows the id
                       and whether its text agrees
  trade-stat-coverage.csv   per trade category: capture entries and keys, how many the export carries, how many
                       it carries that the capture lacks, uncovered entries by stat-key kind

Printed: the coverage tables and the counts the README's findings quote.
"""

import collections
import csv
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
SEARCH = os.path.dirname(TRACK)
CLONES = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SEARCH))))  # siblings of acquisition/
POE1 = os.path.join(CLONES, "poe1")
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # MANIFEST.md
TRANSLATIONS = os.path.join(POE1, "data", "stat_translations.json")
CAPTURE = os.path.join(SEARCH, "trade-query", "data", "stats-2026-09-12.json")
DATA = os.path.join(TRACK, "data")
HEADER = "# generated by scripts/trade-stat-map.py from poe1/data/stat_translations.json @ e2bd511a and ../trade-query/data/stats-2026-09-12.json"


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the manifest's {commit}: add a manifest row before re-running")


def kind(stat_key):
    # the capture's key kinds as trade-query counted them: stat_N, indexable_*, pseudo_*, lake_*, ...
    return stat_key.split("_")[0] if "_" in stat_key else stat_key


def main():
    pinned(POE1, POE1_COMMIT)
    os.makedirs(DATA, exist_ok=True)
    entries = json.load(open(TRANSLATIONS))
    cats = json.load(open(CAPTURE))["result"]

    capture = {}  # trade id -> (category, entry); the site lists 229 ids twice with a second text (a rename kept)
    texts = collections.defaultdict(set)
    dup = 0
    for c in cats:
        for e in c["entries"]:
            if e["id"] in capture:
                dup += 1
            capture[e["id"]] = (c["id"], e)
            texts[e["id"]].add(e["text"])

    # export side: trade id -> the translation entries carrying it
    carried = collections.defaultdict(list)
    for n, t in enumerate(entries):
        for ts in t.get("trade_stats") or []:
            carried[ts["id"]].append((n, ts))

    rows = 0
    with open(os.path.join(DATA, "trade-stat-map.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["trade_id", "category", "stat_key", "trade_text", "option", "entry", "n_entries", "repoe_ids",
                    "english", "hidden", "in_capture", "capture_text_equal"])
        for tid in sorted(carried):
            for n, ts in carried[tid]:
                t = entries[n]
                cat, key = tid.split(".", 1)
                cap = capture.get(tid)
                english = t["English"][0]["string"] if t.get("English") else ""
                w.writerow([tid, cat, key, ts["text"], ts.get("option") or "", n, len(carried[tid]),
                            "|".join(t["ids"]), english.replace("\n", "\\n"), "yes" if t.get("hidden") else "",
                            "yes" if cap else "no", ("yes" if ts["text"] in texts[tid] else "no") if cap else ""])
                rows += 1

    # coverage per category
    print(f"export: {len(entries)} translation entries, {sum(1 for t in entries if t.get('trade_stats'))} with trade_stats, "
          f"{len(carried)} distinct trade ids, {rows} (id, entry) rows")
    print(f"capture: {sum(len(c['entries']) for c in cats)} entries, {len(capture)} distinct ids, {dup} entries repeating an id with another text")
    unknown = sorted(set(carried) - set(capture))
    print(f"export ids the capture does not know: {len(unknown)}", unknown[:20])

    keys_cap = collections.defaultdict(set)   # stat key -> categories in the capture
    keys_cov = collections.defaultdict(set)   # stat key -> categories the export covers
    for tid in capture:
        c, k = tid.split(".", 1); keys_cap[k].add(c)
    for tid in carried:
        c, k = tid.split(".", 1); keys_cov[k].add(c)

    with open(os.path.join(DATA, "trade-stat-coverage.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["category", "capture_entries", "covered", "covered_pct", "export_only", "text_differs",
                    "uncovered_by_kind"])
        tot_e = tot_c = 0
        for c in cats:
            ids = [e["id"] for e in c["entries"]]
            cov = [i for i in ids if i in carried]
            diff = sum(1 for i in cov if carried[i][0][1]["text"] not in texts[i])
            unc = collections.Counter(kind(i.split(".", 1)[1]) for i in ids if i not in carried)
            only = sum(1 for i in carried if i.split(".", 1)[0] == c["id"] and i not in capture)
            pct = f"{100 * len(cov) / len(ids):.1f}" if ids else ""
            w.writerow([c["id"], len(ids), len(cov), pct, only, diff, " ".join(f"{k}:{v}" for k, v in sorted(unc.items()))])
            print(f"  {c['id']:10} {len(ids):6} entries, {len(cov):6} covered ({pct:>5} %), {only} export-only, {diff} text differs; uncovered by kind: {dict(sorted(unc.items()))}")
            tot_e += len(ids); tot_c += len(cov)
        print(f"total: {tot_c} of {tot_e} capture entries covered ({100 * tot_c / tot_e:.1f} %)")

    # by stat key: a key covered in any category is a key the export can name
    cov_keys = [k for k in keys_cap if k in keys_cov]
    print(f"capture stat keys: {len(keys_cap)}; keys the export carries in at least one category: {len(cov_keys)} ({100 * len(cov_keys) / len(keys_cap):.1f} %)")
    unc_kind = collections.Counter(kind(k) for k in keys_cap if k not in keys_cov)
    print("uncovered keys by kind:", dict(sorted(unc_kind.items())))
    # keys of kind stat_ in categories that carry only stat_ keys
    stat_cap = [k for k in keys_cap if kind(k) == "stat"]
    stat_cov = [k for k in stat_cap if k in keys_cov]
    print(f"stat_N keys: {len(stat_cap)} in the capture, {len(stat_cov)} carried ({100 * len(stat_cov) / len(stat_cap):.1f} %)")

    # how many entries carry one trade id under several categories; ids carried by several entries
    multi = collections.Counter(len(v) for v in carried.values())
    print("trade ids by number of translation entries carrying them:", dict(sorted(multi.items())))
    n_ids = collections.Counter(len(t["ids"]) for t in entries if t.get("trade_stats"))
    print("entries with trade_stats by number of stat ids:", dict(sorted(n_ids.items())))
    hidden = sum(1 for t in entries if t.get("hidden") and t.get("trade_stats"))
    print("hidden entries with trade_stats:", hidden)


if __name__ == "__main__":
    main()
