#!/usr/bin/env python3
"""item-facts census: the item as GGG gives it, over every item the two stores hold.

Inputs (all read-only):
  raw/spike-GERWARIC_7694-2026-09-13.db   the spike's facts store (facts v7): `items` verbatim minus socketedItems
  raw/cpp-userstore-GERWARIC_7694-2026-09-13.db   the C++ app's store: one body per tab / character, items inline
  ../trade-query/data/items-2026-09-12.json       the trade site's base-type taxonomy (22 categories)

Outputs (data/, regenerable; the first line of each names this script and its inputs):
  field-census.csv       one row per JSON path: value types, items carrying it, share, by frameTypeId, example
  mod-templates.csv      one row per (mod array, display template): items, lines, line kind, flags, example
  properties-census.csv  one row per (property array, name, type, displayMode, value template): items, example
  class-evidence.csv     one row per (frameTypeId, icon directory, trade category): what could yield an item class
  numbers.md             the numbers table, pasted into the track README

Both stores hold the same account. Items are keyed by GGG id; when both stores hold an id the
newer fetch wins (the spike's `last_seen`, the C++ store's `json_fetched_at`).
"""

import base64
import collections
import csv
import datetime as dt
import json
import os
import re
import sqlite3
import statistics
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
RAW = os.path.join(TRACK, "raw")
DATA = os.path.join(TRACK, "data")
SPIKE = "spike-GERWARIC_7694-2026-09-13.db"
CPP = "cpp-userstore-GERWARIC_7694-2026-09-13.db"
TRADE_ITEMS = os.path.join(TRACK, "..", "trade-query", "data", "items-2026-09-12.json")
DOC_FIELDS = os.path.join(TRACK, "data", "api-reference-item-fields-2026-09-13.txt")
HEADER = f"# generated by scripts/census.py from raw/{SPIKE}, raw/{CPP}, ../trade-query/data/items-2026-09-12.json"

NUM = re.compile(r"(?<![\d#])[-+]?\d+(?:\.\d+)?")  # a sign after a digit is a range dash: `59-88` → `#-#`


def template(text):
    """Display line with every number replaced by `#`, newlines escaped."""
    return NUM.sub("#", text).replace("\n", "\\n")


def is_item(v):
    return isinstance(v, dict) and "typeLine" in v


def item_arrays(body):
    """Top-level keys of a body whose value is an array of item-shaped objects (the store's rule)."""
    return [k for k, v in body.items() if isinstance(v, list) and v and all(is_item(e) for e in v)]


class Rec:
    __slots__ = ("id", "source", "realm", "league", "kind", "loc", "tab_type", "container", "socketed_in", "fetched", "json", "nbytes")

    def __init__(self, **kw):
        for k in self.__slots__:
            setattr(self, k, kw.get(k))


def iso_to_epoch(s):
    return int(dt.datetime.fromisoformat(s).timestamp())


def spike_records():
    db = sqlite3.connect(f"file:{os.path.join(RAW, SPIKE)}?mode=ro", uri=True)
    q = """SELECT i.id, i.realm, i.league, i.location_kind, i.location_id, i.container, i.socketed_in, i.last_seen, i.json, t.type
           FROM items i LEFT JOIN tabs t ON t.realm = i.realm AND t.league = i.league AND t.id = i.location_id AND i.location_kind = 'stash'
           WHERE i.removed_at IS NULL"""
    for row in db.execute(q):
        yield Rec(id=row[0], source="spike", realm=row[1], league=row[2], kind=row[3], loc=row[4], container=row[5],
                  socketed_in=row[6], fetched=row[7], json=json.loads(row[8]), nbytes=len(row[8].encode()), tab_type=row[9])
    counts = {
        "tabs": db.execute("SELECT realm, league, count(*), sum(fetched_at IS NOT NULL) FROM tabs WHERE removed_at IS NULL GROUP BY 1, 2").fetchall(),
        "characters": db.execute("SELECT realm, league, count(*), sum(fetched_at IS NOT NULL) FROM characters WHERE removed_at IS NULL GROUP BY 1, 2").fetchall(),
    }
    spike_records.counts = counts


def lift(body, source, realm, league, kind, loc, tab_type, fetched):
    """Every item-shaped array in a body, socketed gems as their own records (the spike's seam, C29)."""
    for container in item_arrays(body):
        for it in body[container]:
            gems = it.pop("socketedItems", None)
            raw = json.dumps(it, separators=(",", ":"), ensure_ascii=False)
            yield Rec(id=it.get("id"), source=source, realm=realm, league=league, kind=kind, loc=loc, tab_type=tab_type,
                      container=container, socketed_in=None, fetched=fetched, json=it, nbytes=len(raw.encode()))
            for g in gems or []:
                if "id" not in g:  # PoE2 granted skill (C57): a property of its host, never a row
                    continue
                graw = json.dumps(g, separators=(",", ":"), ensure_ascii=False)
                yield Rec(id=g["id"], source=source, realm=realm, league=league, kind=kind, loc=loc, tab_type=tab_type,
                          container=container, socketed_in=it.get("id"), fetched=fetched, json=g, nbytes=len(graw.encode()))


def cpp_records():
    db = sqlite3.connect(f"file:{os.path.join(RAW, CPP)}?mode=ro", uri=True)
    for sid, realm, league, ttype, fetched_at, body in db.execute(
            "SELECT id, realm, league, type, json_fetched_at, json_data FROM stashes WHERE json_data IS NOT NULL"):
        yield from lift(json.loads(body), "cpp", realm, league, "stash", sid, ttype, iso_to_epoch(fetched_at))
    for cid, realm, league, fetched_at, body in db.execute(
            "SELECT id, realm, league, json_fetched_at, json_data FROM characters WHERE json_data IS NOT NULL"):
        yield from lift(json.loads(body), "cpp", realm, league, "character", cid, None, iso_to_epoch(fetched_at))
    cpp_records.counts = {
        "tabs": db.execute("SELECT realm, league, count(*), sum(json_data IS NOT NULL) FROM stashes GROUP BY 1, 2").fetchall(),
        "characters": db.execute("SELECT realm, league, count(*), sum(json_data IS NOT NULL) FROM characters GROUP BY 1, 2").fetchall(),
    }


def walk(v, path, seen, types, examples, frame):
    """Record every path this value carries, once per item. `a[]` is an element of array `a`;
    a dict keyed by numbers (crucible nodes) is walked as `{n}`."""
    if isinstance(v, dict):
        for k, x in v.items():
            k = "{n}" if k.isdigit() else k
            p = f"{path}.{k}" if path else k
            if p == "socketedItems":
                continue
            walk(x, p, seen, types, examples, frame)
        if not path:
            return
    elif isinstance(v, list):
        for x in v:
            walk(x, path + "[]", seen, types, examples, frame)
    if path not in seen:
        seen.add(path)
        t = {dict: "object", list: "array", str: "string", bool: "bool", int: "int", float: "float", type(None): "null"}[type(v)]
        types[path][t] += 1
        frame[path][FRAME] += 1
        if path not in examples and v not in (None, "", [], {}):
            ex = v if isinstance(v, str) else json.dumps(v, ensure_ascii=False)
            examples[path] = ex.replace("\n", "\\n")[:80].rstrip()


def icon_dir(url):
    """The art path inside a poecdn icon URL: `2DItems/Armours/Boots/...` → `Armours/Boots`."""
    f = None
    if "/gen/image/" in url:
        token = url.split("/gen/image/")[1].split("/")[0]
        token += "=" * (-len(token) % 4)
        try:
            spec = json.loads(base64.urlsafe_b64decode(token))
            for part in spec:
                if isinstance(part, dict) and "f" in part:
                    f = part["f"]
        except Exception:
            return "?"
    elif "/image/Art/" in url:
        f = url.split("/image/Art/")[1]
    if not f:
        return "?"
    segs = f.split("/")
    if segs and segs[0] == "2DItems":
        segs = segs[1:]
    return "/".join(segs[:2])


def main():
    os.makedirs(DATA, exist_ok=True)
    trade = json.load(open(TRADE_ITEMS))["result"]
    cat_by_type = collections.defaultdict(set)
    for g in trade:
        for e in g["entries"]:
            cat_by_type[e["type"]].add(g["id"])

    # ---- gather, dedupe by id, newest fetch wins
    by_id = {}
    per_source = collections.Counter()
    line_kind_by_date = collections.Counter()  # (source, month, kind) for explicitMods elements
    overlap = collections.Counter()
    for rec in list(spike_records()) + list(cpp_records()):
        per_source[(rec.source, rec.realm, rec.league, rec.kind)] += 1
        em = rec.json.get("explicitMods")
        if em:
            kind = "object" if isinstance(em[0], dict) else "string"
            line_kind_by_date[(rec.source, dt.datetime.fromtimestamp(rec.fetched, dt.UTC).strftime("%Y-%m-%d"), kind)] += 1
        old = by_id.get(rec.id)
        if old is None:
            by_id[rec.id] = rec
        else:
            overlap[(old.league, rec.league)] += 1
            if rec.fetched > old.fetched:
                by_id[rec.id] = rec
    items = list(by_id.values())
    n = len(items)

    # ---- field census
    global FRAME
    types = collections.defaultdict(collections.Counter)
    frame = collections.defaultdict(collections.Counter)
    examples = {}
    for it in items:
        FRAME = it.json.get("frameTypeId", "?")
        walk(it.json, "", set(), types, examples, frame)
    with open(os.path.join(DATA, "field-census.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["path", "items", "share", "types", "by_frame_type", "example"])
        for p in sorted(types, key=lambda p: (-sum(types[p].values()), p)):
            cnt = sum(types[p].values())
            w.writerow([p, cnt, f"{cnt / n:.3f}", ";".join(f"{t}:{c}" for t, c in types[p].most_common()),
                        ";".join(f"{t}:{c}" for t, c in frame[p].most_common()), examples.get(p, "")])

    # ---- mod templates
    mods = collections.defaultdict(lambda: collections.defaultdict(lambda: {"items": 0, "lines": 0, "kinds": collections.Counter(), "flags": collections.Counter(), "example": None}))
    lines_per_item = collections.defaultdict(list)
    for it in items:
        for k, v in it.json.items():
            if not k.endswith("Mods") or not isinstance(v, list):
                continue
            lines_per_item[k].append(len(v))
            seen = set()
            for line in v:
                if isinstance(line, dict):
                    # ItemMod carries `description`; an ultimatumMods element carries `type` and `tier`
                    text, kind, flags = line.get("description", line.get("type", "")), "object", line.get("flags") or {}
                else:
                    text, kind, flags = str(line), "string", {}
                tpl = template(text)
                row = mods[k][tpl]
                row["lines"] += 1
                row["kinds"][kind] += 1
                for fk, fv in flags.items():
                    row["flags"][f"{fk}={fv}"] += 1
                if row["example"] is None:
                    row["example"] = text.replace("\n", "\\n")[:100].rstrip()
                if tpl not in seen:
                    seen.add(tpl)
                    row["items"] += 1
    with open(os.path.join(DATA, "mod-templates.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["array", "template", "items", "lines", "kinds", "flags", "example"])
        for k in sorted(mods, key=lambda k: -sum(r["lines"] for r in mods[k].values())):
            for tpl, row in sorted(mods[k].items(), key=lambda kv: (-kv[1]["items"], kv[0])):
                w.writerow([k, tpl, row["items"], row["lines"], ";".join(f"{a}:{b}" for a, b in row["kinds"].most_common()),
                            ";".join(f"{a}:{b}" for a, b in row["flags"].most_common()), row["example"]])

    # ---- the C++ app's view of the mod arrays (cpp-search Q2, Q3): one mod table per item keyed by the app's own
    # template (`[0-9.]+` -> `#`, sign kept; a `1 Added Passive Skill` line verbatim), last assignment wins, so a
    # repeated numbered template loses a line; and items whose only mod lines sit in an array the app never reads
    CPP_READ = {"enchantMods", "implicitMods", "explicitMods"}
    cpp_tpl = lambda t: t if t.startswith("1 Added Passive Skill") else re.sub(r"[0-9.]+", "#", t)
    cpp_dup_items = cpp_dup_lines = cpp_ignored_any = cpp_ignored_only = 0
    cpp_dup_by = collections.Counter()
    for it in items:
        table = collections.Counter()
        read_lines = ignored_lines = 0
        for k, v in it.json.items():
            if not k.endswith("Mods") or not isinstance(v, list):
                continue
            if k not in CPP_READ:
                ignored_lines += len(v)
                continue
            for line in v:
                text = line.get("description", "") if isinstance(line, dict) else str(line)
                flags = (line.get("flags") or {}) if isinstance(line, dict) else {}
                if flags.get("desecrated") or flags.get("vestigial"):
                    continue
                read_lines += 1
                tpl = cpp_tpl(text)
                if "#" in tpl:  # a line without a number never enters the table
                    table[tpl] += 1
        hybrid = (it.json.get("hybrid") or {}).get("explicitMods")
        if isinstance(hybrid, list):
            ignored_lines += len(hybrid)
        lost = sum(c - 1 for c in table.values() if c > 1)
        if lost:
            cpp_dup_items += 1
            cpp_dup_lines += lost
            for tpl, c in table.items():
                if c > 1:
                    cpp_dup_by[tpl] += c - 1
        if ignored_lines:
            cpp_ignored_any += 1
            if not read_lines:
                cpp_ignored_only += 1

    # ---- properties census
    PROP_ARRAYS = ["properties", "additionalProperties", "requirements", "nextLevelRequirements", "weaponRequirements",
                   "supportGemRequirements", "notableProperties", "hybrid.properties"]
    props = collections.defaultdict(lambda: {"items": 0, "example": None})
    for it in items:
        seen = set()
        for arr in PROP_ARRAYS:
            v = it.json
            for seg in arr.split("."):
                v = v.get(seg) if isinstance(v, dict) else None
            if not isinstance(v, list):
                continue
            for p in v:
                if not isinstance(p, dict):
                    continue
                vals = p.get("values") or []
                vt = "|".join(template(str(x[0])) if isinstance(x, list) and x else "?" for x in vals)
                key = (arr, template(p.get("name", "")), p.get("type", ""), p.get("displayMode", ""), vt, len(vals))
                if key in seen:
                    continue
                seen.add(key)
                props[key]["items"] += 1
                if props[key]["example"] is None:
                    props[key]["example"] = json.dumps(p, ensure_ascii=False)[:120]
    with open(os.path.join(DATA, "properties-census.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["array", "name", "type", "displayMode", "value_templates", "n_values", "items", "example"])
        for key, row in sorted(props.items(), key=lambda kv: (kv[0][0], -kv[1]["items"], kv[0][1])):
            w.writerow([*key, row["items"], row["example"]])

    # ---- class evidence
    cls = collections.defaultdict(lambda: {"items": 0, "example": None})
    matched = collections.Counter()
    for it in items:
        j = it.json
        ft = j.get("frameTypeId", "?")
        idir = icon_dir(j.get("icon", ""))
        cats = cat_by_type.get(j.get("baseType", ""), set())
        cat = "|".join(sorted(cats)) if cats else "-"
        matched[(ft, bool(cats))] += 1
        key = (ft, idir, cat)
        cls[key]["items"] += 1
        if cls[key]["example"] is None:
            cls[key]["example"] = f'{j.get("name") or ""} / {j.get("typeLine")}'
    with open(os.path.join(DATA, "class-evidence.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["frameTypeId", "icon_dir", "trade_category_by_baseType", "items", "example"])
        for key, row in sorted(cls.items(), key=lambda kv: (kv[0][0], -kv[1]["items"], kv[0][1])):
            w.writerow([*key, row["items"], row["example"]])

    # ---- numbers
    sizes = [it.nbytes for it in items]
    sizes.sort()
    out = [f"<!-- {HEADER[2:]} -->", "", "| | |", "| --- | --- |"]
    out.append(f"| Items (distinct ids, both stores) | {n:,} |")
    out.append(f"| Item JSON bytes: total / mean / p50 / p95 / max | {sum(sizes):,} / {statistics.mean(sizes):,.0f} / {sizes[n // 2]:,} / {sizes[int(n * 0.95)]:,} / {sizes[-1]:,} |")
    out.append(f"| Store files: spike / C++ (bytes) | {os.path.getsize(os.path.join(RAW, SPIKE)):,} / {os.path.getsize(os.path.join(RAW, CPP)):,} |")
    out.append(f"| Socketed gems (rows with a host) | {sum(1 for it in items if it.socketed_in):,} |")
    out.append(f"| Distinct JSON paths | {len(types):,} |")
    for k in sorted(mods, key=lambda k: -sum(r['lines'] for r in mods[k].values())):
        lp = lines_per_item[k]
        out.append(f"| `{k}`: items / lines / distinct templates / lines per item mean, max | {len(lp):,} / {sum(lp):,} / {len(mods[k]):,} / {statistics.mean(lp):.2f}, {max(lp)} |")
    out.append(f"| Property rows (array, name, type, mode, value shape) | {len(props):,} |")
    out.append(f"| C++ mod table (cpp-search Q2): items losing a numbered line to a repeated template / lines lost / top templates | {cpp_dup_items:,} / {cpp_dup_lines:,} / " + ", ".join(f"`{t}` {c:,}" for t, c in cpp_dup_by.most_common(3)) + " |")
    out.append(f"| C++ unread arrays (cpp-search Q3): items with a line in one / items with mod lines only there | {cpp_ignored_any:,} / {cpp_ignored_only:,} |")
    out.append(f"| baseType matched to a trade category: items / share | {sum(c for (ft, m), c in matched.items() if m):,} / {sum(c for (ft, m), c in matched.items() if m) / n:.3f} |")
    out += ["", "**Per store, before dedupe** (source, realm, league, kind → items):", "", "| Source | Realm | League | Kind | Items |", "| --- | --- | --- | --- | ---: |"]
    for (s, r, l, k), c in sorted(per_source.items()):
        out.append(f"| {s} | {r} | {l} | {k} | {c:,} |")
    out += ["", "**Containers listed / fetched** (tabs, characters):", "", "| Source | Realm | League | Tabs listed / fetched | Characters listed / fetched |", "| --- | --- | --- | --- | --- |"]
    for src, counts in (("spike", spike_records.counts), ("cpp", cpp_records.counts)):
        tabs = {(r, l): (c, f) for r, l, c, f in counts["tabs"]}
        chars = {(r, l): (c, f) for r, l, c, f in counts["characters"]}
        for key in sorted(set(tabs) | set(chars)):
            t = tabs.get(key, (0, 0))
            ch = chars.get(key, (0, 0))
            out.append(f"| {src} | {key[0]} | {key[1]} | {t[0]:,} / {t[1] or 0:,} | {ch[0]:,} / {ch[1] or 0:,} |")
    out += ["", "**Ids held by both stores** (league as each store files it → items):", ""]
    for (a, b), c in sorted(overlap.items()):
        out.append(f"- {a} / {b}: {c:,}")
    out += ["", "**`explicitMods` line kind by fetch date** (source, day, kind → items):", "", "| Source | Day | Kind | Items |", "| --- | --- | --- | ---: |"]
    for (s, d, k), c in sorted(line_kind_by_date.items()):
        out.append(f"| {s} | {d} | {k} | {c:,} |")
    out += ["", "**frameTypeId × baseType matched to the trade taxonomy:**", "", "| frameTypeId | matched | unmatched |", "| --- | ---: | ---: |"]
    for ft in sorted({ft for ft, _ in matched}):
        out.append(f"| {ft} | {matched[(ft, True)]:,} | {matched[(ft, False)]:,} |")

    # observed vs documented (the API reference's Item type, hand-extracted on the file's date)
    documented = [l.strip() for l in open(DOC_FIELDS) if l.strip() and not l.startswith("#")]
    observed = {p: sum(types[p].values()) for p in types if "." not in p and "[" not in p}
    out += ["", f"**Top-level fields against the API reference** (`{os.path.basename(DOC_FIELDS)}`): "
            f"observed {len(observed)}, documented {len(documented)}.", "",
            "- observed, undocumented: " + (", ".join(f"`{k}` ({v:,})" for k, v in sorted(observed.items(), key=lambda kv: -kv[1]) if k not in documented) or "none"),
            "- documented, unobserved: " + (", ".join(f"`{k}`" for k in documented if k not in observed) or "none")]
    sub_doc = {"influences": {"elder", "shaper", "searing", "tangled"}}
    for parent, docd in sub_doc.items():
        obs = {p.split(".", 1)[1]: sum(types[p].values()) for p in types if p.startswith(parent + ".")}
        out.append(f"- `{parent}.*` observed, undocumented: " + (", ".join(f"`{k}` ({v:,})" for k, v in obs.items() if k not in docd) or "none"))

    # `[Tag|Display]` game-text markup leaking into display strings, by realm
    markup = re.compile(r"\[[^\]]*\|[^\]]*\]")
    leak = collections.Counter()
    leak_ex = {}
    for it in items:
        for k, v in it.json.items():
            strings = []
            if k.endswith("Mods") and isinstance(v, list):
                strings = [(x.get("description", "") if isinstance(x, dict) else str(x)) for x in v]
            elif k in PROP_ARRAYS and isinstance(v, list):
                strings = [p.get("name", "") for p in v if isinstance(p, dict)]
            for s in strings:
                if markup.search(s):
                    leak[(it.realm, k)] += 1
                    leak_ex.setdefault((it.realm, k), s.replace("\n", "\\n")[:70])
    out += ["", "**`[Tag|Display]` markup in display strings** (realm, array → lines; first example):", ""]
    for (r, k), c in sorted(leak.items(), key=lambda kv: -kv[1]):
        out.append(f"- {r} `{k}`: {c:,} — `{leak_ex[(r, k)]}`")
    text = "\n".join(out) + "\n"
    open(os.path.join(DATA, "numbers.md"), "w").write(text)
    print(text)


if __name__ == "__main__":
    sys.exit(main())
