#!/usr/bin/env python3
"""item-facts Q1: where a map's area lives, read from the icon URL of every map the two stores hold.

Inputs: the two stores census.py reads (same dedupe, newest fetch wins) and the trade site's
`items.json` map group. The icon URL is `/gen/image/<base64 JSON>/<hash>/<Art>.png`; the JSON is
`[28, 14, {"f": "2DItems/Maps/Atlas2Maps/New/<Art>", "w", "h", "scale", "mn", "mt", "mg", "mi", "mc"}]`.

Output: data/map-identity.csv — one row per icon art name: items, the tiers seen, the parameter values
seen, an example. Stdout: how many art names join a trade `map` entry (art + " Map" == entry type,
spaces ignored) and the crosstabs (parameter x tier, league, influence, art kind).
"""

import base64
import collections
import csv
import json
import os
import re
import sys
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import census  # noqa: E402

MAP_BASE = re.compile(r"^Map \(Tier (\d+)\)$")
HEADER = "# generated by scripts/map-identity.py from " + census.HEADER[len("# generated by scripts/census.py from "):]


def decode_icon(url):
    path = urllib.parse.urlparse(url).path
    segs = path.split("/")
    try:
        i = segs.index("image")
        blob = segs[i + 1]
        blob += "=" * (-len(blob) % 4)
        spec = json.loads(base64.urlsafe_b64decode(blob))[2]
    except (ValueError, IndexError, KeyError):
        spec = {}
    return spec, segs[-1].removesuffix(".png")


def main():
    by_id = {}
    for rec in list(census.spike_records()) + list(census.cpp_records()):
        old = by_id.get(rec.id)
        if old is None or rec.fetched > old.fetched:
            by_id[rec.id] = rec
    maps = [r for r in by_id.values() if MAP_BASE.match(r.json.get("baseType", ""))]
    trade = json.load(open(census.TRADE_ITEMS))["result"]
    map_types = {}
    for g in trade:
        if g["id"] == "map":
            for e in g["entries"]:
                map_types[e["type"].replace(" ", "").lower()] = e
    rows = collections.defaultdict(lambda: {"items": 0, "params": collections.defaultdict(collections.Counter), "tiers": collections.Counter(), "example": None})
    cross = collections.defaultdict(collections.Counter)
    params_seen = collections.Counter()
    for r in maps:
        spec, art = decode_icon(r.json["icon"])
        tier = int(MAP_BASE.match(r.json["baseType"]).group(1))
        row = rows[art]
        row["items"] += 1
        row["tiers"][tier] += 1
        if row["example"] is None:
            row["example"] = f'{r.json.get("name") or ""} / {r.json.get("typeLine")}'
        infl = ",".join(sorted(k for k, v in (r.json.get("influences") or {}).items() if v)) or "-"
        for k in ("mn", "mt", "mg", "mi", "mc"):
            if k in spec:
                params_seen[k] += 1
                row["params"][k][spec[k]] += 1
                cross[(k, "tier")][(spec[k], tier)] += 1
                cross[(k, "league")][(spec[k], r.league)] += 1
                cross[(k, "influence")][(spec[k], infl)] += 1
                cross[(k, "art")][(spec[k], "MapNumbers" if art.startswith("MapNumbers") else "area")] += 1
            else:
                params_seen[k + " absent"] += 1
    joined = sum(1 for art in rows if (art + "map").lower() in map_types)
    joined_items = sum(row["items"] for art, row in rows.items() if (art + "map").lower() in map_types)
    numbered = sum(row["items"] for art, row in rows.items() if art.startswith("MapNumbers"))
    with open(os.path.join(census.DATA, "map-identity.csv"), "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["art", "items", "tiers", "mn", "mt", "mg", "mi", "mc", "example"])
        for art, row in sorted(rows.items(), key=lambda kv: (-kv[1]["items"], kv[0])):
            w.writerow([art, row["items"], ";".join(f"{t}:{c}" for t, c in sorted(row["tiers"].items()))]
                       + [";".join(f"{v}:{c}" for v, c in sorted(row["params"][k].items())) for k in ("mn", "mt", "mg", "mi", "mc")]
                       + [row["example"]])
    print(f"maps {len(maps):,}; distinct art {len(rows)}; art joined to a trade map type {joined} ({joined_items:,} items); "
          f"tier-number art {numbered:,} items; params {dict(params_seen)}")
    for (k, dim), c in sorted(cross.items()):
        print(f"\n{k} x {dim}:")
        for (v, d), n in sorted(c.items(), key=lambda kv: (str(kv[0][0]), str(kv[0][1]))):
            print(f"  {k}={v} {dim}={d}: {n}")


if __name__ == "__main__":
    sys.exit(main())
