#!/usr/bin/env python3
"""category, findings 3 and 4: what a captured beast is in the private API, measured over the
owner's copy — which facts of its body vary, which candidate reading sorts it into which of the
site's three leaves, and whether the game's own data gives it a base or a class.

    python3 search/category/scripts/beasts.py

A beast is an item whose descrText is the bestiary help line (common.BEAST_HELP; Awakened PoE
Trade's parser keys on the same line, Parser.ts lines 974-975).

The candidate readings, each named by where it comes from; none is a finding that the site
agrees, which nothing on this machine can say (the README, finding 3):
  apt     every beast is one category, `Captured Beast` (APT's ItemCategory.CapturedBeast,
          parser/meta.ts line 3), read here as the site id whose text it equals: monster.beast
  frame   the site's texts read as the name's colour, the colour as the frame: Rare -> Yellow
          Beast, Unique -> Red Beast, any other frame -> Captured Beast
  lure    the base begins with a word the export names a Bestiary lure for (`<word> Lure`,
          base_items.json, Metadata/Items/Scarabs/ScarabBeasts4a-d) -> Red Beast, else Yellow Beast

Inputs (read-only): the copy (sqlite mode=ro; when absent nothing is written and the run says so),
../trade-query/data/items-2026-09-12.json (the site's `monster` list), poe1/data @ e2bd511a
(base_items.json, item_classes.json, mods.json), awakened-poe-trade @ ce551eb7 (items.ndjson).

Outputs (data/): beasts.csv (one row per beast base on the copy), beast-facts.csv (one row per
body fact over the copy's beasts, `varies` yes or no, its values and counts).
"""

import collections
import sys
import json
import re

sys.dont_write_bytecode = True  # nothing is cached beside a script this track does not own
import common  # noqa: E402

HEADER = ("# generated by scripts/beasts.py from the copy ../item-facts/raw/m3 (local), ../trade-query/data/items-2026-09-12.json, "
          "poe1/data @ e2bd511a (base_items, item_classes, mods), awakened-poe-trade @ ce551eb7 (items.ndjson)")


def fmt(counter):
    return "; ".join(f"{k}:{v}" for k, v in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0]))))


def props(body):
    return {p["name"]: (p["values"][0][0] if p.get("values") else "") for p in body.get("properties") or []}


def main():
    ex = common.Export()
    coarse_by_type, _ = common.site_coarse()
    site_monster = {t for t, cs in coarse_by_type.items() if "monster" in cs}
    _, _, _, apt_beasts = common.apt()
    apt_beasts = set(apt_beasts)
    items = common.copy_items()
    if items is None:
        print("the copy is absent: beasts.csv and beast-facts.csv not written; every count is an open question")
        return
    beasts = [b for _, _, _, b in items if common.is_beast(b)]

    lures = sorted({b["name"][: -len(" Lure")] for k, b in ex.bases.items() if b["name"] and b["name"].endswith(" Lure")})
    bestiary_mods = {m["name"] for m in ex.mods.values() if m.get("generation_type") == "bestiary" and m.get("name")}
    beast_classes = sorted({c for c, v in ex.classes.items()
                            if re.search(r"(?i)beast|bestiar|monster|captured", c + " " + (v["name"] or "") + " " + (v["category"] or ""))})

    def reading_frame(b):
        f = b.get("frameTypeId")
        return "monster.yellowbeast" if f == "Rare" else "monster.redbeast" if f == "Unique" else "monster.beast"

    def reading_lure(base):
        return "monster.redbeast" if base.split(" ")[0] in lures else "monster.yellowbeast"

    per = collections.defaultdict(list)
    for b in beasts:
        per[common.shown(b["baseType"])].append(b)
    rows = []
    for base in sorted(per):
        bs = per[base]
        fr = collections.Counter(b.get("frameTypeId") for b in bs)
        ra = collections.Counter(b.get("rarity") for b in bs)
        ps = [props(b) for b in bs]
        mods = collections.Counter(m.get("description") for b in bs for m in b.get("explicitMods") or [])
        words = collections.Counter(len((b.get("name") or "").split()) for b in bs)
        rows.append([base, len(bs), fmt(fr), fmt(ra),
                     fmt(collections.Counter(p.get("Genus", "") for p in ps)),
                     fmt(collections.Counter(p.get("Group", "") for p in ps)),
                     fmt(collections.Counter(p.get("Family", "") for p in ps)),
                     f"name set on {sum(1 for b in bs if b.get('name'))}, differs from the base on "
                     f"{sum(1 for b in bs if b.get('name') and b.get('name') != base)}; words {fmt(words)}",
                     fmt(collections.Counter(b.get("descrText") for b in bs)),
                     fmt(mods), " ".join(sorted({m for m in mods if m in bestiary_mods})),
                     "yes" if base in site_monster else "no", "yes" if base in apt_beasts else "no",
                     "yes" if base in ex.by_name else "no",
                     "monster.beast", fmt(collections.Counter(reading_frame(b) for b in bs)), reading_lure(base)])
    common.write_csv("beasts.csv", HEADER,
                     ["base", "items", "frames", "rarities", "genus", "group", "family", "name_pattern", "descrText",
                      "explicit_mods", "bestiary_mods_in_export", "in_site_monster_list", "in_apt_captured_beasts",
                      "an_export_base_name", "reading_apt", "reading_frame", "reading_lure"], rows)

    # every body fact over the beasts
    facts = collections.defaultdict(collections.Counter)
    for b in beasts:
        for k, v in b.items():
            if k in ("properties", "explicitMods"):
                continue
            facts[k][json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v] += 1
        for k in set().union(*(set(x) for x in beasts)) - set(b):
            facts[k]["(absent)"] += 1
        for p in b.get("properties") or []:
            facts[f"properties[{p['name']}].value"][p["values"][0][0] if p.get("values") else ""] += 1
            facts[f"properties[{p['name']}].type"][p.get("type")] += 1
            facts[f"properties[{p['name']}].displayMode"][p.get("displayMode")] += 1
        facts["properties (names in order)"][" / ".join(p["name"] for p in b.get("properties") or [])] += 1
        facts["explicitMods (count)"][len(b.get("explicitMods") or [])] += 1
        for m in b.get("explicitMods") or []:
            facts["explicitMods[].description"][m.get("description")] += 1
            facts["explicitMods[] keys"][" ".join(sorted(m))] += 1
    frows = []
    for k in sorted(facts):
        c = facts[k]
        vals = f"{len(c)} distinct (identity; values not listed)" if k == "id" else fmt(c)
        frows.append([k, "yes" if len(c) > 1 else "no", len(c), sum(c.values()), vals])
    common.write_csv("beast-facts.csv", HEADER, ["fact", "varies", "distinct", "occurrences", "values"], frows)

    # printed
    print(f"F3 beasts on the copy: {len(beasts)} items, {len(per)} bases; in the site's monster list: "
          f"{sum(1 for b in per if b in site_monster)}; in APT's CAPTURED_BEAST: {sum(1 for b in per if b in apt_beasts)}; "
          f"an export base name: {sum(1 for b in per if b in ex.by_name)}")
    print(f"F3 the site's monster list {len(site_monster)}; APT's captured beasts {len(apt_beasts)}, of them in the site's list "
          f"{len(apt_beasts & site_monster)}; site names not in APT {len(site_monster - apt_beasts)}")
    print(f"F3 facts: {len(frows)}; varying {sum(1 for r in frows if r[1] == 'yes')}: {[r[0] for r in frows if r[1] == 'yes']}")
    print(f"F3 constant: {[(r[0], r[4]) for r in frows if r[1] == 'no']}")
    print(f"F3 lure words (export): {lures}; bestiary mods in the export: {len(bestiary_mods)}")
    rf = collections.Counter(reading_frame(b) for b in beasts)
    rl = collections.Counter(reading_lure(common.shown(b['baseType'])) for b in beasts)
    print(f"F3 readings over items: apt {{'monster.beast': {len(beasts)}}}; frame {dict(rf)}; lure {dict(rl)}")
    rlb = collections.Counter(reading_lure(b) for b in per)
    print(f"F3 lure reading over bases: {dict(rlb)}")
    # which body facts line up with the lure reading, item by item
    for fact in ("Family", "Group", "Genus"):
        tab = collections.Counter((props(b).get(fact), reading_lure(common.shown(b["baseType"]))) for b in beasts)
        split = {v for (v, r) in tab}
        mixed = sorted(v for v in split if (v, "monster.redbeast") in tab and (v, "monster.yellowbeast") in tab)
        print(f"F3 {fact} against the lure reading: {len(split)} values, {len(mixed)} hold both readings {mixed}")
    pres = collections.Counter()
    for b in beasts:
        base = common.shown(b["baseType"])
        own = any((m.get("description") or "") == f"{base.split(' ')[0]} Presence" for m in b.get("explicitMods") or [])
        any_lure = any((m.get("description") or "") in {f"{w} Presence" for w in lures} for m in b.get("explicitMods") or [])
        pres[(reading_lure(base), "own word's Presence" if own else "another lure word's Presence" if any_lure else "no lure word's Presence")] += 1
    print(f"F3 lure reading against a `<lure word> Presence` mod: {dict(sorted(pres.items()))}")
    bm = collections.Counter((reading_lure(common.shown(b["baseType"])),
                              any((m.get("description") or "") in bestiary_mods for m in b.get("explicitMods") or [])) for b in beasts)
    print(f"F3 lure reading against carrying any bestiary mod of the export: {dict(sorted(bm.items()))}")
    import glob
    import os
    named = {}
    for f in sorted(glob.glob(os.path.join(common.POE1, "data", "*.json"))):
        text = open(f, encoding="utf-8").read()
        hits = sorted(b for b in per if json.dumps(b, ensure_ascii=False) in text)
        named[os.path.basename(f)] = len(hits)
    print(f"F4 top-level poe1/data files: {len(named)}; those naming any of the copy's {len(per)} beast bases as a string: "
          f"{ {k: v for k, v in named.items() if v} or 'none'}")
    print(f"F4 export classes whose id, name or category says beast/bestiary/monster/captured: {beast_classes}; "
          f"beast bases that are export base names: {sum(1 for b in per if b in ex.by_name)} of {len(per)}")


if __name__ == "__main__":
    main()
