#!/usr/bin/env python3
"""category, findings 3 and 4: what a captured beast is in the private API, measured over the
owner's copy — which facts of its body vary, which candidate reading sorts it into which of the
site's three leaves, and whether the game's own data gives it a base or a class.

    python3 search/category/scripts/beasts.py

A beast is an item whose descrText is the bestiary help line (common.BEAST_HELP; Awakened PoE
Trade's parser keys on the same line, Parser.ts lines 974-975).

The candidate readings, each named by where it comes from; none is a finding that the site
agrees, which nothing on this machine can say (the README, finding 3):
  apt     every beast is one category, `Captured Beast` (APT's ItemCategory.CapturedBeast,
          parser/meta.ts line 3), read here as the site id whose text it equals: monster.beast
  frame   the site's texts read as the name's colour, the colour as the frame: Rare -> Yellow
          Beast, Unique -> Red Beast, any other frame -> Captured Beast
  lure    the base begins with a word the export names a Bestiary lure for (`<word> Lure`,
          base_items.json, Metadata/Items/Scarabs/ScarabBeasts4a-d) -> Red Beast, else Yellow Beast
  mods    the wiki's account (poewiki.net, Beast_(Bestiary)), read and quoted by the owner 2026-10-01
          (search/category/BRIEF.md at 2e712e60; MANIFEST.md): "Yellow Beasts have one Bestiary mod
          ... Red Beasts have two Bestiary mods". The body's explicitMods whose text is the name of
          one of the export's bestiary mods are counted: 1 -> Yellow Beast, 2 -> Red Beast; 0 or more
          than 2 is a count the account names no colour for -> `none` (the run prints how many)

The wiki's named red beasts are looked for by what the quote says of them, never by a name
recalled: "The Black Mórrigan" (the site's list spells it without "The"); the four Spirit
Beasts, whose names the quote does not give, by the quote's "an avatar of the First Ones": the
site's names holding ", First of the " (a candidate match, the owner's to confirm); the Harvest
beasts, whose names no input on this machine gives, are not looked for.

Inputs (read-only): the copy (sqlite mode=ro; when absent nothing is written and the run says so),
../trade-query/data/items-2026-09-12.json (the site's `monster` list), poe1/data @ e2bd511a
(base_items.json, item_classes.json, mods.json), awakened-poe-trade @ ce551eb7 (items.ndjson).

Outputs (data/): beasts.csv (one row per beast base on the copy), beast-facts.csv (one row per
body fact over the copy's beasts, `varies` yes or no, its values and counts).
"""

import collections
import sys
import json
import re

sys.dont_write_bytecode = True  # nothing is cached beside a script this track does not own
import common  # noqa: E402

HEADER = ("# generated by scripts/beasts.py from the copy ../item-facts/raw/m3 (local), ../trade-query/data/items-2026-09-12.json, "
          "poe1/data @ e2bd511a (base_items, item_classes, mods), awakened-poe-trade @ ce551eb7 (items.ndjson)")


# Round j's two beasts (tools/trade-sheet.py, round_j, j01-j06): one red and one yellow under both the
# lure and the mods readings, chosen in the first run (README, open question 1); the run prints that
# both readings still place them so.
ROUND_J_BEASTS = ["Farric Ursa", "Dune Hellion"]


def fmt(counter):
    return "; ".join(f"{k}:{v}" for k, v in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0]))))


def props(body):
    return {p["name"]: (p["values"][0][0] if p.get("values") else "") for p in body.get("properties") or []}


def main():
    ex = common.Export()
    coarse_by_type, _ = common.site_coarse()
    site_monster = {t for t, cs in coarse_by_type.items() if "monster" in cs}
    _, _, _, apt_beasts = common.apt()
    apt_beasts = set(apt_beasts)
    items = common.copy_items()
    if items is None:
        print("the copy is absent: beasts.csv and beast-facts.csv not written; every count is an open question")
        return
    beasts = [b for _, _, _, b in items if common.is_beast(b)]

    lures = sorted({b["name"][: -len(" Lure")] for k, b in ex.bases.items() if b["name"] and b["name"].endswith(" Lure")})
    bestiary_mods = {m["name"] for m in ex.mods.values() if m.get("generation_type") == "bestiary" and m.get("name")}
    beast_classes = sorted({c for c, v in ex.classes.items()
                            if re.search(r"(?i)beast|bestiar|monster|captured", c + " " + (v["name"] or "") + " " + (v["category"] or ""))})

    def reading_frame(b):
        f = b.get("frameTypeId")
        return "monster.yellowbeast" if f == "Rare" else "monster.redbeast" if f == "Unique" else "monster.beast"

    def reading_lure(base):
        return "monster.redbeast" if base.split(" ")[0] in lures else "monster.yellowbeast"

    def bestiary_count(b):
        return sum(1 for m in b.get("explicitMods") or [] if (m.get("description") or "") in bestiary_mods)

    def reading_mods(b):
        return {1: "monster.yellowbeast", 2: "monster.redbeast"}.get(bestiary_count(b), "none")

    per = collections.defaultdict(list)
    for b in beasts:
        per[common.shown(b["baseType"])].append(b)
    rows = []
    for base in sorted(per):
        bs = per[base]
        fr = collections.Counter(b.get("frameTypeId") for b in bs)
        ra = collections.Counter(b.get("rarity") for b in bs)
        ps = [props(b) for b in bs]
        mods = collections.Counter(m.get("description") for b in bs for m in b.get("explicitMods") or [])
        words = collections.Counter(len((b.get("name") or "").split()) for b in bs)
        rows.append([base, len(bs), fmt(fr), fmt(ra),
                     fmt(collections.Counter(p.get("Genus", "") for p in ps)),
                     fmt(collections.Counter(p.get("Group", "") for p in ps)),
                     fmt(collections.Counter(p.get("Family", "") for p in ps)),
                     f"name set on {sum(1 for b in bs if b.get('name'))}, differs from the base on "
                     f"{sum(1 for b in bs if b.get('name') and b.get('name') != base)}; words {fmt(words)}",
                     fmt(collections.Counter(b.get("descrText") for b in bs)),
                     fmt(mods), " ".join(sorted({m for m in mods if m in bestiary_mods})),
                     "yes" if base in site_monster else "no", "yes" if base in apt_beasts else "no",
                     "yes" if base in ex.by_name else "no",
                     "monster.beast", fmt(collections.Counter(reading_frame(b) for b in bs)), reading_lure(base),
                     fmt(collections.Counter(bestiary_count(b) for b in bs)),
                     fmt(collections.Counter(reading_mods(b) for b in bs))])
    common.write_csv("beasts.csv", HEADER,
                     ["base", "items", "frames", "rarities", "genus", "group", "family", "name_pattern", "descrText",
                      "explicit_mods", "bestiary_mods_in_export", "in_site_monster_list", "in_apt_captured_beasts",
                      "an_export_base_name", "reading_apt", "reading_frame", "reading_lure",
                      "bestiary_mods_per_item", "reading_mods"], rows)

    # every body fact over the beasts
    facts = collections.defaultdict(collections.Counter)
    by_reading = collections.defaultdict(lambda: collections.defaultdict(set))  # fact -> value -> mods readings

    def seen(k, v, b):
        facts[k][v] += 1
        by_reading[k][v].add(reading_mods(b))

    for b in beasts:
        for k, v in b.items():
            if k in ("properties", "explicitMods"):
                continue
            seen(k, json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v, b)
        for k in set().union(*(set(x) for x in beasts)) - set(b):
            seen(k, "(absent)", b)
        for p in b.get("properties") or []:
            seen(f"properties[{p['name']}].value", p["values"][0][0] if p.get("values") else "", b)
            seen(f"properties[{p['name']}].type", p.get("type"), b)
            seen(f"properties[{p['name']}].displayMode", p.get("displayMode"), b)
        seen("properties (names in order)", " / ".join(p["name"] for p in b.get("properties") or []), b)
        seen("explicitMods (count)", len(b.get("explicitMods") or []), b)
        for m in b.get("explicitMods") or []:
            seen("explicitMods[].description", m.get("description"), b)
            seen("explicitMods[] keys", " ".join(sorted(m)), b)
    frows = []
    for k in sorted(facts):
        c = facts[k]
        vals = f"{len(c)} distinct (identity; values not listed)" if k == "id" else fmt(c)
        both = sum(1 for v in c if len(by_reading[k][v]) > 1)
        frows.append([k, "yes" if len(c) > 1 else "no", len(c), sum(c.values()), vals, both])
    common.write_csv("beast-facts.csv", HEADER, ["fact", "varies", "distinct", "occurrences", "values",
                                                 "values_on_beasts_of_both_mods_readings"], frows)

    # printed
    print(f"F3 beasts on the copy: {len(beasts)} items, {len(per)} bases; in the site's monster list: "
          f"{sum(1 for b in per if b in site_monster)}; in APT's CAPTURED_BEAST: {sum(1 for b in per if b in apt_beasts)}; "
          f"an export base name: {sum(1 for b in per if b in ex.by_name)}")
    print(f"F3 the site's monster list {len(site_monster)}; APT's captured beasts {len(apt_beasts)}, of them in the site's list "
          f"{len(apt_beasts & site_monster)}; site names not in APT {len(site_monster - apt_beasts)}")
    print(f"F3 facts: {len(frows)}; varying {sum(1 for r in frows if r[1] == 'yes')}: {[r[0] for r in frows if r[1] == 'yes']}")
    print(f"F3 varying facts none of whose values sits on beasts of both mods readings: "
          f"{[r[0] for r in frows if r[1] == 'yes' and r[5] == 0]}")
    print(f"F3 constant: {[(r[0], r[4]) for r in frows if r[1] == 'no']}")
    print(f"F3 lure words (export): {lures}; bestiary mods in the export: {len(bestiary_mods)}")
    rf = collections.Counter(reading_frame(b) for b in beasts)
    rl = collections.Counter(reading_lure(common.shown(b['baseType'])) for b in beasts)
    print(f"F3 readings over items: apt {{'monster.beast': {len(beasts)}}}; frame {dict(rf)}; lure {dict(rl)}")
    rlb = collections.Counter(reading_lure(b) for b in per)
    print(f"F3 lure reading over bases: {dict(rlb)}")
    # which body facts line up with the lure reading, item by item
    for fact in ("Family", "Group", "Genus"):
        tab = collections.Counter((props(b).get(fact), reading_lure(common.shown(b["baseType"]))) for b in beasts)
        split = {v for (v, r) in tab}
        mixed = sorted(v for v in split if (v, "monster.redbeast") in tab and (v, "monster.yellowbeast") in tab)
        print(f"F3 {fact} against the lure reading: {len(split)} values, {len(mixed)} hold both readings {mixed}")
    pres = collections.Counter()
    for b in beasts:
        base = common.shown(b["baseType"])
        own = any((m.get("description") or "") == f"{base.split(' ')[0]} Presence" for m in b.get("explicitMods") or [])
        any_lure = any((m.get("description") or "") in {f"{w} Presence" for w in lures} for m in b.get("explicitMods") or [])
        pres[(reading_lure(base), "own word's Presence" if own else "another lure word's Presence" if any_lure else "no lure word's Presence")] += 1
    print(f"F3 lure reading against a `<lure word> Presence` mod: {dict(sorted(pres.items()))}")
    bm = collections.Counter((reading_lure(common.shown(b["baseType"])),
                              any((m.get("description") or "") in bestiary_mods for m in b.get("explicitMods") or [])) for b in beasts)
    print(f"F3 lure reading against carrying any bestiary mod of the export: {dict(sorted(bm.items()))}")
    # the mods reading (the wiki's account, the owner's quote) against the lure reading
    rm = collections.Counter(reading_mods(b) for b in beasts)
    print(f"F3 mods reading over items: {dict(sorted(rm.items()))}, none (0 or over 2 bestiary mods) {rm['none']}; explicitMods count by bestiary count: "
          f"{dict(sorted(collections.Counter((len(b.get('explicitMods') or []), bestiary_count(b)) for b in beasts).items()))}")
    agree = collections.Counter(reading_mods(b) == reading_lure(common.shown(b["baseType"])) for b in beasts)
    print(f"F3 mods against lure, item by item: agree {agree[True]}, disagree {agree[False]}")
    base_agree = collections.Counter()
    for base, bs in per.items():
        ms = {reading_mods(b) for b in bs}
        base_agree["one mods reading, the lure's" if ms == {reading_lure(base)} else
                   "one mods reading, not the lure's" if len(ms) == 1 else "several mods readings"] += 1
    rmb = collections.Counter(next(iter({reading_mods(b) for b in bs})) for bs in per.values()
                              if len({reading_mods(b) for b in bs}) == 1)
    print(f"F3 mods against lure, base by base: {dict(sorted(base_agree.items()))}; mods reading over bases: {dict(sorted(rmb.items()))}")
    for base in ROUND_J_BEASTS:
        bs = per.get(base, [])
        print(f"F3 round j's beast {base}: items on the copy {len(bs)}; lure {reading_lure(base)}; "
              f"mods {dict(collections.Counter(reading_mods(b) for b in bs))}; frame {dict(collections.Counter(reading_frame(b) for b in bs))}")
    named = [n for n in sorted(site_monster) if n == "Black Mórrigan" or ", First of the " in n]
    for n in named:
        print(f"F3 wiki-named red beast candidate {n!r}: site's monster list yes; APT {'yes' if n in apt_beasts else 'no'}; "
              f"on the copy {len(per.get(n, []))}; lure reading {reading_lure(n)}; mods reading "
              f"{dict(collections.Counter(reading_mods(b) for b in per.get(n, []))) or 'not on the copy'}")
    import glob
    import os
    named = {}
    for f in sorted(glob.glob(os.path.join(common.POE1, "data", "*.json"))):
        text = open(f, encoding="utf-8").read()
        hits = sorted(b for b in per if json.dumps(b, ensure_ascii=False) in text)
        named[os.path.basename(f)] = len(hits)
    print(f"F4 top-level poe1/data files: {len(named)}; those naming any of the copy's {len(per)} beast bases as a string: "
          f"{ {k: v for k, v in named.items() if v} or 'none'}")
    print(f"F4 export classes whose id, name or category says beast/bestiary/monster/captured: {beast_classes}; "
          f"beast bases that are export base names: {sum(1 for b in per if b in ex.by_name)} of {len(per)}")


if __name__ == "__main__":
    main()
