#!/usr/bin/env python3
"""category, findings 1, 2, 5 and 6: every category id the trade site's filter lists, how it is
produced from the pinned export (a class, a name rule on the base, a rule on the body, or nothing),
and every live pc item of the owner's copy placed by those readings.

    python3 search/category/scripts/categories.py

Inputs (read-only; a clone at another commit is refused):
  ../trade-query/data/filters-2026-09-12.json   the 82 category ids with their texts
  ../trade-query/data/items-2026-09-12.json     the 22 coarse categories and their base types
  poe1/data/base_items.json, item_classes.json, gems.json @ e2bd511a   the classes (scripts/common.py)
  ../repoe/scripts/base-taxonomy.py             CLASS_TO_TRADE, NAME_RULES, PARENTS, predict — imported
  crates/acquisition-search/reference/classes-v1.toml   the shipped class table (what it lacks)
  ../item-facts/raw/m3/store/mock/GERWARIC_7694.db      the copy, sqlite mode=ro (skipped when absent)
  ../trade-query/raw/Trade - Path of Exile_files/*.js, *.html   grepped for the grouping ids (skipped when absent)

Outputs (data/):
  categories.csv   one row per id: text, top token, kind, how produced, classes and rule, the
                   export's bases placed there, the copy's items, the site's coarse agreement
  residue.csv      every live pc item no reading places under exactly one id, by base and reason
"""

import collections
import sys
import glob
import os

sys.dont_write_bytecode = True  # nothing is cached beside a script this track does not own
import common  # noqa: E402

HEADER = ("# generated by scripts/categories.py from ../trade-query/data/filters-2026-09-12.json and items-2026-09-12.json, "
          "poe1/data @ e2bd511a through ../repoe/scripts/base-taxonomy.py, classes-v1.toml, the copy ../item-facts/raw/m3 (local)")


def main():
    tax = common.taxonomy()
    ex = common.Export()
    _, table = common.load_table()
    ids = common.site_filters()
    texts = dict(ids)
    order = [i for i, _ in ids]
    coarse_by_type, coarse = common.site_coarse()
    coarse_ids = {c for c, _, _ in coarse}
    prefix_parents = {i for i in order if any(j.startswith(i + ".") for j in order)}
    rule_ids = {fine for _, _, fine in tax.NAME_RULES}

    # the export, base by base: every (name, class) the readings place, before any frame picks
    at = collections.defaultdict(set)          # id -> base names
    classes_at = collections.defaultdict(set)  # id -> classes
    name_ids = collections.defaultdict(set)
    for name, cls in ex.by_name.items():
        for c in cls:
            fine, _ = tax.predict(c, name)
            if fine:
                at[fine].add(name)
                classes_at[fine].add(c)
                name_ids[name].add(fine)
    several_names = {n for n, s in name_ids.items() if len(s) > 1}

    # the copy
    items = common.copy_items()
    one = collections.Counter()
    among = collections.Counter()
    residue = collections.Counter()
    residue_ids = {}
    buckets = collections.Counter()
    lacking_in_table = collections.Counter()
    at_class = collections.Counter()  # (id, class) -> items placed there with one id
    at_class_base = collections.Counter()  # (id, class, base) -> items
    class_items = collections.Counter()
    if items is not None:
        for _iid, _lg, _lk, body in items:
            placed, _basis, cls, reason = common.place(ex, tax, body)
            base = common.shown(body.get("baseType"))
            for c in cls:
                class_items[c] += 1
            if cls and not table.get(base) and not any(base.startswith(p) and table.get(base[len(p):]) for p in common.MAP_PREFIXES):
                lacking_in_table[(",".join(sorted(cls)), reason or "one id")] += 1
            if len(placed) == 1 and not reason:
                one[next(iter(placed))] += 1
                at_class[(next(iter(placed)), ",".join(sorted(cls)))] += 1
                at_class_base[(next(iter(placed)), ",".join(sorted(cls)), base)] += 1
                buckets["one id"] += 1
            else:
                buckets["several ids" if placed else "no id"] += 1
                for i in placed:
                    among[i] += 1
                key = (base, "several" if placed else "none", reason, ",".join(sorted(cls)))
                residue[key] += 1
                residue_ids[key] = " ".join(sorted(placed))

    def under(i):
        """items placed at i or under it by the dot"""
        return sum(v for k, v in one.items() if k == i or k.startswith(i + "."))

    rows = []
    for i in order:
        top = i.split(".")[0]
        dotted_parent = top if "." in i else ""
        if i in prefix_parents and i in tax.CLASS_TO_TRADE.values():
            kind = "prefix parent, and a class's id"
        elif i in prefix_parents:
            kind = "prefix parent"
        elif i in tax.PARENTS:
            kind = "grouping: members named by no dot"
        else:
            kind = "leaf"
        cls = sorted(classes_at.get(i, ()))
        if i in rule_ids:
            produced = "class + name rule"
        elif cls:
            produced = "class"
        elif i in common.BEASTS:
            produced = "rule on the body (candidate; the leaf unsettled)"
        elif i in prefix_parents:
            produced = "nothing: the union of the ids under it by the dot"
        else:
            produced = "nothing: membership not in the site's data"
        rules = " ".join(f"{c}:{fine}" for c, _, fine in tax.NAME_RULES if fine == i)
        names = at.get(i, set())
        agree = sorted(n for n in names if top in coarse_by_type.get(n, ()))
        disagree = sorted(f"{n} (site: {' '.join(sorted(coarse_by_type[n]))})" for n in names
                          if coarse_by_type.get(n) and top not in coarse_by_type[n])
        unlisted = sum(1 for n in names if n not in coarse_by_type)
        copy_one = "" if items is None else one.get(i, 0)
        copy_under = "" if items is None else (under(i) if kind.startswith("prefix") else "")
        copy_among = "" if items is None else among.get(i, 0)
        rows.append([i, texts[i], top if top in coarse_ids else "", dotted_parent,
                     "yes" if dotted_parent in texts else ("no" if dotted_parent else ""), kind, produced,
                     " ".join(f"{c}={ex.display(c) or '(no display name)'}" for c in cls), rules, len(names),
                     len(agree), len(disagree), unlisted, "; ".join(disagree), copy_one, copy_among, copy_under])
    common.write_csv("categories.csv", HEADER,
                     ["id", "text", "site_coarse", "dotted_parent", "dotted_parent_is_an_id", "kind", "produced_by",
                      "classes", "name_rule", "export_bases", "site_coarse_agrees", "site_coarse_disagrees",
                      "not_in_site_list", "disagreeing_bases", "copy_items", "copy_items_among_several",
                      "copy_items_at_or_under_by_dot"], rows)
    rrows = [[b, n, bucket, reason, residue_ids[(b, bucket, reason, c)], c]
             for (b, bucket, reason, c), n in sorted(residue.items(), key=lambda kv: (kv[0][2], -kv[1], kv[0][0]))]
    common.write_csv("residue.csv", HEADER, ["base", "items", "bucket", "why", "ids", "classes"], rrows)

    # printed: the numbers the README carries
    kinds = collections.Counter(r[5] for r in rows)
    prod = collections.Counter(r[6] for r in rows)
    print(f"F1 ids: {len(order)}; kinds: {dict(sorted(kinds.items()))}")
    print(f"F1 produced: {dict(sorted(prod.items()))}")
    leaves = [r for r in rows if not r[5].startswith("grouping") and r[5] != "prefix parent"]
    print(f"F1 leaves (a class's id included): {len(leaves)}; by a class {sum(1 for r in leaves if r[6] == 'class')}, "
          f"by a class + name rule {sum(1 for r in leaves if r[6] == 'class + name rule')}, "
          f"by nothing in the export {[r[0] for r in leaves if r[6] not in ('class', 'class + name rule')]}; "
          f"by a class or a class + name rule together {sum(1 for r in leaves if r[6] in ('class', 'class + name rule'))}")
    print(f"F1 base-taxonomy PARENTS: {len(tax.PARENTS)}; all are site ids: {tax.PARENTS <= set(order)}; "
          f"groupings (members named by no dot): {[r[0] for r in rows if r[5].startswith('grouping')]}")
    print(f"F1 export names placed under several ids: {len(several_names)}: "
          f"{sorted((n, tuple(sorted(name_ids[n]))) for n in several_names)}")
    dis = [(r[0], r[13]) for r in rows if r[11]]
    print(f"F1 site coarse vs export: agree {sum(r[10] for r in rows)}, disagree {sum(r[11] for r in rows)} {dis}, "
          f"not in the site's list {sum(r[12] for r in rows)}")
    ids_without_bases = [r[0] for r in rows if r[5] == 'leaf' and r[9] == 0]
    print(f"F1 leaves with no export base: {ids_without_bases}")
    inv = sorted(at.get("map.invitation", ()))
    site_inv = sorted(n for n in inv if "map" in coarse_by_type.get(n, ()))
    print(f"F1 map.invitation (text {texts['map.invitation']!r}): export bases {len(inv)}, of them in the site's map list {len(site_inv)} "
          f"{site_inv}, not Maven's {sum(1 for n in site_inv if not n.startswith('Maven'))}")

    # F2
    print(f"F2 prefix parents: {len(prefix_parents)}: " + ", ".join(
        f"{p} {sum(1 for j in order if j.startswith(p + '.'))}" for p in order if p in prefix_parents))
    tops_no_id = sorted({i.split('.')[0] for i in order if '.' in i and i.split('.')[0] not in texts})
    print(f"F2 dotted ids whose top token is no id: {[i for i in order if '.' in i and i.split('.')[0] in tops_no_id]} (tops {tops_no_id})")
    lone = [i for i in order if '.' not in i and i not in prefix_parents]
    print(f"F2 ids neither a parent nor under one: {len(lone)} {lone}")
    print(f"F2 coarse categories: {len(coarse)}; not a filter id: {sorted(coarse_ids - set(order))}; "
          f"filter top tokens not coarse: {sorted({i.split('.')[0] for i in order} - coarse_ids)}")
    print(f"F2 texts beginning 'Any': {sum(1 for i in order if texts[i].startswith('Any'))}, of them prefix parents or groupings "
          f"{sum(1 for i in order if texts[i].startswith('Any') and (i in prefix_parents or i in tax.PARENTS))}")
    raw = os.path.join(common.SEARCH, "trade-query", "raw")
    files = glob.glob(os.path.join(raw, "Trade - Path of Exile_files", "*.js")) + glob.glob(os.path.join(raw, "*.html"))
    if files:
        blob = "".join(open(f, encoding="utf-8", errors="replace").read() for f in files)
        groupings = [r[0] for r in rows if r[5].startswith("grouping")]
        print(f"F2 the saved page and its {len(files) - 1} bundles name the groupings: "
              f"{ {g: blob.count(chr(34) + g + chr(34)) + blob.count(chr(39) + g + chr(39)) for g in groupings} }")
    else:
        print("F2 the saved page is absent: its bundles not grepped")

    # F5
    if items is None:
        print("F5 the copy is absent: every count on it is an open question")
        return
    import hashlib
    print(f"F5 the copy's sha256 {hashlib.sha256(open(common.COPY, 'rb').read()).hexdigest()}")
    print(f"F5 live pc items: {len(items)}; buckets {dict(sorted(buckets.items()))}; sum {sum(buckets.values())}")
    why = collections.Counter()
    for (b, bucket, reason, c), n in residue.items():
        why[(bucket, reason)] += n
    print(f"F5 residue by reason: {dict(sorted(why.items()))}")
    for reason in sorted({k[2] for k in residue}):
        top = sorted(((n, k[0]) for k, n in residue.items() if k[2] == reason), reverse=True)
        print(f"F5   {reason}: {len(top)} bases; largest {top[:6]}")
    print(f"F5 leaves with no item on the copy ({sum(1 for r in leaves if r[14] == 0 and r[15] == 0)}): "
          f"{[r[0] for r in leaves if r[14] == 0 and r[15] == 0]}")
    print(f"F5 copy items by id, one id: {sorted(one.items(), key=lambda kv: -kv[1])}")
    for i in ("map", "currency"):
        print(f"F5 items with the one id {i}, by class: {sorted(((c, n) for (j, c), n in at_class.items() if j == i), key=lambda kv: -kv[1])}")
    inv = sorted(((n, base) for (j, k, base), n in at_class_base.items() if j == "map.invitation"), reverse=True)
    print(f"F5 map.invitation on the copy: {sum(n for n, _ in inv)} items; Maven's {sum(n for n, b in inv if b.startswith('Maven'))}, "
          f"other {[(b, n) for n, b in inv if not b.startswith('Maven')]}")
    for c in ("MiscMapItem", "VaultKey"):
        b = sorted(((n, base) for (j, k, base), n in at_class_base.items() if j == "map" and k == c), reverse=True)
        print(f"F5 {c} at map: {len(b)} bases; largest {b[:8]}")
    print(f"F5 bases the export classes and the shipped table lacks, items by (classes, bucket): {dict(sorted(lacking_in_table.items()))}")

    # F6
    noid = sorted(c for c in ex.classes if c not in tax.CLASS_TO_TRADE)
    held = [(c, ex.display(c) or "(none)", class_items[c]) for c in noid if class_items[c]]
    print(f"F6 classes with no id: {len(noid)}; held on the copy: {len(held)} classes, {sum(n for _, _, n in held)} items: {held}")


if __name__ == "__main__":
    main()
