#!/usr/bin/env python3
"""category, finding 7: coverage apart from use — for every site id, which surfaces on this machine
place which bases there, and every base two surfaces place under different ids.

    python3 search/category/scripts/crosscheck.py

Sources (common.py reads each; a clone at another commit is refused):
  export      poe1 @ e2bd511a through ../repoe/scripts/base-taxonomy.py: class, and name rule on the base
  site-coarse ../trade-query/data/items-2026-09-12.json: the site's own list, at the coarse (top-token) level
  apt         awakened-poe-trade @ ce551eb7: items.ndjson `craftable.category` through CATEGORY_TO_TRADE_ID
              (renderer/src/web/price-check/trade/pathofexile-trade.ts, lines 13-56)
  pob         PathOfBuilding @ 16de4b82: src/Data/Bases/*.lua `type`/`subType` through M.getTradeCategory
              (src/Classes/TradeHelpers.lua; the line is printed), with the slot a type is worn in
              (common.POB_SLOT; weapons in `Weapon 1`, shields and quivers in `Weapon 2`, an abyss jewel
              in an `Abyssal` socket)
  site-fetch  ../trade-query/raw/searches/q*-request.json and -fetch.json (local; skipped when absent): the
              base types the site returned for a search with a category, 2026-09-13 — the one leaf-level
              answer of the site's on this machine

How a source's id relates to the export's for one base: `same`; `nested by the dot` (one is the other's
dotted parent or top token); `under a grouping` (one is a grouping — weapon.dagger, weapon.onesword, ... —
whose members the site's data does not name, so the pair is unsettled); `different`; `export places none`.

Outputs (data/):
  category-crosscheck.csv       one row per (id, source, level): the bases placed, how many relate to the
                                export's placement in each way, and their names; a leaf no source but the
                                export reaches has a row saying so
  category-disagreements.csv    one row per base and pair of sources whose ids differ, both ids and the
                                relation; pairs nested by the dot are counted in the printout, not listed
"""

import collections
import sys
import itertools

sys.dont_write_bytecode = True  # nothing is cached beside a script this track does not own
import common  # noqa: E402

HEADER = ("# generated by scripts/crosscheck.py from poe1/data @ e2bd511a through ../repoe/scripts/base-taxonomy.py, "
          "../trade-query/data/items-2026-09-12.json and filters-2026-09-12.json, awakened-poe-trade @ ce551eb7, "
          "PathOfBuilding @ 16de4b82, ../trade-query/raw/searches (local)")


def main():
    tax = common.taxonomy()
    ex = common.Export()
    order = [i for i, _ in common.site_filters()]
    site_ids = set(order)
    prefix_parents = {i for i in order if any(j.startswith(i + ".") for j in order)}
    groupings = {i for i in tax.PARENTS if i not in prefix_parents}
    coarse_by_type, coarse = common.site_coarse()
    apt_place, apt_unmapped, apt_map, apt_beasts = common.apt()
    pob_place, pob_info, pob_line = common.pob()
    fetches = common.site_fetches()

    export = collections.defaultdict(set)
    for name, cls in ex.by_name.items():
        for c in cls:
            fine, _ = tax.predict(c, name)
            if fine:
                export[name].add(fine)

    def relate(sid, eids):
        if not eids:
            return "export places none"
        if sid in eids:
            return "same"
        for e in eids:
            if e.startswith(sid + ".") or sid.startswith(e + ".") or e.split(".")[0] == sid:
                return "nested by the dot"
        if sid in groupings or any(e in groupings for e in eids):
            if any(e.split(".")[0] == sid.split(".")[0] for e in eids):
                return "under a grouping"
        return "different"

    # every source's placements: source -> {base: set(ids)}
    placements = {
        "export": {n: set(s) for n, s in export.items()},
        "site-coarse": {n: set(s) for n, s in coarse_by_type.items()},
        "apt": {n: {i} for n, i in apt_place.items()},
        "pob": {n: {i} for n, i in pob_place.items() if i},
    }
    fetch_place = collections.defaultdict(set)
    for cat, cnt in fetches.items():
        for (bt, _klass), _n in cnt.items():
            fetch_place[bt].add(cat)
    if fetches:
        placements["site-fetch"] = dict(fetch_place)

    rows = []
    kinds = {}
    for i in order:
        kinds[i] = ("prefix parent" if i in prefix_parents else "grouping" if i in groupings else "leaf")
    reached = collections.defaultdict(set)  # id -> sources reaching it exactly
    via = collections.defaultdict(set)      # export leaf -> sources reaching its bases only through a parent or grouping
    all_ids = list(order) + sorted({i for p in placements.values() for s in p.values() for i in s} - site_ids)
    for i in all_ids:
        kind = kinds.get(i, "coarse only" if i in {c for c, _, _ in coarse} else "not a site id")
        for src, pl in placements.items():
            names = sorted(n for n, s in pl.items() if i in s)
            if names:
                reached[i].add(src)
                rel = collections.Counter(relate(i, export.get(n, set())) if src != "export" else "same" for n in names)
                rows.append([i, kind, src, "coarse id" if src == "site-coarse" else "exact", len(names), rel["same"], rel["nested by the dot"], rel["under a grouping"],
                             rel["different"], rel["export places none"], "; ".join(names)])
            if src in ("export", "site-coarse") or kind != "leaf":
                continue
            # the export's bases at this leaf that the source places at another id
            enames = sorted(n for n, s in export.items() if i in s)
            other = collections.defaultdict(list)
            for n in enames:
                for sid in pl.get(n, ()):
                    if sid != i:
                        other[sid].append(n)
            for sid in sorted(other):
                r = relate(sid, {i})
                if r in ("nested by the dot", "under a grouping"):
                    via[i].add(src)
                rows.append([i, kind, src, f"at {sid} ({r})", len(other[sid]), 0,
                             len(other[sid]) if r == "nested by the dot" else 0,
                             len(other[sid]) if r == "under a grouping" else 0,
                             len(other[sid]) if r == "different" else 0, 0, "; ".join(other[sid])])
        if kind == "leaf" and i in site_ids:
            top = i.split(".")[0]
            enames = sorted(n for n, s in export.items() if i in s)
            listed = [n for n in enames if n in coarse_by_type]
            if listed:
                ok = [n for n in listed if top in coarse_by_type[n]]
                rows.append([i, kind, "site-coarse", f"at {top} (the parent's level)", len(listed), 0, len(ok), 0,
                             len(listed) - len(ok), 0, "; ".join(ok)])
                reached[i].add("site-coarse")
            elif top in {c for c, _, _ in coarse} and not enames:
                n_site = sorted(n for n, s in coarse_by_type.items() if top in s)
                rows.append([i, kind, "site-coarse", f"at {top} (the parent's level; which leaf, not stated)", len(n_site),
                             0, 0, 0, 0, len(n_site), "; ".join(n_site)])
                reached[i].add("site-coarse")
            if reached[i] <= {"export"} and not via[i]:
                rows.append([i, kind, "(none but the export)", "", 0, 0, 0, 0, 0, 0, ""])
    common.write_csv("category-crosscheck.csv", HEADER,
                     ["id", "kind", "source", "level", "bases", "same", "nested_by_the_dot", "under_a_grouping",
                      "different", "export_places_none", "names"], rows)

    # disagreements: every base, every pair of sources whose ids differ
    drows = []
    nested = 0
    rel_count = collections.Counter()
    srcs = list(placements)
    names = sorted(set().union(*(set(p) for p in placements.values())))
    for n in names:
        for a, b in itertools.combinations(srcs, 2):
            ia, ib = placements[a].get(n, set()), placements[b].get(n, set())
            if not ia or not ib or ia == ib:
                continue
            if ia & ib:
                r = "shares an id; a name under several ids"
            else:
                rels = {relate(x, {y}) for x in ia for y in ib}
                r = next(k for k in ("nested by the dot", "under a grouping", "different") if k in rels)
            rel_count[(a, b, r)] += 1
            if r == "nested by the dot":
                nested += 1
                continue
            drows.append([n, a, " ".join(sorted(ia)), b, " ".join(sorted(ib)), r])
    common.write_csv("category-disagreements.csv", HEADER, ["base", "source_a", "id_a", "source_b", "id_b", "relation"], drows)

    # printed
    print(f"F7 sources: {list(placements)}; pob's getTradeCategory at TradeHelpers.lua line {pob_line}; "
          f"pob base entries read {len(pob_info)} names; pob with no id {sorted(t for n, (t, s, f) in pob_info.items() if not pob_place[n]) and collections.Counter(pob_info[n][0] for n in pob_info if not pob_place[n])}")
    print(f"F7 apt: {len(apt_place)} bases placed; craftable categories with no id {dict(collections.Counter(apt_unmapped.values()))}; "
          f"ids APT sends that the site's filter lacks {sorted(set(apt_map.values()) - site_ids)}; "
          f"APT's ids at groupings or prefix parents {sorted(set(apt_map.values()) & (groupings | prefix_parents))}")
    print(f"F7 pob ids at groupings or prefix parents {sorted(set(pob_place.values()) & (groupings | prefix_parents))}")
    leaves = [i for i in order if kinds[i] == "leaf" or i in ("map", "currency")]
    four = [i for i in leaves if {"export", "site-coarse", "apt", "pob"} <= reached[i]]
    three = [i for i in leaves if i not in four and {"export", "site-coarse"} <= reached[i] and (reached[i] & {"apt", "pob"})]
    coarse_only = [i for i in leaves if reached[i] & {"apt", "pob"} == set() and "site-coarse" in reached[i]]
    export_only = [i for i in leaves if reached[i] <= {"export"}]
    print(f"F7 leaves (map and currency, a class's ids, included): {len(leaves)}")
    print(f"F7   checked by all four at the leaf: {len(four)} {four}")
    print(f"F7   by the export, the site's coarse list and one of apt/pob at the leaf: {len(three)} "
          f"{[(i, sorted(reached[i] & {'apt', 'pob'})) for i in three]}")
    print(f"F7   by the site's coarse list alone (besides the export) at the leaf: {len(coarse_only)} {coarse_only}")
    print(f"F7     of them reached by apt or pob only through a grouping or parent: {sum(1 for i in coarse_only if via[i] & {'apt', 'pob'})} "
          f"{[(i, sorted(via[i])) for i in coarse_only if via[i]]}")
    print(f"F7   by the export alone: {len(export_only)} {export_only}")
    print(f"F7   reached by no source's bases (the beasts'): {[i for i in leaves if not reached[i]]}")
    for src in ("apt", "pob"):
        tot = collections.Counter()
        for r in rows:
            if r[2] == src and r[3] == "exact" and r[0] in site_ids:
                tot["bases"] += r[4]; tot["same"] += r[5]; tot["nested"] += r[6]; tot["grouping"] += r[7]
                tot["different"] += r[8]; tot["export places none"] += r[9]
        missing = collections.Counter()
        for i in leaves:
            e_l = {n for n, s in export.items() if i in s}
            s_l = {n for n, s in placements[src].items() if i in s}
            if s_l:
                missing["export bases at a leaf the source reaches, which the source lacks"] += len({n for n in e_l - s_l if n not in placements[src]})
                missing["... which the source places elsewhere"] += len({n for n in e_l - s_l if n in placements[src]})
        print(f"F7 {src} at site ids, exact: {dict(tot)}; {dict(missing)}")
        none = sorted({n for r in rows if r[2] == src and r[3] == "exact" for n in r[10].split("; ") if n and not export.get(n)})
        print(f"F7 {src} bases the export places nowhere: {len(none)} {none[:30]}")
    fetch_rel = collections.Counter()
    for cat, cnt in fetches.items():
        for (bt, _k), n in cnt.items():
            fetch_rel[(cat, relate(cat, export.get(bt, set())))] += n
    print(f"F7 site-fetch, items by (category searched, relation to the export): {dict(sorted(fetch_rel.items()))}")
    print(f"F7 site-fetch weapon.onesword returned classes: {dict(collections.Counter(k for (bt, k) in fetches.get('weapon.onesword', {}).elements()))}")
    print(f"F7 disagreements listed: {len(drows)}; by (pair, relation): {dict(sorted((k, v) for k, v in rel_count.items() if k[2] != 'nested by the dot'))}; "
          f"nested by the dot, counted not listed: {nested}")
    print(f"F7 disagreement rows by relation: {dict(collections.Counter(r[5] for r in drows))}")
    diff = [r for r in drows if r[5] == "different"]
    print(f"F7 'different' rows: {len(diff)}: {[tuple(r[:5]) for r in diff]}")
    print(f"F7 'shares an id' rows: {[tuple(r[:5]) for r in drows if r[5].startswith('shares')]}")


if __name__ == "__main__":
    main()
