#!/usr/bin/env python3
"""category, round j: the sheet's j rows read back against the export and the owner's copy.

    python3 search/category/scripts/round-j.py

Round j is tools/trade-sheet.py's `round_j`, written into search/pseudo-stats/data/search-sheet.csv;
its types are written out there. This script decodes each j row's link, takes its category and
type, and says what the export and the copy hold of the type: its classes, the leaf the shipped
rule (../repoe/scripts/base-taxonomy.py) gives it, the site's coarse list, the copy's items. It
fails when a type is no export base and no name on the site's `monster` list, or when a grouping's
search names a pair that is not the export's leaf for its type.

Inputs (read-only): the sheet, the copy (sqlite mode=ro), poe1/data @ e2bd511a, the site's coarse
list (../trade-query/data/items-2026-09-12.json). Output (data/): round-j.csv, one row per search.
"""

import base64
import collections
import csv
import json
import os
import re
import sys
import zlib

sys.dont_write_bytecode = True  # nothing is cached beside a script this track does not own
import common  # noqa: E402

SHEET = os.path.join(common.SEARCH, "pseudo-stats", "data", "search-sheet.csv")
HEADER = ("# generated by scripts/round-j.py from ../pseudo-stats/data/search-sheet.csv (round j), the copy "
          "../item-facts/raw/m3 (local), poe1/data @ e2bd511a through ../repoe/scripts/base-taxonomy.py, "
          "../trade-query/data/items-2026-09-12.json")
PACE = 10  # seconds a link: tools/trade-pages.py's PACE, the skill's pace
PAGE = 25  # links a page: tools/trade-pages.py's SIZE


def decode(link):
    token = link.rsplit("/", 1)[1]
    return json.loads(zlib.decompress(base64.urlsafe_b64decode(token + "=" * (-len(token) % 4)), 16 + zlib.MAX_WBITS))


def main():
    with open(SHEET, newline="") as fh:
        sheet = [r for r in csv.DictReader(fh) if re.fullmatch(r"j\d+", r["search"])]
    ex = common.Export()
    tax = common.taxonomy()
    coarse, _ = common.site_coarse()
    items = common.copy_items()
    held = collections.Counter(common.shown(b.get("baseType")) for _, _, _, b in items or [])
    faults = 0
    pairs = 0
    rows = []
    for r in sheet:
        q = decode(r["link"])
        cat = (((q.get("filters") or {}).get("type_filters") or {}).get("filters") or {}).get("category", {}).get("option", "")
        typ = q.get("type", "")
        classes = sorted(ex.by_name.get(typ, ())) if typ else []
        leaves = sorted({tax.predict(c, typ)[0] for c in classes} - {None, ""}) if typ else []
        if typ and not classes and "monster" not in coarse.get(typ, ()):
            faults += 1
            print(f"FAULT  {r['search']}: {typ!r} is no export base and not on the site's monster list")
        pair = re.search(r"the pair, (j\d+): `[^`]+` under `([^`]+)`", r["control"])
        pairs += bool(pair)
        if pair and pair.group(2) not in leaves:
            faults += 1
            print(f"FAULT  {r['search']}: the pair's leaf {pair.group(2)} is not the export's {leaves}")
        rows.append([r["search"], cat or "(none)", typ or "(none)", " ".join(classes), " ".join(leaves),
                     " ".join(sorted(coarse.get(typ, ()))) if typ else "", held[typ] if typ and items is not None else "",
                     r["control"]])
    common.write_csv("round-j.csv", HEADER, ["search", "category", "type", "export_classes", "export_leaf",
                                            "site_coarse", "copy_items", "control"], rows)
    print(f"round j: {len(rows)} searches; pages of {PAGE}: {-(-len(rows) // PAGE)}; at one link every {PACE} s: "
          f"{len(rows) * PACE // 60} min {len(rows) * PACE % 60} s of clicking")
    by_cat = collections.Counter(r[1] for r in rows)
    print(f"round j by category: {dict(sorted(by_cat.items()))}")
    for r in rows:
        print(f"  {r[0]}  {r[1]:<20} {r[2]:<24} export {r[3] or '-'} -> {r[4] or '-'}; coarse {r[5] or '-'}; copy {r[6]}")
    print(f"grouping searches whose pair was checked against the export's leaf: {pairs}; faults: {faults}")
    return 1 if faults else 0


if __name__ == "__main__":
    sys.exit(main())
