//! `CLI-REFERENCE.md` is generated from the binary's own help — every
//! subcommand's `--help`, walked from the root — and this test keeps the
//! committed copy equal to it. A golden file, not a frozen one (P5):
//! drift fails here, and
//! `ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-cli --test cli_reference`
//! rewrites it. The reader — an agent, a Codex session, an outside
//! reviewer — gets every verb's semantics without building; the writer
//! builds anyway. A verb's semantics is its help string (C11: the CLI
//! is itself an API); the README's tour shows the shape.

use std::process::Command;

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../CLI-REFERENCE.md");

fn help(path: &[String]) -> String {
    let out = Command::new(env!("CARGO_BIN_EXE_acq"))
        .args(path)
        .arg("--help")
        // The account arg renders `[env: ACQ_ACCOUNT=<value>]` when set.
        .env_remove("ACQ_ACCOUNT")
        .env("ACQ_NO_SPAWN", "1")
        .output()
        .expect("running acq --help");
    assert!(out.status.success(), "acq {} --help failed", path.join(" "));
    String::from_utf8(out.stdout).expect("help is UTF-8")
}

/// The subcommand names in one help text: the `Commands:` block, one
/// per line, `help` excluded.
fn subcommands(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut inside = false;
    for line in text.lines() {
        if line == "Commands:" {
            inside = true;
            continue;
        }
        if inside {
            if line.trim().is_empty() {
                break;
            }
            if let Some(name) = line.split_whitespace().next()
                && name != "help"
            {
                names.push(name.to_string());
            }
        }
    }
    names
}

fn walk(path: Vec<String>, out: &mut String) {
    let text = help(&path);
    let title = if path.is_empty() {
        "acq".to_string()
    } else {
        format!("acq {}", path.join(" "))
    };
    // The two global options render on every subcommand; shown once, under
    // the root, so a reader's 50 sections are not 13 KB of the same lines.
    let body: String = text
        .lines()
        .filter(|l| {
            path.is_empty()
                || !(l.trim_start().starts_with("--json ")
                    || l.trim_start().starts_with("--account "))
        })
        .map(|l| format!("{l}\n"))
        .collect();
    out.push_str(&format!(
        "## `{title}`\n\n```text\n{}\n```\n\n",
        body.trim_end_matches('\n')
    ));
    for sub in subcommands(&text) {
        let mut next = path.clone();
        next.push(sub);
        walk(next, out);
    }
}

fn render() -> String {
    let mut out = String::from(
        "# `acq` — command reference\n\n\
         Generated by `crates/acquisition-cli/tests/cli_reference.rs` from the \
         binary's own `--help`, every subcommand walked from the root; a golden \
         file the test keeps equal to the binary. Do not edit: change the help \
         string in `crates/acquisition-cli/src/main.rs` and regenerate with \
         `ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-cli --test cli_reference`. \
         The README's tour shows the shape; this is every verb's semantics. \
         `--json` and `--account` are global — every verb takes them — and are \
         listed once, under `acq`. The MCP server's tools are `MCP-REFERENCE.md`.\n\n",
    );
    walk(Vec::new(), &mut out);
    out
}

#[test]
fn the_reference_matches_the_binary() {
    let actual = render();
    if std::env::var_os("ACQ_UPDATE_FIXTURES").is_some() {
        std::fs::write(PATH, &actual).unwrap();
    }
    let expected = std::fs::read_to_string(PATH).unwrap_or_else(|e| panic!("{PATH}: {e}"));
    assert!(
        expected == actual,
        "CLI-REFERENCE.md no longer matches the binary's help; regenerate with \
         ACQ_UPDATE_FIXTURES=1 cargo test -p acquisition-cli --test cli_reference"
    );
    assert!(
        actual.contains("## `acq shop render`"),
        "the walk stopped early"
    );
}
