//! The class table (C106; the build plan, step 6): an item's class as the
//! game names it, read from its base by reviewed reference data (C68),
//! and what the search says of an item the table cannot class (C93).
//!
//! What reference data admits, and the admission test the table passed,
//! is `search/DESIGN.md`'s contract detail (C106 — what reference data
//! admits, and the test; C101 — the derived-field pseudos), cited and not
//! restated; the buckets of a count are `counts.rs`'s (C105).
//!
//! # As built
//!
//! - **The table is `reference/classes-v1.toml`** beside this crate,
//!   compiled in by `include_str!` and parsed once, on first use
//!   ([`table`]); generated by `tools/class-table.py` from the owner's
//!   pinned RePoE clone (`SURFACES.md`), reviewed as a diff at each pull,
//!   pinned by `tests/class.rs`. It is *data* under C106 — what the
//!   game's files state, never a convention and never a judgment — and
//!   the file's header and the script's docstring carry the rules a
//!   reviewer reads. The loader checks what a reviewer would: the version
//!   this build expects, every realm one GGG has, every class and base
//!   name non-empty, no class named twice, no base twice under one class.
//!   A table that fails is a build defect surfaced as [`ClassTableError`]
//!   to every caller — no corpus is loaded over it — never a partial
//!   table.
//! - **A class is the game's own name for it** — `Rings`, `Body Armours`,
//!   `Thrusting One Hand Swords` — the display name the export gives the
//!   class, which the clipboard's `Item Class:` line and an item filter's
//!   `Class` condition both print. `class:ring` picks the classes whose
//!   name holds the word (`Rings`), `class:sword` three; `class=Rings` is
//!   the one, in any case (B1); a word no name holds is an authoring
//!   error with the near names offered — `class:staff` offers
//!   `class=Staves` — since the search never fuzzy-matches (S107). The
//!   spelling is the builder's under rule 4 of the plan; `--describe
//!   class` prints every name with the table's source and version.
//! - **The lookup is the base, exact** ([`ClassTable::of`]): GGG's
//!   `baseType` as displayed (`derive::shown`) against the table's names
//!   as the export spells them. A transfigured gem's base is its own
//!   name, which the table holds from `gems.json`.
//! - **What the table cannot class is undecided with its reason** (C93,
//!   C105), one [`ClassGap`] each, said once, where the table is read
//!   (rule 8 of the plan): the base is not in the table (a blighted map,
//!   an itemised beast); it is in the table under more than one class
//!   (`Energy Blade`, a Maven's invitation — the table lists each and
//!   never chooses); the item's realm has no table (`poe2`); the item has
//!   no base. Each is `undecided(class)`: its reason on the row, its kind
//!   tallied beneath a count's `undecided` bucket, and its hint that a
//!   refresh will not help and a reference update may. A base the deriver
//!   could not read leaves the class open too, and that is the deriver's
//!   unread and not a second one here ([`Classed::BaseUnread`]). Known
//!   absence never occurs — every item has a class — so `-has:class`
//!   selects nothing and a count by class has no `none` bucket.
//! - **The version is on the basis** (C98; C106's clause (c)): `classes`
//!   beside the derivation, so two builds shipping different tables never
//!   label one answer alike.

use std::collections::{BTreeMap, HashMap};
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

use crate::corpus::REALMS;
use crate::derive::{Item, Part, Unread};

/// The table this build ships, verbatim (the reviewed file).
pub const CLASS_TABLE_TOML: &str = include_str!("../reference/classes-v1.toml");

/// The table version this build expects and every basis cites; a file
/// stamped otherwise is a build defect, not a runtime condition.
pub const CLASS_TABLE_VERSION: u32 = 1;

/// The hint on every class reason: the table, not the store, is what
/// could change (C93: a hint, never a guarantee).
pub const CLASS_HINT: &str = "a refresh will not help; a reference update may";

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct File {
    version: u32,
    realms: Vec<String>,
    source: String,
    game: String,
    #[allow(dead_code)]
    generated_by: String,
    #[serde(rename = "class", default)]
    classes: Vec<Rows>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Rows {
    name: String,
    bases: Vec<String>,
}

/// The parsed, checked table. Read-only; one per build.
#[derive(Debug)]
pub struct ClassTable {
    version: u32,
    realms: Vec<String>,
    source: String,
    game: String,
    /// The class names in the file's order.
    names: Vec<String>,
    /// Each base to the classes it is listed under, by their index in
    /// `names`; more than one where the source lists it so.
    by_base: HashMap<String, Vec<usize>>,
}

/// Why a table text is not a table. Every arm names the offending row so a
/// reviewer can fix the file, not the loader.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClassTableError {
    Parse(String),
    Version { found: u32, expected: u32 },
    UnknownRealm(String),
    NoRealm,
    NoClass,
    EmptyName { class: String },
    DuplicateClass(String),
    DuplicateBase { class: String, base: String },
}

impl std::fmt::Display for ClassTableError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ClassTableError::Parse(e) => write!(f, "the class table does not parse: {e}"),
            ClassTableError::Version { found, expected } => write!(
                f,
                "the class table is version {found}; this build reads version {expected}"
            ),
            ClassTableError::UnknownRealm(realm) => {
                write!(f, "the class table names a realm GGG has not: {realm:?}")
            }
            ClassTableError::NoRealm => write!(f, "the class table names no realm"),
            ClassTableError::NoClass => write!(f, "the class table has no class"),
            ClassTableError::EmptyName { class } => {
                write!(f, "the class table has an empty name under {class:?}")
            }
            ClassTableError::DuplicateClass(name) => {
                write!(f, "the class table names the class {name:?} twice")
            }
            ClassTableError::DuplicateBase { class, base } => {
                write!(f, "the class table lists {base:?} twice under {class:?}")
            }
        }
    }
}

impl std::error::Error for ClassTableError {}

static TABLE: LazyLock<Result<ClassTable, ClassTableError>> =
    LazyLock::new(|| ClassTable::parse(CLASS_TABLE_TOML));

/// The class names as a closed set the binder can hold (`bind::Kind`):
/// leaked once from the shipped table, empty when it does not load.
static NAMES: LazyLock<&'static [&'static str]> = LazyLock::new(|| match &*TABLE {
    Ok(table) => Box::leak(
        table
            .names
            .iter()
            .map(|name| &*Box::leak(name.clone().into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    ),
    Err(_) => &[],
});

/// The shipped table, parsed and checked once.
pub fn table() -> Result<&'static ClassTable, &'static ClassTableError> {
    TABLE.as_ref()
}

/// The legal values of `class`, in the table's order.
pub fn names() -> &'static [&'static str] {
    &NAMES
}

impl ClassTable {
    /// Parse and check a table text. The shipped file goes through
    /// [`table`]; this is the same path over any text, for the tests
    /// that pin what the loader refuses.
    pub fn parse(text: &str) -> Result<ClassTable, ClassTableError> {
        let file: File = toml::from_str(text).map_err(|e| ClassTableError::Parse(e.to_string()))?;
        if file.version != CLASS_TABLE_VERSION {
            return Err(ClassTableError::Version {
                found: file.version,
                expected: CLASS_TABLE_VERSION,
            });
        }
        if file.realms.is_empty() {
            return Err(ClassTableError::NoRealm);
        }
        if let Some(realm) = file.realms.iter().find(|r| !REALMS.contains(&r.as_str())) {
            return Err(ClassTableError::UnknownRealm(realm.clone()));
        }
        if file.classes.is_empty() {
            return Err(ClassTableError::NoClass);
        }
        let mut names: Vec<String> = Vec::with_capacity(file.classes.len());
        let mut by_base: HashMap<String, Vec<usize>> = HashMap::new();
        for (at, rows) in file.classes.into_iter().enumerate() {
            if rows.name.trim().is_empty() {
                return Err(ClassTableError::EmptyName {
                    class: rows.name.clone(),
                });
            }
            if names.contains(&rows.name) {
                return Err(ClassTableError::DuplicateClass(rows.name));
            }
            for base in rows.bases {
                if base.trim().is_empty() {
                    return Err(ClassTableError::EmptyName {
                        class: rows.name.clone(),
                    });
                }
                let under = by_base.entry(base.clone()).or_default();
                if under.contains(&at) {
                    return Err(ClassTableError::DuplicateBase {
                        class: rows.name.clone(),
                        base,
                    });
                }
                under.push(at);
            }
            names.push(rows.name);
        }
        Ok(ClassTable {
            version: file.version,
            realms: file.realms,
            source: file.source,
            game: file.game,
            names,
            by_base,
        })
    }

    /// The version every basis cites.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// The realms the table covers.
    pub fn realms(&self) -> &[String] {
        &self.realms
    }

    /// The table-level source, verbatim.
    pub fn source(&self) -> &str {
        &self.source
    }

    /// The game version the source was exported from.
    pub fn game(&self) -> &str {
        &self.game
    }

    /// The class names, in the file's order.
    pub fn names(&self) -> &[String] {
        &self.names
    }

    /// How many bases the table lists, a base under two classes twice.
    pub fn rows(&self) -> usize {
        self.by_base.values().map(Vec::len).sum()
    }

    /// The classes a base is listed under: none, one, or — where the
    /// source lists it so — several.
    pub fn of(&self, base: &str) -> Vec<&str> {
        self.by_base
            .get(base)
            .map(|under| under.iter().map(|at| self.names[*at].as_str()).collect())
            .unwrap_or_default()
    }

    /// Every base listed under more than one class, each with its classes.
    pub fn shared(&self) -> BTreeMap<&str, Vec<&str>> {
        self.by_base
            .iter()
            .filter(|(_, under)| under.len() > 1)
            .map(|(base, under)| {
                (
                    base.as_str(),
                    under.iter().map(|at| self.names[*at].as_str()).collect(),
                )
            })
            .collect()
    }

    /// What `--describe class` says of the table: what it is and where it
    /// is from, with its version.
    pub fn definition(&self) -> String {
        format!(
            "the item's class as the game names it, read from its base in the class table — classes v{}, {} classes over {}: {}. An item whose base the table lacks, lists under more than one class, or whose realm the table does not cover is undecided with that reason (C93); the table never chooses",
            self.version,
            self.names.len(),
            self.realms.join(", "),
            self.source
        )
    }

    /// What the table says of one derived item (the module doc).
    pub fn classify(&self, item: &Item) -> Classed {
        let open = |gap: ClassGap, problem: String| {
            Classed::Open(Unread {
                part: Part::Class(gap),
                problem,
                line: None,
            })
        };
        if !self.realms.contains(&item.facts.realm) {
            return open(
                ClassGap::NoTableForRealm,
                format!(
                    "no class table for realm {} (classes v{} covers {})",
                    item.facts.realm,
                    self.version,
                    self.realms.join(", ")
                ),
            );
        }
        let Some(base) = &item.base else {
            let base_key = Part::Field("baseType".to_string());
            return if item.unread_in(&base_key).next().is_some() {
                Classed::BaseUnread
            } else {
                open(
                    ClassGap::NoBase,
                    "the item has no base to class by".to_string(),
                )
            };
        };
        match self.of(base).as_slice() {
            [] => open(
                ClassGap::NotInTable,
                format!(
                    "`{base}` is not in the class table (classes v{})",
                    self.version
                ),
            ),
            [one] => Classed::Is((*one).to_string()),
            several => open(
                ClassGap::Several,
                format!(
                    "`{base}` is in the class table under {} (classes v{}): the table never chooses",
                    several.join(" and "),
                    self.version
                ),
            ),
        }
    }
}

/// What the class table says of one item.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Classed {
    /// The class of the item's base, as the game names it.
    Is(String),
    /// The base was read and the table could not class it: why, as the
    /// one unread that `undecided(class)` shows.
    Open(Unread),
    /// The base itself could not be read: the deriver's unread says so,
    /// and this says nothing twice.
    BaseUnread,
}

impl Classed {
    pub fn name(&self) -> Option<&str> {
        match self {
            Classed::Is(name) => Some(name),
            Classed::Open(_) | Classed::BaseUnread => None,
        }
    }

    /// The reason the table gives, where it gave one.
    pub fn open(&self) -> Option<&Unread> {
        match self {
            Classed::Open(unread) => Some(unread),
            Classed::Is(_) | Classed::BaseUnread => None,
        }
    }
}

/// Why the class table could not class an item (C93's closed list of
/// reasons, this table's part of it): the kind a count tallies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ClassGap {
    /// The base is not in the table.
    NotInTable,
    /// The base is in the table under more than one class.
    Several,
    /// The item's realm has no table.
    NoTableForRealm,
    /// The item has no base to look up.
    NoBase,
}

impl ClassGap {
    /// What was unread, as a reason and a tally name it (`eval::reason`).
    pub fn unread(self) -> &'static str {
        match self {
            ClassGap::NotInTable => "the class: base not in the table",
            ClassGap::Several => "the class: base under several classes",
            ClassGap::NoTableForRealm => "the class: no table for the realm",
            ClassGap::NoBase => "the class: no base",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{CLASS_TABLE_VERSION, ClassTable, ClassTableError, names, table};

    fn text(classes: &str) -> String {
        format!(
            "version = 1\nrealms = [\"pc\"]\nsource = \"s\"\ngame = \"g\"\ngenerated_by = \"t\"\n{classes}"
        )
    }

    /// The shipped file parses under the loader's checks and is the
    /// version this build cites; the binder's list is its names.
    #[test]
    fn the_shipped_table_loads_and_is_version_1() {
        let t = table().unwrap();
        assert_eq!(t.version(), CLASS_TABLE_VERSION);
        assert_eq!(t.realms(), ["pc", "xbox", "sony"]);
        assert_eq!(names().len(), t.names().len());
        assert!(names().iter().zip(t.names()).all(|(a, b)| a == b));
    }

    /// What the loader refuses, each by the row it names.
    #[test]
    fn the_loader_refuses_what_a_reviewer_would() {
        let one = "[[class]]\nname = \"Rings\"\nbases = [\"Iron Ring\"]\n";
        assert!(ClassTable::parse(&text(one)).is_ok());
        for (bad, expected) in [
            (
                text(one).replace("version = 1", "version = 2"),
                ClassTableError::Version {
                    found: 2,
                    expected: 1,
                },
            ),
            (
                text(one).replace("[\"pc\"]", "[\"ps4\"]"),
                ClassTableError::UnknownRealm("ps4".to_string()),
            ),
            (
                text(one).replace("[\"pc\"]", "[]"),
                ClassTableError::NoRealm,
            ),
            (text(""), ClassTableError::NoClass),
            (
                text("[[class]]\nname = \" \"\nbases = [\"Iron Ring\"]\n"),
                ClassTableError::EmptyName {
                    class: " ".to_string(),
                },
            ),
            (
                text("[[class]]\nname = \"Rings\"\nbases = [\"\"]\n"),
                ClassTableError::EmptyName {
                    class: "Rings".to_string(),
                },
            ),
            (
                text(&format!("{one}{one}")),
                ClassTableError::DuplicateClass("Rings".to_string()),
            ),
            (
                text("[[class]]\nname = \"Rings\"\nbases = [\"Iron Ring\", \"Iron Ring\"]\n"),
                ClassTableError::DuplicateBase {
                    class: "Rings".to_string(),
                    base: "Iron Ring".to_string(),
                },
            ),
        ] {
            assert_eq!(ClassTable::parse(&bad).unwrap_err(), expected);
        }
        assert!(matches!(
            ClassTable::parse("version = 1\nnope = 2"),
            Err(ClassTableError::Parse(_))
        ));
        // a base under two classes is no defect: the source lists it so
        let two = "[[class]]\nname = \"Rings\"\nbases = [\"Energy Blade\"]\n[[class]]\nname = \"Wands\"\nbases = [\"Energy Blade\"]\n";
        let t = ClassTable::parse(&text(two)).unwrap();
        assert_eq!(t.of("Energy Blade"), ["Rings", "Wands"]);
        assert_eq!(t.shared().len(), 1);
        assert_eq!(t.rows(), 2);
    }
}
