//! The totals table (C94; the build plan, step 7): a named total is a sum
//! that answers, defined once as reviewed reference data (C68, C106), so
//! that it has one meaning on every surface.
//!
//! The words are `search/DESIGN.md`'s reference (*Values*, *A sum's
//! status*); the rule that decides a total is this doc's (C94, taken from
//! the contract detail 2026-09-23). How a computed value is asked for,
//! evaluated and shown is `pseudo.rs`; what reference data admits, and the
//! admission test the table passed, is the contract detail (C106), cited
//! and not restated.
//!
//! # Decisions as recorded
//!
//! - **C94 — the totals table.** A total's row names the contributing
//!   line — its template, exact; its source and flag where they matter,
//!   any otherwise — the slot of it or none, and a weight. For each
//!   occurrence the row names, a row with a slot contributes that slot's
//!   value times its weight: an all-elemental resistance line with `arg1`
//!   20 and weight 3 contributes 60 to `pseudo.total_res`; a row without a
//!   slot contributes its weight per occurrence, so weight 1 counts them.
//!   A readable line absent from every row is not an unknown contributor:
//!   the total answers its declared definition. A total of nothing is an
//!   honest zero (a sum, never a lacked line). A total whose rows are
//!   ranged lines sums low with low and high with high and is a ranged
//!   value taking `low`, `high` and `avg`. A contributor the search could
//!   not read — a source a row admits unread, an occurrence a row names
//!   whose number or flag is unread — leaves a subtotal marked incomplete,
//!   never a total: its comparison is undecided, `undecided( … )` of it is
//!   true (`pseudo.rs`). No definition for the item's realm is never a
//!   zero: the value is unavailable with that reason, undecided as an
//!   incomplete one is, and the reason names the realm and the versions
//!   (rule 8 of the plan: said once, where the table is read). The answer
//!   prints a definition on request (`--describe pseudo.<name>`, C97),
//!   and the table is checked, loudly, when it is built: a table that
//!   fails is a build defect surfaced as [`TotalsTableError`] to every
//!   caller, never a partial table.
//!
//! # As built
//!
//! - **The table is `reference/totals-v1.toml`** beside this crate,
//!   compiled in by `include_str!` and parsed once, on first use
//!   ([`table`]); generated by `tools/totals-table.py` from the C++ app's
//!   pseudomod tables (`src/pseudomods.cpp` at `master@946a4f51`, the
//!   extract `search/cpp-search/data/pseudomods.toml`), reviewed as a diff
//!   at each change, pinned by this module's tests (the shipped file loads
//!   at version 1; the loader refuses what a reviewer would) and at the
//!   crate's boundary by `tests/pseudo.rs`. It is *convention* under
//!   C106 — the app's own published definitions, each naming the trade
//!   site's pseudo stat (`site`), never a judgment — and the file's header
//!   and the script's docstring carry the rules a reviewer reads. The
//!   site's own answer on ten fetched items agrees with the fire
//!   resistance recipe on every one (the script's docstring); the coverage
//!   trial the plan owes is `search/pseudo-stats/scripts/coverage-trial.py`
//!   (M6, `SEARCH-SLICE.md`).
//! - **A row is a line's group** (`group::row`): bound once when the table
//!   is parsed, so what a row admits, selects and says of one occurrence
//!   is read as every other group's is (the build plan, step 4b), and a
//!   row's sum is the evaluator's own sum (`eval::sum`): one maker of a
//!   sum (rule 10 of the plan). The table's realms are the file's: PoE1's
//!   three share one game and one recipe, and `poe2` has none.
//! - **A weight is a whole number or a half**, carried in halves and
//!   applied exactly (`exact::Exact::halved`): the site's own
//!   `+94.5 total maximum Life` over `+90` life and `+9` Strength is the
//!   half (`search/pseudo-stats/README.md`). Units hold the half of a
//!   displayed number, of a sum of them and of a count, and not the half
//!   of a mean, so the loader refuses a half weight on a row whose slot is
//!   `avg` and on a ranged total, whose `avg` is a mean. A total is never
//!   rounded: `94.5` prints as `94.5`, and `>=94.5` is the comparison the
//!   reference's arithmetic rule gives it (*Slots*: exact in decimals).
//! - **The loader checks what a reviewer would**: the version this build
//!   expects, every realm one GGG has, every total named once by a name
//!   the language takes, every total with a row, every row's template one
//!   the tree admits — no sign before a `#`, no number typed into it — its
//!   source and flag legal words, its slot one the template has (or, on a
//!   ranged total, none, every template ranged), its weight finite,
//!   nonzero, a whole number or a half, and no row named twice.
//! - **The version is on the basis** (C98; C106's clause (c)): `totals`
//!   beside `classes`, so two builds shipping different tables never label
//!   one answer alike.

use std::collections::{BTreeMap, HashMap};
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

use crate::corpus::REALMS;
use crate::derive::{Part, Unread};
use crate::error::LanguageError;
use crate::group::{self, Group};
use crate::tree::{self, Node};
use crate::{print, template};

/// The table this build ships, verbatim (the reviewed file).
pub const TOTALS_TABLE_TOML: &str = include_str!("../reference/totals-v1.toml");

/// The table version this build expects and every basis cites; a file
/// stamped otherwise is a build defect, not a runtime condition.
pub const TOTALS_TABLE_VERSION: u32 = 1;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct File {
    version: u32,
    realms: Vec<String>,
    source: String,
    #[allow(dead_code)]
    generated_by: String,
    #[serde(rename = "total", default)]
    totals: Vec<TotalIn>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TotalIn {
    name: String,
    /// The trade site's pseudo stat this total corresponds to, where one
    /// does: a citation the translation reads (C99), never a binding.
    site: Option<String>,
    /// The text the source prints the total as.
    text: Option<String>,
    #[serde(default)]
    ranged: bool,
    rows: Vec<RowIn>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RowIn {
    template: String,
    source: Option<String>,
    flag: Option<String>,
    slot: Option<String>,
    weight: f64,
}

/// The parsed, checked table. Read-only; one per build.
#[derive(Debug)]
pub struct TotalsTable {
    version: u32,
    realms: Vec<String>,
    source: String,
    totals: Vec<Total>,
    by_name: HashMap<String, usize>,
    /// Why a total is unavailable in a realm the table does not cover, one
    /// reason per realm GGG has, made once so that a reason is borrowed as
    /// the deriver's are (`eval::why`).
    unavailable: BTreeMap<String, Unread>,
    /// The reason for a realm outside GGG's list.
    elsewhere: Unread,
}

/// One named total.
#[derive(Debug)]
pub struct Total {
    pub name: String,
    pub site: Option<String>,
    pub text: Option<String>,
    /// A ranged value, taking `low`, `high` and `avg`.
    pub ranged: bool,
    pub(crate) rows: Vec<Row>,
}

/// What names a row once: its template, source, flag and slot.
type RowKey = (String, Option<String>, Option<String>, Option<String>);

/// One contributing line.
#[derive(Debug)]
pub(crate) struct Row {
    /// The line as a term: what the definition prints.
    pub term: Node,
    pub group: Group,
    /// None counts occurrences.
    pub slot: Option<String>,
    /// The weight, in halves.
    pub halves: i64,
}

/// Why a table text is not a table. Every arm names the offending row so a
/// reviewer can fix the file, not the loader.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TotalsTableError {
    Parse(String),
    Version {
        found: u32,
        expected: u32,
    },
    UnknownRealm(String),
    NoRealm,
    NoTotal,
    BadName(String),
    DuplicateTotal(String),
    NoRows {
        total: String,
    },
    /// A row the language or the table's rules refuse, with the message.
    Row {
        total: String,
        template: String,
        problem: String,
    },
    DuplicateRow {
        total: String,
        template: String,
    },
}

impl std::fmt::Display for TotalsTableError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TotalsTableError::Parse(e) => write!(f, "the totals table does not parse: {e}"),
            TotalsTableError::Version { found, expected } => write!(
                f,
                "the totals table is version {found}; this build reads version {expected}"
            ),
            TotalsTableError::UnknownRealm(realm) => {
                write!(f, "the totals table names a realm GGG has not: {realm:?}")
            }
            TotalsTableError::NoRealm => write!(f, "the totals table names no realm"),
            TotalsTableError::NoTotal => write!(f, "the totals table has no total"),
            TotalsTableError::BadName(name) => write!(
                f,
                "the totals table names a total {name:?}, which is no name the language takes: one word of letters, digits and underscores"
            ),
            TotalsTableError::DuplicateTotal(name) => {
                write!(f, "the totals table names the total {name:?} twice")
            }
            TotalsTableError::NoRows { total } => {
                write!(f, "the totals table's {total:?} has no row")
            }
            TotalsTableError::Row {
                total,
                template,
                problem,
            } => write!(
                f,
                "the totals table's {total:?}, row {template:?}: {problem}"
            ),
            TotalsTableError::DuplicateRow { total, template } => write!(
                f,
                "the totals table's {total:?} names the row {template:?} twice"
            ),
        }
    }
}

impl std::error::Error for TotalsTableError {}

static TABLE: LazyLock<Result<TotalsTable, TotalsTableError>> =
    LazyLock::new(|| TotalsTable::parse(TOTALS_TABLE_TOML));

/// The shipped table, parsed and checked once.
pub fn table() -> Result<&'static TotalsTable, &'static TotalsTableError> {
    TABLE.as_ref()
}

/// The hint on every total reason: the table, not the store, is what
/// could change (C93: a hint, never a guarantee).
pub const TOTAL_HINT: &str = crate::class::CLASS_HINT;

/// Why a total could not be established on an item, this table's part of
/// C93's closed list of reasons: the kind a count tallies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TotalGap {
    /// The item's realm has no definition in the table.
    NoDefinitionForRealm,
}

impl TotalGap {
    /// What was unread, as a reason and a tally name it (`eval::reason`).
    pub fn unread(self) -> &'static str {
        match self {
            TotalGap::NoDefinitionForRealm => "the total: no definition for the realm",
        }
    }
}

impl TotalsTable {
    /// Parse and check a table text. The shipped file goes through
    /// [`table`]; this is the same path over any text, for the tests
    /// that pin what the loader refuses.
    pub fn parse(text: &str) -> Result<TotalsTable, TotalsTableError> {
        let file: File =
            toml::from_str(text).map_err(|e| TotalsTableError::Parse(e.to_string()))?;
        if file.version != TOTALS_TABLE_VERSION {
            return Err(TotalsTableError::Version {
                found: file.version,
                expected: TOTALS_TABLE_VERSION,
            });
        }
        if file.realms.is_empty() {
            return Err(TotalsTableError::NoRealm);
        }
        if let Some(realm) = file.realms.iter().find(|r| !REALMS.contains(&r.as_str())) {
            return Err(TotalsTableError::UnknownRealm(realm.clone()));
        }
        if file.totals.is_empty() {
            return Err(TotalsTableError::NoTotal);
        }
        let mut totals: Vec<Total> = Vec::with_capacity(file.totals.len());
        let mut by_name: HashMap<String, usize> = HashMap::new();
        for total in file.totals {
            if !tree::is_segment(&total.name) {
                return Err(TotalsTableError::BadName(total.name));
            }
            if by_name.contains_key(&total.name) {
                return Err(TotalsTableError::DuplicateTotal(total.name));
            }
            if total.rows.is_empty() {
                return Err(TotalsTableError::NoRows { total: total.name });
            }
            let mut rows: Vec<Row> = Vec::with_capacity(total.rows.len());
            let mut named: Vec<RowKey> = Vec::new();
            for row in total.rows {
                let refuse = |problem: String| TotalsTableError::Row {
                    total: total.name.clone(),
                    template: row.template.clone(),
                    problem,
                };
                let key = (
                    row.template.clone(),
                    row.source.clone(),
                    row.flag.clone(),
                    row.slot.clone(),
                );
                if named.contains(&key) {
                    return Err(TotalsTableError::DuplicateRow {
                        total: total.name,
                        template: row.template,
                    });
                }
                named.push(key);
                let (term, group) =
                    group::row(&row.template, row.source.as_deref(), row.flag.as_deref())
                        .map_err(|e: LanguageError| refuse(e.message))?;
                let ranged_template = template::slots(&row.template).ranged.is_some();
                match (&row.slot, total.ranged) {
                    (Some(slot), false) => {
                        template::check_slot(&row.template, slot).map_err(|e| refuse(e.message))?;
                    }
                    (None, false) => {}
                    (Some(_), true) => {
                        return Err(refuse(
                            "a ranged total's row names no slot: low and high are its pair"
                                .to_string(),
                        ));
                    }
                    (None, true) if !ranged_template => {
                        return Err(refuse(
                            "a ranged total's rows are ranged lines: a template with exactly one `# to #`"
                                .to_string(),
                        ));
                    }
                    (None, true) => {}
                }
                let halves = row.weight * 2.0;
                if !halves.is_finite() || halves == 0.0 || halves.fract() != 0.0 {
                    return Err(refuse(format!(
                        "a weight is a whole number or a half, never {}",
                        row.weight
                    )));
                }
                let halves = halves as i64;
                if halves % 2 != 0 && (total.ranged || row.slot.as_deref() == Some("avg")) {
                    return Err(refuse(
                        "a half weight is on a displayed number, never on a mean: not on `avg`, and not on a ranged total"
                            .to_string(),
                    ));
                }
                rows.push(Row {
                    term,
                    group,
                    slot: row.slot,
                    halves,
                });
            }
            by_name.insert(total.name.clone(), totals.len());
            totals.push(Total {
                name: total.name,
                site: total.site,
                text: total.text,
                ranged: total.ranged,
                rows,
            });
        }
        let covered = file.realms.join(", ");
        let reason = |realm: &str| Unread {
            part: Part::Total(TotalGap::NoDefinitionForRealm),
            problem: format!(
                "no totals table for realm {realm} (totals v{} covers {covered})",
                file.version
            ),
            line: None,
            name: None,
        };
        Ok(TotalsTable {
            unavailable: REALMS
                .iter()
                .filter(|r| !file.realms.iter().any(|c| c == *r))
                .map(|r| ((*r).to_string(), reason(r)))
                .collect(),
            elsewhere: reason("outside GGG's"),
            version: file.version,
            realms: file.realms,
            source: file.source,
            totals,
            by_name,
        })
    }

    /// The version every basis cites.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// The realms the table covers.
    pub fn realms(&self) -> &[String] {
        &self.realms
    }

    /// The table-level source, verbatim.
    pub fn source(&self) -> &str {
        &self.source
    }

    /// The totals, in the file's order.
    pub fn totals(&self) -> &[Total] {
        &self.totals
    }

    /// A total by name, in any case (B1: every name is matched so).
    pub fn get(&self, name: &str) -> Option<&Total> {
        self.by_name
            .get(name)
            .or_else(|| {
                self.by_name
                    .iter()
                    .find(|(n, _)| n.eq_ignore_ascii_case(name))
                    .map(|(_, at)| at)
            })
            .map(|at| &self.totals[*at])
    }

    /// Why a total has no value in `realm`, when the table does not cover
    /// it: the one reason, made once.
    pub fn unavailable(&self, realm: &str) -> Option<&Unread> {
        if self.realms.iter().any(|r| r == realm) {
            return None;
        }
        Some(self.unavailable.get(realm).unwrap_or(&self.elsewhere))
    }

    /// What `--describe` says of the table as a whole: where it is from,
    /// with its version.
    pub fn provenance(&self) -> String {
        format!(
            "totals v{}, {} totals over {}: {}",
            self.version,
            self.totals.len(),
            self.realms.join(", "),
            self.source
        )
    }
}

impl Total {
    /// The definition, as `--describe` prints it: each row's weight, slot
    /// and line (C94: printed on request).
    pub fn definition(&self) -> String {
        let rows: Vec<String> = self
            .rows
            .iter()
            .map(|row| {
                let weight = if row.halves % 2 == 0 {
                    (row.halves / 2).to_string()
                } else {
                    format!("{}", row.halves as f64 / 2.0)
                };
                match &row.slot {
                    Some(slot) => format!("{weight} × {slot} of {}", print::print(&row.term)),
                    None if self.ranged => {
                        format!("{weight} × low and high of {}", print::print(&row.term))
                    }
                    None => format!("{weight} per {}", print::print(&row.term)),
                }
            })
            .collect();
        let what = if self.ranged {
            "the sum over the item's lines, low with low and high with high — a range taking low, high and avg"
        } else {
            "the sum over the item's lines"
        };
        let site = match (&self.site, &self.text) {
            (Some(site), Some(text)) => format!("the trade site's {site} (`{text}`): "),
            (Some(site), None) => format!("the trade site's {site}: "),
            (None, Some(text)) => format!("`{text}`: "),
            (None, None) => String::new(),
        };
        format!("{site}{what} of {}", rows.join(" + "))
    }
}

#[cfg(test)]
mod tests {
    use super::{TOTALS_TABLE_VERSION, TotalsTable, TotalsTableError, table};

    fn text(totals: &str) -> String {
        format!("version = 1\nrealms = [\"pc\"]\nsource = \"s\"\ngenerated_by = \"t\"\n{totals}")
    }

    const ONE: &str = "[[total]]\nname = \"total_res\"\nrows = [\n  { template = \"#% to Fire Resistance\", slot = \"arg1\", weight = 1 },\n]\n";

    /// The shipped file parses under the loader's checks, is the version
    /// this build cites, and every total prints a definition.
    #[test]
    fn the_shipped_table_loads_and_is_version_1() {
        let t = table().unwrap();
        assert_eq!(t.version(), TOTALS_TABLE_VERSION);
        assert_eq!(t.realms(), ["pc", "xbox", "sony"]);
        assert_eq!(t.totals().len(), 35);
        let res = t.get("total_res").unwrap();
        assert_eq!(res.site.as_deref(), Some("pseudo_total_resistance"));
        assert!(!res.ranged);
        assert!(
            res.definition()
                .contains("3 × arg1 of line(\"#% to all Elemental Resistances\")"),
            "{}",
            res.definition()
        );
        assert!(t.get("TOTAL_RES").is_some());
        assert!(t.get("total_nothing").is_none());
        assert!(t.unavailable("pc").is_none());
        assert!(
            t.unavailable("poe2")
                .unwrap()
                .problem
                .contains("no totals table for realm poe2 (totals v1 covers pc, xbox, sony)")
        );
        assert!(t.unavailable("mars").is_some());
    }

    /// What the loader refuses, each by the row it names.
    #[test]
    fn the_loader_refuses_what_a_reviewer_would() {
        assert!(TotalsTable::parse(&text(ONE)).is_ok());
        for (bad, expected) in [
            (
                text(ONE).replace("version = 1", "version = 2"),
                TotalsTableError::Version {
                    found: 2,
                    expected: 1,
                },
            ),
            (
                text(ONE).replace("[\"pc\"]", "[\"ps4\"]"),
                TotalsTableError::UnknownRealm("ps4".to_string()),
            ),
            (
                text(ONE).replace("[\"pc\"]", "[]"),
                TotalsTableError::NoRealm,
            ),
            (text(""), TotalsTableError::NoTotal),
            (
                text(ONE).replace("total_res", "total-res"),
                TotalsTableError::BadName("total-res".to_string()),
            ),
            (
                text(&format!("{ONE}{ONE}")),
                TotalsTableError::DuplicateTotal("total_res".to_string()),
            ),
            (
                text("[[total]]\nname = \"total_res\"\nrows = []\n"),
                TotalsTableError::NoRows {
                    total: "total_res".to_string(),
                },
            ),
            (
                text(
                    "[[total]]\nname = \"total_res\"\nrows = [\n  { template = \"#% to Fire Resistance\", slot = \"arg1\", weight = 1 },\n  { template = \"#% to Fire Resistance\", slot = \"arg1\", weight = 2 },\n]\n",
                ),
                TotalsTableError::DuplicateRow {
                    total: "total_res".to_string(),
                    template: "#% to Fire Resistance".to_string(),
                },
            ),
        ] {
            assert_eq!(TotalsTable::parse(&bad).unwrap_err(), expected, "{bad}");
        }
        // a row the language or the table's rules refuse, with the message
        for (edit, problem) in [
            ("weight = 1", "weight = 0"),
            ("weight = 1", "weight = 0.25"),
            ("slot = \"arg1\"", "slot = \"arg2\""),
            ("slot = \"arg1\"", "slot = \"avg\""),
            (
                "slot = \"arg1\", weight = 1",
                "slot = \"avg\", weight = 0.5",
            ),
            ("\"#% to Fire Resistance\"", "\"+#% to Fire Resistance\""),
            ("\"#% to Fire Resistance\"", "\"+48% to Fire Resistance\""),
            ("slot = \"arg1\"", "source = \"explicits\", slot = \"arg1\""),
            ("slot = \"arg1\"", "flag = \"corrupted\", slot = \"arg1\""),
        ] {
            let bad = text(&ONE.replace(edit, problem));
            match TotalsTable::parse(&bad) {
                Err(TotalsTableError::Row { total, .. }) => assert_eq!(total, "total_res"),
                other => panic!("{problem}: {other:?}"),
            }
        }
        // a half weight on a displayed number is admitted; on a mean, not
        let half = text(&ONE.replace("weight = 1", "weight = 0.5"));
        assert!(TotalsTable::parse(&half).is_ok());
        let ranged = "[[total]]\nname = \"cold\"\nranged = true\nrows = [\n  { template = \"Adds # to # Cold Damage\", weight = 1 },\n]\n";
        assert!(TotalsTable::parse(&text(ranged)).is_ok());
        for (edit, problem) in [
            ("weight = 1", "weight = 0.5"),
            ("weight = 1", "slot = \"low\", weight = 1"),
            ("Adds # to # Cold Damage", "#% to Cold Resistance"),
        ] {
            assert!(
                TotalsTable::parse(&text(&ranged.replace(edit, problem)))
                    .unwrap_err()
                    .to_string()
                    .contains("\"cold\", row"),
                "{problem}"
            );
        }
        assert!(matches!(
            TotalsTable::parse("version = 1\nnope = 2"),
            Err(TotalsTableError::Parse(_))
        ));
        // a definition prints a half as written and a count as `per`
        let t = TotalsTable::parse(&text(
            "[[total]]\nname = \"life\"\nrows = [\n  { template = \"# to maximum Life\", slot = \"arg1\", weight = 1 },\n  { template = \"# to Strength\", slot = \"arg1\", weight = 0.5 },\n  { template = \"Has # Abyssal Sockets\", weight = 1 },\n]\n",
        ))
        .unwrap();
        assert_eq!(
            t.get("life").unwrap().definition(),
            "the sum over the item's lines of 1 × arg1 of line(\"# to maximum Life\") + 0.5 × arg1 of line(\"# to Strength\") + 1 per line(\"Has # Abyssal Sockets\")"
        );
    }
}
