#!/usr/bin/env python3
"""The class table (C106, C68): every base name the game's data files give a
class, and the class as the game names it — regenerated from the owner's
pinned RePoE clone (SURFACES.md, the RePoE row; search/repoe/MANIFEST.md)
into the reviewed file the search crate ships.

    python3 tools/class-table.py            # writes crates/acquisition-search/reference/classes-v1.toml
    python3 tools/class-table.py --check    # exits 1 when the file on disk differs from what the clone gives

Inputs (read-only; the clone must sit at POE1_COMMIT or this refuses to run —
a pull is a new commit here and a reviewed diff of the table, never a silent
regeneration):
  ../poe1/data/base_items.json     every base: name, item class, release state
  ../poe1/data/item_classes.json   the classes: their display names
  ../poe1/data/gems.json           every gem, its base item, and a transfigured
                                   gem's own display name (`active_skill.display_name`)

Rules, each a reading of the source and never a judgment (C106):
  1. A base enters under the display name of its class — the class as the
     game prints it (`Item Class: Rings` on the clipboard; `Class "Rings"`
     in an item filter) — when the base has a name and its class has a
     display name, whatever its release state: the export marks a base the
     game no longer drops `unreleased` (Blade Trap, held by the owner in a
     Remove-only tab, 2026-09-23), and a stash keeps what the game removed.
  2. A gem enters under its class by its displayed name, which for a
     transfigured gem (`Ice Nova of Frostbolts`) is its own and is no base
     of `base_items.json`.
  3. A name the source lists under more than one class is listed under each,
     and the search says so (`class.rs`): the table never chooses.
Nothing is renamed, merged or dropped beyond rules 1 and 2; the counts the
header prints are measured at generation.
"""

import collections
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
# the clones sit beside the repository (search/repoe/MANIFEST.md, "The clones")
POE1 = os.path.normpath(os.path.join(ROOT, "..", "..", "..", "poe1"))
POE1_COMMIT = "e2bd511a0133bbe6c1ab548ef1285cb99f3cf0e9"  # search/repoe/MANIFEST.md
OUT = os.path.join(ROOT, "crates", "acquisition-search", "reference", "classes-v1.toml")
VERSION = 1
REALMS = ["pc", "xbox", "sony"]  # the PoE1 export; poe2 has no table yet


def pinned(path, commit):
    head = subprocess.run(["git", "-C", path, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    if head != commit:
        sys.exit(f"{path} is at {head}, not the pinned {commit}: a pull is a new commit in this script and a reviewed diff of the table")


def toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    check = "--check" in sys.argv[1:]
    pinned(POE1, POE1_COMMIT)
    bases = json.load(open(os.path.join(POE1, "data", "base_items.json")))
    classes = json.load(open(os.path.join(POE1, "data", "item_classes.json")))
    gems = json.load(open(os.path.join(POE1, "data", "gems.json")))
    game = open(os.path.join(POE1, "version.txt")).read().strip()

    under = collections.defaultdict(set)  # class display name -> base names
    skipped = collections.Counter()
    for base in bases.values():  # rule 1
        name, display = base["name"], classes[base["item_class"]]["name"]
        if not name:
            skipped["no name"] += 1
        elif not display:
            skipped["class with no display name"] += 1
        else:
            under[display].add(name)
    gems_added = 0
    for gem in gems.values():  # rule 2
        base_item = gem.get("base_item")
        if not base_item:
            continue
        base = bases[base_item["id"]]
        display = classes[base["item_class"]]["name"]
        name = (gem.get("active_skill") or {}).get("display_name") or base_item["display_name"]
        if name and display and name not in under[display]:
            under[display].add(name)
            gems_added += 1
    by_name = collections.defaultdict(set)
    for display, names in under.items():
        for name in names:
            by_name[name].add(display)
    several = sorted(n for n, ds in by_name.items() if len(ds) > 1)
    rows = sum(len(names) for names in under.values())

    out = [
        f"# The class table — v1 (C106, C68; decisions/search.md), item search step 6.",
        "#",
        "# Reference data: reviewed, committed, shipped inside the binary",
        "# (`include_str!` in `src/class.rs`), read-only, never in a store file,",
        "# enumerable by `acq search --describe class`, cited by version in every",
        "# basis (C98). Generated by tools/class-table.py from the owner's pinned",
        "# RePoE clone, and reviewed as a diff at each pull (the admission test,",
        "# search/DESIGN.md, C106): data, what the game files state — never a",
        "# convention and never a judgment. Its rules are the script's docstring.",
        "#",
        "# What a row means: the base named is of the class named, the class as the",
        "# game prints it (`Item Class: Rings` on the clipboard, `Class \"Rings\"` in",
        "# an item filter). A name under two classes is listed under each and the",
        "# search says so (undecided, C93); the table never chooses. Corroboration:",
        "# the clipboard `Item Class:` line equals the export's class name for all",
        "# 46 listed base types the trade-query capture holds (search/repoe/README.md,",
        "# F3); the item-filter documentation names no vocabulary (item-filter S93).",
        "#",
        f"# Measured at generation: {len(under)} classes, {rows} rows, {len(several)} names under",
        f"# more than one class, {gems_added} names from gems.json (transfigured gems);",
        f"# skipped: {', '.join(f'{v} {k}' for k, v in sorted(skipped.items()))}.",
        "",
        f"version = {VERSION}",
        f"realms = [{', '.join(toml_str(r) for r in REALMS)}]",
        f"source = {toml_str(f'RePoE poe1 export @ {POE1_COMMIT[:8]} (game {game}): base_items.json, item_classes.json, gems.json; the owner’s clone of 2026-09-13, SURFACES.md')}",
        f"game = {toml_str(game)}",
        'generated_by = "tools/class-table.py"',
        "",
    ]
    for display in sorted(under):
        out.append("[[class]]")
        out.append(f"name = {toml_str(display)}")
        out.append("bases = [")
        for name in sorted(under[display]):
            out.append(f"  {toml_str(name)},")
        out.append("]")
        out.append("")
    text = "\n".join(out)
    if check:
        if not os.path.exists(OUT) or open(OUT, newline="").read() != text:
            sys.exit(f"{OUT} differs from what the clone at {POE1_COMMIT[:8]} gives: regenerate and review the diff")
        print(f"ok      {os.path.relpath(OUT, ROOT)} is what the clone gives")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print(f"{os.path.relpath(OUT, ROOT)}: {len(under)} classes, {rows} rows, {len(several)} names under more than one class")
    for name in several:
        print(f"  several: {name!r} -> {sorted(by_name[name])}")


if __name__ == "__main__":
    main()
