#!/usr/bin/env python3
"""Classify the trade site's 298 `pseudo` stats by the mechanism that answers them.

Regenerates ../data/pseudo-classes.csv and prints the per-class counts.
Run from anywhere: paths resolve against this file.

The one rule: an entry lands in a class only when a named input supports it,
with a locator a reader can open. Every rule below names the input it rests on.
A pattern is allowed only where the pattern is a lookup into an input (a name
match against pseudomods.toml, a key in property_type_to_field, a template in
mod-templates.csv, a property name in properties-census.csv). The fallback is
`unresolved` and nothing else, and each unresolved row names the read that
would close it.
"""

import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

SEARCH = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parents[1] / "data" / "pseudo-classes.csv"

STATS = SEARCH / "trade-query/data/stats-2026-09-12.json"
GRAMMAR = SEARCH / "trade-query/data/grammar.json"
FETCH = SEARCH / "trade-query/data/fetch-census.json"
PSEUDOMODS = SEARCH / "cpp-search/data/pseudomods.toml"
FIELDS = SEARCH / "item-facts/data/field-census.csv"
PROPS = SEARCH / "item-facts/data/properties-census.csv"
TEMPLATES = SEARCH / "item-facts/data/mod-templates.csv"

# Input paths as they appear in the evidence_source column (repo-relative).
P_GRAMMAR = "search/trade-query/data/grammar.json"
P_FETCH = "search/trade-query/data/fetch-census.json"
P_PSEUDOMODS = "search/cpp-search/data/pseudomods.toml"
P_FIELDS = "search/item-facts/data/field-census.csv"
P_PROPS = "search/item-facts/data/properties-census.csv"
P_TEMPLATES = "search/item-facts/data/mod-templates.csv"


def load_entries():
    doc = json.loads(STATS.read_text())
    group = next(g for g in doc["result"] if g["id"] == "pseudo")
    return group["entries"]


def load_property_type_to_field():
    """grammar.json property_type_to_field: property type -> filter key.

    Several keys are `stat.pseudo.*`: the site answers those pseudo stats from a
    property the item carries, not from its lines. Returns {pseudo id: type}.
    """
    table = json.loads(GRAMMAR.read_text())["property_type_to_field"]["table"]
    out = {}
    for type_id, field in table.items():
        if field.startswith("stat.pseudo."):
            out[field[len("stat.") :]] = type_id
    return out


def load_pseudomod_names():
    """The C++ app's 35 pseudomod tables: each sums a listed set of templates."""
    return re.findall(r'^name = "(.+)"$', PSEUDOMODS.read_text(), re.M)


def load_fetched_pseudomods():
    """pseudo stats the site itself put on a fetched item, with the item that showed it.

    These are the site's own answers: `lines.pseudoMods[].hash` names the stat and
    `description` carries the value it computed from the item's other lines.
    """
    doc = json.loads(FETCH.read_text())
    seen = {}
    for qid, query in doc["queries"].items():
        for i, item in enumerate(query["fetched"]):
            for j, line in enumerate(item.get("lines", {}).get("pseudoMods", []) or []):
                hash_ = line.get("hash", "")
                if not hash_.startswith("stat.pseudo."):
                    continue  # `statgroup.N` is the query's own weighted sum, not a stat
                key = hash_[len("stat.") :]
                seen.setdefault(key, (f"queries.{qid}.fetched[{i}].lines.pseudoMods[{j}]", line["description"]))
    return seen


def read_census(path, want):
    """Yield (line number in the file, row dict) for a census CSV.

    Each census file carries a `# generated by` comment line before the header
    (item-facts convention), so the header is the second line. `newline="\\n"`,
    not `""`: 260 of mod-templates.csv's game-text templates carry a bare CR
    (search/README.md's CRLF trap), and Python would split a line on it, putting
    every later line number 687 past what `sed -n` opens.
    """
    rows = []
    with path.open(newline="\n") as fh:
        next(fh)  # the comment line
        reader = csv.DictReader(fh)
        for row in reader:
            if want(row):
                rows.append((reader.line_num + 1, row))
    return rows


def load_templates():
    """mod-templates.csv: line template -> (file line, items) for lines private items show."""
    out = {}
    for lineno, row in read_census(TEMPLATES, lambda r: True):
        key = row["template"]
        if key not in out:
            out[key] = (lineno, int(row["items"]))
    return out


def load_properties():
    """properties-census.csv rows, keyed for the two families the pseudo texts need.

    - `properties` rows named `Quality (X)` (type 6): the catalyst and map quality
      the pseudo group asks for by that exact name.
    - `additionalProperties` type 49 rows whose *value* is a room name, grouped on
      the item under the `Open Rooms:` / `Obstructed Rooms:` headers: how a private
      Chronicle of Atzoatl carries its rooms.
    """
    quality = {}
    rooms = {}
    headers = {}
    for lineno, row in read_census(PROPS, lambda r: True):
        name, array, value, type_ = row["name"], row["array"], row["value_templates"], row["type"]
        if array == "properties" and name.startswith("Quality ("):
            quality.setdefault(name, (lineno, int(row["items"])))
        if array == "additionalProperties" and type_ == "49" and value:
            rooms.setdefault(value, (lineno, int(row["items"])))
        if array == "additionalProperties" and name in ("Open Rooms:", "Obstructed Rooms:"):
            headers.setdefault(name, lineno)
    return quality, rooms, headers


def load_fields():
    """field-census.csv: json path -> (file line, items) for the private corpus."""
    out = {}
    for lineno, row in read_census(FIELDS, lambda r: True):
        out.setdefault(row["path"], (lineno, int(row["items"])))
    return out


# Names the C++ table and the site spell differently for the same sum (cpp-search F3 /
# DIGEST S29: 34 of 35 names match trade's texts verbatim; this is the 35th).
PSEUDOMOD_ALIASES = {
    "#% total increased Physical Damage": "+#% total increased Physical Damage",
}

# The two eldritch implicit tiers. field-census shows the private item carries
# `searing` / `tangled` as bare booleans (presence), never the tier the text asks for.
IMPLICIT_TIER = {
    "pseudo.pseudo_searing_implicit_tier": "searing",
    "pseudo.pseudo_tangled_implicit_tier": "tangled",
}

QUALITY_RE = re.compile(r"^Quality \((.+)\): #%$")
ROOM_RE = re.compile(r"^Has Room: (.+)$")
DIGITS_RE = re.compile(r"\d+")


def classify():
    entries = load_entries()
    ptf = load_property_type_to_field()
    pseudomods = set(load_pseudomod_names())
    fetched = load_fetched_pseudomods()
    templates = load_templates()
    quality, rooms, room_headers = load_properties()
    fields = load_fields()

    # Family fallbacks: the best-attested sibling row, so a locator always opens.
    room_family = "properties-census.csv rows %s (type 49 room values), %s (Open Rooms:)" % (
        sorted(rooms.values())[0][0] if rooms else "?",
        room_headers.get("Open Rooms:", "?"),
    )
    best_room = max(rooms.items(), key=lambda kv: kv[1][1])
    room_family = "properties-census.csv row %d (%s) + row %d (Open Rooms:)" % (
        best_room[1][0],
        best_room[0],
        room_headers["Open Rooms:"],
    )
    best_quality = max(quality.items(), key=lambda kv: kv[1][1])
    quality_family = "properties-census.csv row %d (%s)" % (best_quality[1][0], best_quality[0])

    # The one read that closes each unresolved family. Every note names a read.
    READ_SUM = (
        "run one trade search on this id and read the returned item's pseudoMods "
        "against its lines, as fetch-census Q5 did for fire resistance"
    )
    rows = []
    for entry in entries:
        eid, text = entry["id"], entry["text"]
        cls = "unresolved"
        source = ""
        locator = ""
        note = ""

        # R1 — the site's own renderer maps a property type straight to this pseudo key.
        if eid in ptf:
            cls, source = "field", P_GRAMMAR
            locator = "property_type_to_field.table.%s" % ptf[eid]
            note = "the renderer reads a property of this type, not the item's lines"

        # R2 — the site put this pseudo on a fetched item and its value is the sum of
        # that item's displayed lines (the strongest evidence in the track).
        elif eid in fetched:
            loc, desc = fetched[eid]
            cls, source, locator = "sum", P_FETCH, loc
            note = "the site's own answer on a fetched item (%s)" % desc
            if text in pseudomods or PSEUDOMOD_ALIASES.get(text, text) in pseudomods:
                note += "; pseudomods.toml sums the same lines"

        # R3 — the C++ app keeps a table of the same name and the templates it sums.
        elif text in pseudomods or PSEUDOMOD_ALIASES.get(text, text) in pseudomods:
            name = text if text in pseudomods else PSEUDOMOD_ALIASES[text]
            cls, source = "sum", P_PSEUDOMODS
            locator = '[[pseudomod]] name="%s"' % name
            note = "sums the listed templates, a template listed N times counting N times"
            if name != text:
                note += "; the C++ name differs by its leading '+'"

        # R4 — the text asks for a modifier's identity (how many, which affix slot,
        # which tier). Only the trade fetch's `mods` list carries that; a private
        # item has none, and one modifier can make two lines (the Carnal Boots).
        elif (eid.startswith("pseudo.pseudo_number_of_") and text.endswith("Modifiers")) or eid in IMPLICIT_TIER:
            cls, source = "mod-behind-line", P_FETCH
            if eid in IMPLICIT_TIER:
                locator = "queries.q5.fetched[0].lines.explicitMods[0].mods[0].tier"
                note = (
                    "the tier is a property of the modifier; field-census row %d shows the private "
                    "item carries `%s` as a bare boolean, presence and not tier"
                    % (fields[IMPLICIT_TIER[eid]][0], IMPLICIT_TIER[eid])
                )
            else:
                locator = "queries.q2.fetched[0].lines.explicitMods[5:7] (Carnal Boots)"
                note = (
                    "one crafted modifier ('Upgraded' P0) makes two crafted-flagged lines there, "
                    "so counting lines does not count modifiers; census.mods_feeding_several_lines=31"
                )

        # R5 — the counted things are lines the private item displays.
        elif eid == "pseudo.pseudo_number_of_notable_passive_skills":
            lineno, items = templates["# Added Passive Skill is Prismatic Heart"]
            cls, source = "count", P_TEMPLATES
            locator = "mod-templates.csv row %d" % lineno
            note = (
                "196 `# Added Passive Skill is …` templates in the census, one line per notable "
                "on a cluster jewel, so the count is over lines"
            )

        # R6 — an influence is a key on the `influences` object, not a line.
        elif eid == "pseudo.pseudo_has_influence_count":
            lineno, items = fields["influences"]
            cls, source = "field", P_FIELDS
            locator = "field-census.csv row %d (influences)" % lineno
            note = (
                "counts the true keys of the `influences` object (%d items carry it, the six "
                "`influences.*` rows sum to more, so items carry several) — no line is counted"
                % items
            )
        elif eid.startswith("pseudo.pseudo_has_") and text.endswith(" Influence"):
            key = "influences." + eid[len("pseudo.pseudo_has_") : -len("_influence")]
            if key in fields:
                lineno, items = fields[key]
                cls, source = "field", P_FIELDS
                locator = "field-census.csv row %d (%s)" % (lineno, key)
                note = "%d private items carry the flag" % items

        # R7 — a temple room is a type-49 `additionalProperties` value under the
        # `Open Rooms:` / `Obstructed Rooms:` headers, which are the entry's two options.
        elif ROOM_RE.match(text):
            room = ROOM_RE.match(text).group(1)
            key = DIGITS_RE.sub("#", room)
            cls, source = "field", P_PROPS
            if key in rooms:
                lineno, items = rooms[key]
                locator = "properties-census.csv row %d (%s)" % (lineno, key)
                note = "%d private items carry the room as a property value" % items
            else:
                locator = room_family
                note = (
                    "family: the room is a type-49 property value under Open Rooms:/Obstructed "
                    "Rooms: (the entry's two options); this room name is absent from the corpus"
                )

        # R8 — catalyst and map quality are `properties` entries of that exact name.
        elif QUALITY_RE.match(text):
            name = "Quality (%s)" % QUALITY_RE.match(text).group(1)
            cls, source = "field", P_PROPS
            if name in quality:
                lineno, items = quality[name]
                locator = "properties-census.csv row %d (%s)" % (lineno, name)
                note = "%d private items carry the property" % items
            else:
                locator = quality_family
                note = "family: a type-6 `properties` entry of this name; this name is absent from the corpus"

        # R9 — a ranged pseudo whose own template the private items display.
        elif text.startswith("Adds # to #") and text in templates:
            lineno, items = templates[text]
            cls, source = "ranged-total", P_TEMPLATES
            locator = "mod-templates.csv row %d" % lineno
            note = (
                "%d private items show this ranged line, summed slot-wise; which other "
                "templates it also sums is open (see the README)" % items
            )

        # Fallback — unresolved, with the read that would close it.
        if cls == "unresolved":
            if text.startswith("Reflection of"):
                note = (
                    "fetch a Mirrored Tablet from trade (or capture one) and read its pseudoMods "
                    "against its properties; no census row names a Reflection"
                )
            elif eid == "pseudo.pseudo_lake_number_of_islands":
                note = (
                    "fetch a Mirrored Tablet and read its properties; no field, property or "
                    "template in the census mentions islands"
                )
            elif text.startswith("Has Logbook"):
                note = (
                    "capture an Expedition Logbook and check for a `logbookMods` array carrying "
                    "the faction and area; field-census has no `logbookMods` row"
                )
            elif eid == "pseudo.pseudo_base_defence_percentile":
                note = (
                    "read RePoE's base_items for per-base armour/evasion/energy-shield ranges; "
                    "repoe/README.md names no defence ranges among its five extracts, and "
                    "field-census has no `extended`/`base_defence_percentile`"
                )
            elif text in templates:
                note = "%s; the text matches mod-templates.csv row %d but no input states the set it sums" % (
                    READ_SUM,
                    templates[text][0],
                )
            else:
                note = "%s; no input names the lines it aggregates" % READ_SUM

        rows.append(
            {
                "id": eid,
                "text": text,
                "class": cls,
                "evidence_source": source,
                "evidence_locator": locator,
                "note": note,
            }
        )
    return rows


def main():
    rows = classify()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=["id", "text", "class", "evidence_source", "evidence_locator", "note"],
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)

    counts = Counter(r["class"] for r in rows)
    order = ["sum", "ranged-total", "count", "field", "computed", "mod-behind-line", "unresolved"]
    print("%s — %d entries" % (OUT, len(rows)))
    for cls in order:
        print("  %-16s %3d" % (cls, counts.get(cls, 0)))
    extra = set(counts) - set(order)
    if extra:
        print("  UNEXPECTED CLASSES: %s" % sorted(extra), file=sys.stderr)
        return 1
    assert len(rows) == 298, len(rows)
    assert all(r["evidence_source"] and r["evidence_locator"] for r in rows if r["class"] != "unresolved")
    assert all(not r["evidence_source"] and r["note"] for r in rows if r["class"] == "unresolved")
    return 0


if __name__ == "__main__":
    sys.exit(main())
