#!/usr/bin/env python3
"""Score each stated base-defence-percentile formula against the site's own
value: writes ../data/percentile-check.csv and prints the counts.

    percentile.py

One row per captured item carrying `extended.base_defence_percentile`
(search/trade-query/data/fetch-census.json: 30 of 70). The sittings' captures
(data/captures.json, tools/trade-captures.py) are scored the same way and
written to ../data/percentile-captures.csv, apart, since candidates.py reads
percentile-check.csv: every fetched row carrying the value, the first row
holding the same item named beside a repeat, and what the rule gives with a
roll allowed outside the base's range. A round's new captures are read here. For each: the base and
its defence ranges (search/repoe/data/base-defences.csv), the displayed
defences and quality (the item's `properties`), the lines read as local (the
line's trade id -> search/repoe/data/trade-stat-map.csv -> its export stat,
`is_local` in poe1/data/stats.json @ e2bd511a), the site's value, and what each
formula gives, as the lowest and the highest it could give: a displayed
defence is a rounded number.

The formulas, each as its source states it; none is preferred here:

- `apt` — awakened-poe-trade @ ce551eb7: renderer/src/parser/calc-q20.ts
  L116-L127 (calcPropPercentile; calcFlat L156-L160) and
  renderer/src/parser/Parser.ts L1266-L1282 ("Base percentile is the same for
  all defences": the first of armour, evasion, energy shield, ward the item
  carries): round(100 * (D / (1 + q/100) / (1 + inc/100) - flat - min) /
  (max - min)), clamped to 0..100. Evaluated at D - 0.5 and D + 0.5.
- `pob` — PathOfBuilding @ 16de4b82, src/Classes/Item.lua L2346-L2385: the
  same quotient per defence type, clamped to 0..1, four places; one value
  per type and no rule joining them. Its per-type columns are evaluated at
  D - 0.5 and D + 0.5; `pob_avg` joins them by the site's rule below.
- `site` — the site's own tip for the filter
  (search/trade-query/data/grammar.json, filter_groups[3].filters[5]): "The
  percentile of all base defence rolls, averaged (0-100%)". A roll is an
  integer in the base's range; the rolls are recovered as every integer B
  whose display, round-half-up of (B + flat) * (1 + inc/100) * (1 + q/100),
  equals D; each roll's percentile is 100 * (B - min) / (max - min); the
  average is rounded half up. `site_lo`/`site_hi` span every combination of
  recovered rolls; one value means the display fixes it.

Negative controls, printed: the same recovery with the display floored or
ceiled instead (how many items then admit no roll at all); the hybrids
joined by min, max or the first type instead of the average; the average
rounded half to even instead of half up; the local lines, or the quality,
not read; the global twins of the local defence lines read as local (C14 of
percentile-shapes.py: a private item shows the two alike, so the text reading
reads them); and, under `Quality does not increase Defences`, the quality read
after all, for the value and for the 20%-quality figure.

The quality multiplier both tools state is also checked against the site's
own figures: `extended.ar|ev|es` "includes base value, local modifiers, and
maximum quality" (grammar.json filter_groups[3].filters[0-2]), so the
recovered roll, displayed at quality max(20, q) (APT calc-q20.ts L52-L59),
should give it exactly; under `Quality does not increase Defences`, at no
quality (round i, i02: the site drops the term from both figures).

The searches of ROUND are printed one by one: the items each fetched, how
many the stated rule reproduces, how many the 20%-quality figure, how many
admit no roll in the base's range, and the highest value shown.
"""

import csv
import itertools
import json
import math
import re
import sys
from pathlib import Path

TRACK = Path(__file__).resolve().parents[1]
SEARCH = TRACK.parent
CLONES = SEARCH.parents[3]
OUT = TRACK / "data" / "percentile-check.csv"
CAPTURES = TRACK / "data" / "captures.json"
CAPTURE_OUT = TRACK / "data" / "percentile-captures.csv"
CAPTURE_FIRST_LINE = ("# generated by scripts/percentile.py from data/captures.json, ../repoe/data/base-defences.csv, "
                      "../repoe/data/trade-stat-map.csv and poe1/data/stats.json @ e2bd511a")

FETCH = SEARCH / "trade-query/data/fetch-census.json"
BASES = SEARCH / "repoe/data/base-defences.csv"
TRADE_MAP = SEARCH / "repoe/data/trade-stat-map.csv"
STATS = CLONES / "poe1/data/stats.json"

TYPES = ["ar", "ev", "es", "ward"]
PROPERTY = {"Armour": "ar", "Evasion Rating": "ev", "Energy Shield": "es", "Ward": "ward"}
BASE_COLUMNS = {
    "ar": ("armour_min", "armour_max"),
    "ev": ("evasion_min", "evasion_max"),
    "es": ("energy_shield_min", "energy_shield_max"),
    "ward": ("ward_min", "ward_max"),
}

# The export's local defence stats and what each does to which type: a flat
# addition before the increase, or an increase (the roles both tools use:
# APT calc-q20.ts L5-L38; PoB Item.lua L2347-L2365).
ROLES = {
    "local_base_physical_damage_reduction_rating": ("flat", ["ar"]),
    "local_base_evasion_rating": ("flat", ["ev"]),
    "local_energy_shield": ("flat", ["es"]),
    "local_ward": ("flat", ["ward"]),
    "local_evasion_rating_and_energy_shield": ("flat", ["ev", "es"]),
    "local_physical_damage_reduction_rating_+%": ("inc", ["ar"]),
    "local_evasion_rating_+%": ("inc", ["ev"]),
    "local_energy_shield_+%": ("inc", ["es"]),
    "local_ward_+%": ("inc", ["ward"]),
    "local_armour_and_evasion_+%": ("inc", ["ar", "ev"]),
    "local_armour_and_energy_shield_+%": ("inc", ["ar", "es"]),
    "local_evasion_and_energy_shield_+%": ("inc", ["ev", "es"]),
    "local_armour_and_evasion_and_energy_shield_+%": ("inc", ["ar", "ev", "es"]),
}
NO_QUALITY = "local_quality_does_not_increase_defences"
# The global stats whose text a local defence line displays the same
# (tools/trade-sheet.py, DEFENCE_TWINS), with the role the local one has.
TWINS = {
    "base_physical_damage_reduction_rating": ("flat", ["ar"]),
    "base_evasion_rating": ("flat", ["ev"]),
    "base_maximum_energy_shield": ("flat", ["es"]),
    "physical_damage_reduction_rating_+%": ("inc", ["ar"]),
    "evasion_rating_+%": ("inc", ["ev"]),
}
# The round whose searches are printed one by one (tools/trade-sheet.py, round_i).
ROUND = "i"


def read_commented_csv(path):
    with path.open(newline="\n") as fh:
        next(fh)
        reader = csv.DictReader(fh)
        return [(reader.line_num + 1, row) for row in reader]


def number(text):
    m = re.search(r"-?\d+(?:\.\d+)?", text)
    value = float(m.group()) if m else 0.0
    if " reduced " in text and value > 0:
        value = -value
    return value


def half_up(x):
    return math.floor(x + 0.5)


def half_even(x):
    return round(x)


def quotient(d, q, inc, flat, lo, hi):
    """The quotient both tools compute: the base roll's fraction of its range."""
    return (d / (1 + q / 100) / (1 + inc / 100) - flat - lo) / (hi - lo)


def apt_value(d, q, inc, flat, lo, hi):
    return min(max(half_up(quotient(d, q, inc, flat, lo, hi) * 100), 0), 100)


def pob_value(d, q, inc, flat, lo, hi):
    return round(min(max(quotient(d, q, inc, flat, lo, hi), 0), 1), 4) * 100


DISPLAY = {
    "half-up": half_up,
    "floor": lambda x: math.floor(x + 1e-9),
    "ceil": lambda x: math.ceil(x - 1e-9),
    # a control the captures asked for: an exact half shown as the number below
    "half-down": lambda x: math.ceil(x - 0.5 - 1e-9),
}


def rolls(d, q, inc, flat, lo, hi, display="half-up"):
    """Every integer roll whose display equals d."""
    if display == "either":
        # a control the captures asked for: an exact half shown either way
        return [b for b in range(int(lo), int(hi) + 1)
                if abs((b + flat) * (1 + inc / 100) * (1 + q / 100) - d) <= 0.5 + 1e-9]
    show = DISPLAY[display]
    return [b for b in range(int(lo), int(hi) + 1)
            if show((b + flat) * (1 + inc / 100) * (1 + q / 100)) == d]


def pct(b, lo, hi):
    return 100 * (b - lo) / (hi - lo)


def fmt(x):
    if x is None:
        return ""
    return ("%.2f" % x).rstrip("0").rstrip(".")


def read_item(item, bases, tmap, local):
    shown, quality = {}, 0.0
    for prop in item.get("properties", []):
        name, values = prop[1], prop[2]
        if name == "Quality":
            quality = number(values[0])
        elif name in PROPERTY:
            shown[PROPERTY[name]] = number(values[0])
    base_row, base = None, None
    # a capture names its base apart (`baseType`); the fetch census does not
    name = item.get("baseType", item["typeLine"])
    for lineno, row in bases.get(name, []):
        if {t for t in TYPES if row[BASE_COLUMNS[t][0]]} == set(shown):
            base_row, base = lineno, row
    if base is None:
        # a flat line can show a defence its base lacks: the one row whose
        # types the item shows, and only those read
        fits = [(lineno, row) for lineno, row in bases.get(name, [])
                if {t for t in TYPES if row[BASE_COLUMNS[t][0]]} < set(shown)]
        if len(fits) == 1:
            base_row, base = fits[0]
    flat = {t: 0.0 for t in TYPES}
    inc = {t: 0.0 for t in TYPES}
    read, no_quality = [], False
    for array, lines in item["lines"].items():
        if array == "pseudoMods":
            continue
        for line in lines:
            for stat in tmap.get(line["hash"].removeprefix("stat."), []):
                if stat == NO_QUALITY:
                    no_quality = True
                    read.append(line["description"])
                elif stat in ROLES and stat in local:
                    role, types = ROLES[stat]
                    for t in types:
                        (flat if role == "flat" else inc)[t] += number(line["description"])
                    read.append(line["description"])
    ranges = {}
    if base:
        for t in TYPES:
            lo_col, hi_col = BASE_COLUMNS[t]
            if base[lo_col] and t in shown:
                ranges[t] = (float(base[lo_col]), float(base[hi_col]))
    q = 0.0 if no_quality else quality
    return shown, quality, q, flat, inc, ranges, base_row, read


def twin_lines(item, tmap):
    """(flat, inc) of the item's global defence twins, read as if local."""
    flat = {t: 0.0 for t in TYPES}
    inc = {t: 0.0 for t in TYPES}
    for array, lines in item["lines"].items():
        if array == "pseudoMods":
            continue
        for line in lines:
            for stat in tmap.get(line["hash"].removeprefix("stat."), []):
                if stat in TWINS:
                    role, types = TWINS[stat]
                    for t in types:
                        (flat if role == "flat" else inc)[t] += number(line["description"])
    return flat, inc


def has_no_quality(item, tmap):
    return any(NO_QUALITY in tmap.get(line["hash"].removeprefix("stat."), [])
               for array, lines in item["lines"].items() if array != "pseudoMods" for line in lines)


def site_values(shown, q, flat, inc, ranges, display="half-up", join=None, rounding=half_up):
    per = {}
    for t, (lo, hi) in ranges.items():
        per[t] = [pct(b, lo, hi) for b in rolls(shown[t], q, inc[t], flat[t], lo, hi, display)]
    if not per:  # no base range to read: no value, never a zero
        return per, set()
    join = join or (lambda xs: sum(xs) / len(xs))
    out = set()
    for combo in itertools.product(*per.values()):
        out.add(rounding(join(combo)))
    return per, out


HEADER = [
    "locator", "base", "base_row", "quality", "armour", "evasion", "energy_shield", "ward",
    "local_lines", "site_value", "site_q20", "q20_predicted",
    "apt_type", "apt_point", "apt_lo", "apt_hi",
    "pob_ar_lo", "pob_ar_hi", "pob_ev_lo", "pob_ev_hi", "pob_es_lo", "pob_es_hi",
    "pob_ward_lo", "pob_ward_hi", "pob_avg_lo", "pob_avg_hi",
    "site_rolls", "site_lo", "site_hi",
    "apt_exact", "apt_within", "pob_avg_within", "site_within",
]
# The captures' file adds four columns: the first row holding the same item
# (a search's items recur across searches); the defences the item shows and
# its base lacks, which no roll reads; and the site's rule with a roll
# allowed anywhere from 0 to twice the base's maximum, unclamped — an item
# whose display no roll in the base's range gives reads over 100 there (the
# contract detail under C101).
CAPTURE_HEADER = HEADER + ["same_as", "shown_not_of_base", "beyond_range", "site_unbounded"]


def score(locator, item, bases, tmap, local):
    """One item's row of HEADER, and the tuple the negative controls replay."""
    ext = item.get("extended", {})
    value = ext["base_defence_percentile"]
    shown, quality, q, flat, inc, ranges, base_row, read = read_item(item, bases, tmap, local)
    no_quality = has_no_quality(item, tmap)
    q20_type = next((t for t in ("ar", "ev", "es") if t in shown and t in ext), None)
    q20_pred, q20_read = None, None
    if q20_type and q20_type in ranges:
        found = rolls(shown[q20_type], q, inc[q20_type], flat[q20_type], *ranges[q20_type])
        if len(found) == 1:
            q20_pred = half_up((found[0] + flat[q20_type]) * (1 + inc[q20_type] / 100)
                               * (1 + (0 if no_quality else max(20, q)) / 100))
            q20_read = half_up((found[0] + flat[q20_type]) * (1 + inc[q20_type] / 100)
                               * (1 + max(20, q) / 100))
    apt_type = next((t for t in TYPES if t in ranges), None)
    apt = (None, None, None)
    if apt_type:
        args = (q, inc[apt_type], flat[apt_type]) + ranges[apt_type]
        d = shown[apt_type]
        apt = (apt_value(d, *args), apt_value(d - 0.5, *args), apt_value(d + 0.5, *args))
    pob = {}
    for t in TYPES:
        if t in ranges:
            args = (q, inc[t], flat[t]) + ranges[t]
            pob[t] = (pob_value(shown[t] - 0.5, *args), pob_value(shown[t] + 0.5, *args))
    pob_avg = None
    if pob:
        pob_avg = (sum(v[0] for v in pob.values()) / len(pob),
                   sum(v[1] for v in pob.values()) / len(pob))
    per, site = site_values(shown, q, flat, inc, ranges)
    recovered = ";".join(
        f"{t}={'|'.join(str(b) for b in rolls(shown[t], q, inc[t], flat[t], *ranges[t]))}"
        for t in ranges
    )
    tflat, tinc = twin_lines(item, tmap)
    twins = any(tflat[t] or tinc[t] for t in ranges)  # a twin of a type the item reads
    control = (value, shown, q, flat, inc, ranges, len(ranges) > 1,
               twins, {t: flat[t] + tflat[t] for t in TYPES}, {t: inc[t] + tinc[t] for t in TYPES},
               no_quality, quality, q20_read, ext.get(q20_type) if q20_type else None)
    row = [
        locator, item.get("baseType", item["typeLine"]),
        "" if base_row is None else f"base-defences.csv row {base_row}",
        fmt(quality), fmt(shown.get("ar")), fmt(shown.get("ev")), fmt(shown.get("es")),
        fmt(shown.get("ward")), "; ".join(read), value,
        ext.get(q20_type, "") if q20_type else "", fmt(q20_pred),
        apt_type or "", fmt(apt[0]), fmt(apt[1]), fmt(apt[2]),
        *[fmt(pob[t][k]) if t in pob else "" for t in TYPES for k in (0, 1)],
        fmt(pob_avg[0]) if pob_avg else "", fmt(pob_avg[1]) if pob_avg else "",
        recovered,
        fmt(min(site)) if site else "", fmt(max(site)) if site else "",
        "yes" if apt_type and apt[0] == value else "no",
        "yes" if apt_type and apt[1] <= value <= apt[2] else "no",
        "yes" if pob_avg and pob_avg[0] - 0.5 <= value <= pob_avg[1] + 0.5 else "no",
        "yes" if value in site else "no",
    ]
    return row, control


def unbounded(control):
    """(the types whose display no roll in range gives and a roll outside does,
    with those rolls; the site's rule over rolls from 0 to twice the maximum)."""
    _, shown, q, flat, inc, ranges, _ = control[:7]
    beyond, per = [], {}
    for t, (lo, hi) in ranges.items():
        inside = rolls(shown[t], q, inc[t], flat[t], lo, hi)
        wide = rolls(shown[t], q, inc[t], flat[t], 0, 2 * hi)
        if not inside and wide:
            beyond.append(f"{t}={'|'.join(str(b) for b in wide)} of {fmt(lo)}-{fmt(hi)}")
        per[t] = [pct(b, lo, hi) for b in wide]
    values = {half_up(sum(c) / len(c)) for c in itertools.product(*per.values())} if per else set()
    span = f"{min(values)}-{max(values)}" if len(values) > 1 else (str(min(values)) if values else "")
    return "; ".join(beyond), span


def summarise(rows, controls, first_line):
    """The counts and the negative controls, printed; the same for either input."""
    n = len(rows)
    col = {h: k for k, h in enumerate(HEADER)}
    yes = lambda name: sum(1 for r in rows if r[col[name]] == "yes")
    zero = sum(1 for r in rows if r[col["site_value"]] == 0)
    hybrids = sum(1 for c in controls if c[6])
    single = sum(1 for r in rows if r[col["site_lo"]] != "" and r[col["site_lo"]] == r[col["site_hi"]])
    q20 = [(float(r[col["q20_predicted"]]), float(r[col["site_q20"]])) for r in rows
           if r[col["site_q20"]] != "" and r[col["q20_predicted"]] != ""]
    q20_ok = sum(1 for p, s in q20 if p == s)
    unpredicted = sum(1 for r in rows if r[col["site_q20"]] != "" and r[col["q20_predicted"]] == "")
    print(first_line.format(n=n, zero=zero, hybrids=hybrids))
    print(f"apt, exact at the displayed value:        {yes('apt_exact')} of {n}")
    print(f"apt, within its rounding envelope:        {yes('apt_within')} of {n}")
    print(f"pob per type, averaged (the site's rule): {yes('pob_avg_within')} of {n}")
    print(f"site's rule over recovered integer rolls: {yes('site_within')} of {n}"
          f" ({single} of {n} a single value: the display fixes it)")
    print(f"site's 20%-quality figure from the recovered roll, exactly: {q20_ok} of {len(q20)}"
          + (f" ({unpredicted} more not predicted: the figure's type not the base's, or no single roll)"
             if unpredicted else ""))
    print("negative controls (the site's rule, one part changed):")
    for display in ("floor", "ceil", "half-down", "either"):
        none_ = sum(1 for c in controls if not site_values(*c[1:6], display=display)[1])
        hit = sum(1 for c in controls if c[0] in site_values(*c[1:6], display=display)[1])
        print(f"  display {display:9}: {none_} items admit no roll; {hit} of {n} reproduced")
    two = sum(1 for c in controls if len(site_values(*c[1:6], display="either")[1]) > 1)
    print(f"  display either: {two} items give more than one value")
    for name, join in (("min", min), ("max", max), ("first type", lambda xs: xs[0])):
        hit = sum(1 for c in controls if c[6] and c[0] in site_values(*c[1:6], join=join)[1])
        print(f"  hybrids joined by {name:10}: {hit} of {hybrids} reproduced (average: "
              f"{sum(1 for c in controls if c[6] and c[0] in site_values(*c[1:6])[1])})")
    hit = sum(1 for c in controls if c[0] in site_values(*c[1:6], rounding=half_even)[1])
    print(f"  average rounded half to even: {hit} of {n} reproduced")
    with_lines = sum(1 for c in controls if any(c[3].values()) or any(c[4].values()))
    zero = {t: 0.0 for t in TYPES}
    hit = sum(1 for c in controls if (any(c[3].values()) or any(c[4].values()))
              and c[0] in site_values(c[1], c[2], zero, zero, c[5])[1])
    print(f"  local lines not read: {hit} of the {with_lines} items carrying one reproduced")
    hit = sum(1 for c in controls if c[2] and c[0] in site_values(c[1], 0.0, c[3], c[4], c[5])[1])
    print(f"  quality not read: {hit} of the {sum(1 for c in controls if c[2])} items with quality reproduced")
    twins = [c for c in controls if c[7]]
    hit = sum(1 for c in twins if c[0] in site_values(c[1], c[2], c[8], c[9], c[5])[1])
    print(f"  global defence twins read as local: {hit} of the {len(twins)} items carrying one of a type "
          f"they read reproduced (as from their ids: "
          f"{sum(1 for c in twins if c[0] in site_values(*c[1:6])[1])})")
    enchanted = [c for c in controls if c[10]]
    hit = sum(1 for c in enchanted if c[0] in site_values(c[1], c[11], c[3], c[4], c[5])[1])
    figures = [c for c in enchanted if c[12] is not None and c[13] is not None]
    print(f"  `Quality does not increase Defences`, quality read after all: {hit} of {len(enchanted)} "
          f"reproduced; the 20%-quality figure {sum(1 for c in figures if c[12] == float(c[13]))} of {len(figures)}")


def main():
    fetch = json.loads(FETCH.read_text())
    bases = {}
    for lineno, row in read_commented_csv(BASES):
        bases.setdefault(row["name"], []).append((lineno, row))
    tmap = {}
    for _, row in read_commented_csv(TRADE_MAP):
        tmap.setdefault(row["trade_id"], []).append(row["repoe_ids"])
    local = {k for k, v in json.loads(STATS.read_text()).items() if v.get("is_local")}

    rows, controls = [], []
    for qid, query in fetch["queries"].items():
        for i, item in enumerate(query["fetched"]):
            if "base_defence_percentile" not in item.get("extended", {}):
                continue
            row, control = score(f"queries.{qid}.fetched[{i}]", item, bases, tmap, local)
            rows.append(row)
            controls.append(control)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(HEADER)
        w.writerows(rows)
    summarise(rows, controls, "{n} items carry the site's value, {zero} of them 0; "
                              "{hybrids} bases carry two defence types")
    print(f"wrote {OUT.relative_to(SEARCH.parent)}")

    # The sittings' captures, scored the same way and written apart: candidates.py
    # reads percentile-check.csv, so these rows go to their own file.
    captures = json.loads(CAPTURES.read_text())["searches"]
    rows, controls, first = [], [], {}
    for name, capture in captures.items():
        for i, item in enumerate(capture["fetched"] or []):
            if "base_defence_percentile" not in item.get("extended", {}):
                continue
            locator = f"searches.{name}.fetched[{i}]"
            # the same item fetched by two searches differs in its pseudo lines alone
            key = json.dumps({k: (dict(v, pseudoMods=None) if k == "lines" else v)
                              for k, v in item.items() if k != "extended"}, sort_keys=True)
            same = first.get(key, "")
            if not same:
                first[key] = locator
            row, control = score(locator, item, bases, tmap, local)
            beyond, span = unbounded(control)
            extra = ";".join(t for t in TYPES if t in control[1] and control[5] and t not in control[5])
            rows.append(row + [same, extra, beyond, span])
            controls.append(control)
    with CAPTURE_OUT.open("w", newline="") as fh:
        fh.write(CAPTURE_FIRST_LINE + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(CAPTURE_HEADER)
        w.writerows(rows)
    print()
    print(f"the sittings' captures ({CAPTURES.relative_to(TRACK)}): {len(first)} distinct items "
          f"among these rows")
    summarise(rows, controls, "{n} fetched rows carry the site's value, {zero} of them 0; "
                              "{hybrids} carry two defence types or more")
    distinct = [k for k, r in enumerate(rows) if not r[len(HEADER)]]
    summarise([rows[k] for k in distinct], [controls[k] for k in distinct],
              "distinct items only: {n}, {zero} of them 0; {hybrids} with two defence types or more")
    col = {h: k for k, h in enumerate(CAPTURE_HEADER)}
    missed = [r for r in rows if r[col["site_within"]] != "yes" and not r[col["same_as"]]]
    print(f"distinct items the site's rule does not reproduce: {len(missed)}")
    for r in missed:
        print(f"  {r[col['locator']]}  {r[col['base']]}  site {r[col['site_value']]}  "
              f"rolls {r[col['site_rolls']] or '-'}  base {r[col['base_row']] or 'not in base-defences.csv'}  "
              f"not of base {r[col['shown_not_of_base']] or '-'}  "
              f"beyond {r[col['beyond_range']] or '-'}  unbounded {r[col['site_unbounded']] or '-'}")
    print(f"round {ROUND}, search by search (fetched rows; the stated rule; the 20%-quality figure; "
          f"no roll in range; the highest value shown; the items carrying a global defence twin of a type "
          f"they read, and how many of them the twins read as local reproduce; the hybrids, and how many min, "
          f"max and the first type each reproduce; the rows whose ward roll is read, and the repeats):")
    for name in sorted(captures):
        if not re.fullmatch(rf"{ROUND}\d+", name):
            continue
        ks = [k for k, r in enumerate(rows) if r[col["locator"]].startswith(f"searches.{name}.")]
        mine = [rows[k] for k in ks]
        twins = [controls[k] for k in ks if controls[k][7]]
        as_local = sum(1 for c in twins if c[0] in site_values(c[1], c[2], c[8], c[9], c[5])[1])
        hybrids = [controls[k] for k in ks if controls[k][6]]
        joins = [sum(1 for c in hybrids if c[0] in site_values(*c[1:6], join=j)[1])
                 for j in (min, max, lambda xs: xs[0])]
        figures = [r for r in mine if r[col["site_q20"]] != "" and r[col["q20_predicted"]] != ""]
        top = max((r[col["site_value"]] for r in mine), default="-")
        print(f"  {name}: total {captures[name]['search'].get('total')}; {len(mine)} rows; "
              f"{sum(1 for r in mine if r[col['site_within']] == 'yes')} reproduced; "
              f"q20 {sum(1 for r in figures if float(r[col['q20_predicted']]) == float(r[col['site_q20']]))}"
              f" of {len(figures)}; {sum(1 for r in mine if r[col['beyond_range']])} beyond; highest {top}; "
              f"twins {len(twins)}, read as local {as_local}; hybrids {len(hybrids)}, "
              f"min {joins[0]}, max {joins[1]}, first {joins[2]}; "
              f"ward read {sum(1 for k in ks if 'ward' in controls[k][5])}; "
              f"repeats {sum(1 for r in mine if r[col['same_as']])}")
    print(f"wrote {CAPTURE_OUT.relative_to(SEARCH.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
