#!/usr/bin/env python3
"""The copy's live armour items by the percentile's shapes: writes
../data/percentile-shapes.csv and prints the counts.

    percentile-shapes.py     # run percentile.py first: the same readers, imported

What the build's fixtures for `pseudo.defence_pct` are cut from (the plan,
9d; the contract detail under C101). It decides nothing about the site.

An armour item is a live item of the owner's store copy
(search/item-facts/raw/m3/store/mock/GERWARIC_7694.db, opened read-only)
that displays Armour, Evasion Rating, Energy Shield or Ward. Its class is
the shipped class table's (crates/acquisition-search/reference/classes-v1.toml)
by its base; its base's ranges are search/repoe/data/base-defences.csv's.

The item is read as the build must read it, from its text alone: a private
item carries no stat id, so each line's template (search/item-facts's rule)
is given the role its local stat has — the trade site's `(Local)` texts
joined to the export's stats by search/repoe/data/trade-stat-map.csv, the
`reduced` spelling the same stat below nothing — and then scored by
percentile.py's own reader and the site's stated rule, rounding half up.
The sittings' captures (data/captures.json) are read the same way, from
their text with their ids dropped, and the value so read is set beside the
site's: whether the text-only reading reproduces what the site showed.

A shape is a case of the round (C1–C8 as drafted in tools/trade-sheet.py,
C9 on as this script names them); an item is under every shape it has, and
under `none of them` when it has none. For each shape: how many copy items,
how many the stated rule reads to one value, to several (a span), and what
it cannot read, at the grain it is lost (rule 8 of the plan) — the item's
realm, its base, or one defence's roll. Bases the class table or
base-defences.csv does not hold are counted apart.
"""

import csv
import importlib.util
import json
import re
import sqlite3
import sys
import tomllib
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("percentile", HERE / "percentile.py")
P = importlib.util.module_from_spec(spec)
spec.loader.exec_module(P)

TRACK = P.TRACK
SEARCH = P.SEARCH
ROOT = SEARCH.parent
OUT = TRACK / "data" / "percentile-shapes.csv"
STORE = SEARCH / "item-facts/raw/m3/store/mock/GERWARIC_7694.db"
CLASSES = ROOT / "crates/acquisition-search/reference/classes-v1.toml"
TRADE_STATS = SEARCH / "trade-query/data/stats-2026-09-12.json"
FIRST_LINE = ("# generated by scripts/percentile-shapes.py from ../item-facts/raw/m3/store/mock/GERWARIC_7694.db "
              "(read-only), crates/acquisition-search/reference/classes-v1.toml, ../repoe/data/base-defences.csv, "
              "../repoe/data/trade-stat-map.csv, data/captures.json and poe1/data/stats.json @ e2bd511a")

NUM = re.compile(r"(?<![\d#])[-+]?\d+(?:\.\d+)?")  # search/item-facts/scripts/census.py, template()

SHAPES = [
    ("C1", "three defence types: the base has three of armour, evasion, energy shield"),
    ("C2", "ward: the base has ward"),
    ("C3", "a shield"),
    ("C4", "a helmet"),
    ("C5", "gloves"),
    ("C6", "quality above 20"),
    ("C7", "`Quality does not increase Defences`"),
    ("C8", "a unique"),
    ("C9", "a defence shown that the base lacks (a flat line of another type)"),
    ("C10", "a roll over the base's maximum: no roll in range gives the display, one above does"),
    ("C11", "a realm with no table (poe2)"),
    ("C12", "a display at an exact half: another roll gives it if a half may round down"),
    ("C13", "a `reduced` local defence line"),
    ("C14", "a defence line under its global twin, which a private item's text does not tell apart; "
            "on the copy, seen only where no roll in range then gives the display, one under it does"),
    ("none", "none of them"),
]


def template(text):
    return NUM.sub("#", text)


def role_ids():
    """{line template: a trade id whose export stat is a percentile role}, the
    `reduced` spelling beside each `increased` one, by the site's own texts."""
    wanted = set(P.ROLES) | {P.NO_QUALITY}
    out = {}
    for _, row in P.read_commented_csv(P.TRADE_MAP):
        if row["repoe_ids"] not in wanted:
            continue
        text = re.sub(r" \(Local\)$", "", row["trade_text"])
        t = text.replace("+#", "#")
        out.setdefault(t, row["trade_id"])
        if " increased " in t or t.startswith("#% increased"):
            out.setdefault(t.replace("increased", "reduced"), row["trade_id"])
    return out


def global_twins(roles):
    """The trade ids that display a role's text without `(Local)`: a global stat
    whose line a private item shows exactly as the local one's."""
    wanted = set(P.ROLES) | {P.NO_QUALITY}
    rows = [row for _, row in P.read_commented_csv(P.TRADE_MAP)]
    local_ids = {row["trade_id"] for row in rows if row["repoe_ids"] in wanted}
    return {row["trade_id"] for row in rows
            if row["trade_id"] not in local_ids and not row["trade_text"].endswith(" (Local)")
            and row["trade_text"].replace("+#", "#") in roles}


def as_capture(base, type_line, properties, arrays, roles):
    """An item in a capture's shape, each line given the id its template's role
    has (none where it has no role), so percentile.py's reader reads it."""
    lines = {}
    for array, entries in arrays.items():
        out = []
        for entry in entries:
            text = entry.get("description", "") if isinstance(entry, dict) else entry
            if not isinstance(text, str):
                continue
            for row in text.split("\n"):
                tid = roles.get(template(row))
                out.append({"description": row, "hash": f"stat.{tid}" if tid else ""})
        lines[array] = out
    return {"typeLine": type_line, "baseType": base, "properties": properties, "lines": lines}


MARKUP = re.compile(r"\[([^\[\]|]*)(?:\|([^\[\]]*))?\]")  # poe2's `[Armour]`, `[EnergyShield|Energy Shield]`


def store_properties(body):
    out = []
    for prop in body.get("properties", []) or []:
        values = prop.get("values") or []
        first = values[0][0] if values and values[0] else ""
        name = MARKUP.sub(lambda m: m.group(2) or m.group(1), prop.get("name") or "")
        out.append([prop.get("type"), name, [first]])
    return out


def shown_defences(properties):
    return {P.PROPERTY[p[1]] for p in properties if p[1] in P.PROPERTY}


def read(item, bases, tmap, local, value=None):
    """(the shapes, the reading: value / span / what is unread, the values)."""
    shown, quality, q, flat, inc, ranges, base_row, lines_read = P.read_item(item, bases, tmap, local)
    rows = bases.get(item["baseType"], [])
    base_types = set()
    if base_row is not None:
        base = next(r for n, r in rows if n == base_row)
        base_types = {t for t in P.TYPES if base[P.BASE_COLUMNS[t][0]]}
    shapes = set()
    if len(base_types & {"ar", "ev", "es"}) >= 3:
        shapes.add("C1")
    if "ward" in base_types:
        shapes.add("C2")
    if quality > 20:
        shapes.add("C6")
    if any("does not increase Defences" in r for r in lines_read):
        shapes.add("C7")
    if base_types and set(shown) - base_types:
        shapes.add("C9")
    if any(" reduced " in f" {r}" for r in lines_read):
        shapes.add("C13")
    if not rows:
        return shapes, "unread: base not in base-defences.csv", set()
    if base_row is None:
        return shapes, "unread: no row of the base has the defences shown", set()
    over = under = False
    for t, (lo, hi) in ranges.items():
        if not P.rolls(shown[t], q, inc[t], flat[t], lo, hi):
            wide = P.rolls(shown[t], q, inc[t], flat[t], 0, 2 * hi)
            over |= bool(wide) and min(wide) > hi
            under |= bool(wide) and max(wide) < lo
    if over:
        shapes.add("C10")
    if under:
        shapes.add("C14")
    for t, (lo, hi) in ranges.items():
        if len(P.rolls(shown[t], q, inc[t], flat[t], lo, hi, "either")) > len(
                P.rolls(shown[t], q, inc[t], flat[t], lo, hi)):
            shapes.add("C12")
    missing = [t for t, (lo, hi) in ranges.items() if not P.rolls(shown[t], q, inc[t], flat[t], lo, hi)]
    if missing:
        what = "over the maximum" if over else "under the minimum" if under else "none in range"
        return shapes, f"unread: no {'/'.join(missing)} roll gives the display ({what})", set()
    _, values = P.site_values(shown, q, flat, inc, ranges)
    return shapes, ("value" if len(values) == 1 else "span"), values


def main():
    bases = {}
    for lineno, row in P.read_commented_csv(P.BASES):
        bases.setdefault(row["name"], []).append((lineno, row))
    tmap = {}
    for _, row in P.read_commented_csv(P.TRADE_MAP):
        tmap.setdefault(row["trade_id"], []).append(row["repoe_ids"])
    local = {k for k, v in json.loads(P.STATS.read_text()).items() if v.get("is_local")}
    roles = role_ids()
    twins = global_twins(roles)
    classes = defaultdict(set)
    for c in tomllib.loads(CLASSES.read_text())["class"]:
        for b in c["bases"]:
            classes[b].add(c["name"])

    def class_shapes(base):
        names = classes.get(base, set())
        return {s for s, n in (("C3", "Shields"), ("C4", "Helmets"), ("C5", "Gloves")) if n in names}

    copy = {s: Counter() for s, _ in SHAPES}
    apart = Counter()
    overall = Counter()
    few = defaultdict(Counter)  # shape -> the copy's bases under it
    armour = 0
    if not STORE.exists():
        print(f"{STORE.relative_to(ROOT)} is absent: every count over the copy is an open question")
        db = None
    else:
        db = sqlite3.connect(f"file:{STORE}?mode=ro", uri=True)
    for realm, rarity, body in (db.execute(
            "select realm, rarity, json from items where removed_at is null order by id") if db else []):
        body = json.loads(body)
        props = store_properties(body)
        if not shown_defences(props):
            continue
        armour += 1
        base = body.get("baseType") or body.get("typeLine")
        shapes = class_shapes(base)
        if rarity == "Unique":
            shapes.add("C8")
        if base not in classes:
            apart["base not in the class table"] += 1
        if realm == "poe2":
            shapes.add("C11")
            outcome = "unread: realm poe2 has no table"
        else:
            arrays = {k: v for k, v in body.items() if k.endswith("Mods") and isinstance(v, list)}
            item = as_capture(base, body.get("typeLine", ""), props, arrays, roles)
            more, outcome, _ = read(item, bases, tmap, local)
            shapes |= more
            if outcome == "unread: base not in base-defences.csv":
                apart["base not in base-defences.csv"] += 1
        overall[outcome] += 1
        for s in shapes:
            few[s][base] += 1
        for s in shapes or {"none"}:
            copy[s]["items"] += 1
            copy[s][outcome] += 1

    # the captures, read from their text as the copy is
    captured = {s: Counter() for s, _ in SHAPES}
    seen = set()
    lost = []
    col = {h: k for k, h in enumerate(P.HEADER)}
    for name, capture in json.loads(P.CAPTURES.read_text())["searches"].items():
        for item in capture["fetched"] or []:
            ext = item.get("extended", {})
            if "base_defence_percentile" not in ext:
                continue
            key = json.dumps({k: (dict(v, pseudoMods=None) if k == "lines" else v)
                              for k, v in item.items() if k != "extended"}, sort_keys=True)
            if key in seen:
                continue
            seen.add(key)
            base = item.get("baseType", item["typeLine"])
            arrays = {k: [{"description": l["description"]} for l in v]
                      for k, v in item["lines"].items() if k != "pseudoMods"}
            text_item = as_capture(base, item["typeLine"], item["properties"], arrays, roles)
            shapes, outcome, values = read(text_item, bases, tmap, local, ext["base_defence_percentile"])
            shapes |= class_shapes(base)
            if item.get("rarity") == "Unique":
                shapes.add("C8")
            if any(l["hash"].removeprefix("stat.") in twins for k, v in item["lines"].items()
                   if k != "pseudoMods" for l in v):
                shapes.add("C14")
            row, _ = P.score(f"searches.{name}", dict(text_item, extended=ext), bases, tmap, local)
            by_ids, _ = P.score(f"searches.{name}", item, bases, tmap, local)
            if (row[col["site_within"]], row[col["q20_predicted"]]) != (by_ids[col["site_within"]],
                                                                        by_ids[col["q20_predicted"]]):
                lost.append(f"{name} {base}: from its ids {by_ids[col['site_within']]}, from its text "
                            f"{row[col['site_within']]}; lines read from text: {row[col['local_lines']] or '-'}")
            q20 = row[col["site_q20"]] != "" and row[col["q20_predicted"]] != ""
            for s in shapes or {"none"}:
                captured[s]["items"] += 1
                captured[s]["reproduced"] += ext["base_defence_percentile"] in values
                captured[s]["q20"] += q20
                captured[s]["q20 reproduced"] += q20 and float(row[col["q20_predicted"]]) == float(
                    row[col["site_q20"]])

    reasons = sorted({k for c in copy.values() for k in c if k.startswith("unread")})
    header = (["shape", "what", "copy_items", "copy_value", "copy_span"] + [r.replace("unread: ", "unread, ")
                                                                       for r in reasons]
              + ["captured_items", "captured_reproduced_from_text", "captured_q20_predicted",
                 "captured_q20_reproduced_from_text"])
    with OUT.open("w", newline="") as fh:
        fh.write(FIRST_LINE + "\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(header)
        for s, what in SHAPES:
            c, k = copy[s], captured[s]
            w.writerow([s, what, c["items"], c["value"], c["span"]] + [c[r] for r in reasons]
                       + [k["items"], k["reproduced"], k["q20"], k["q20 reproduced"]])
    print(f"the copy: {armour} live items display a defence")
    for why, n in sorted(apart.items()):
        print(f"  counted apart: {n} {why}")
    print(f"the captures: {len(seen)} distinct items carry the site's value, read from their text; "
          f"{len(lost)} read otherwise than from their ids")
    for line in lost:
        print(f"  {line}")
    print(f"{'shape':6} {'copy':>6} {'value':>6} {'span':>5} {'unread':>7}   {'captured':>8} {'reproduced':>10}"
          f" {'q20':>5} {'q20 ok':>6}")
    for s, _ in SHAPES:
        c, k = copy[s], captured[s]
        unread = sum(c[r] for r in reasons)
        print(f"{s:6} {c['items']:>6} {c['value']:>6} {c['span']:>5} {unread:>7}   {k['items']:>8} {k['reproduced']:>10}"
              f" {k['q20']:>5} {k['q20 reproduced']:>6}")
    print("the copy's bases under each shape of 30 items or fewer:")
    for s, _ in SHAPES:
        if s in few and sum(few[s].values()) <= 30:
            print(f"  {s}: " + ", ".join(f"{b} {n}" for b, n in sorted(few[s].items(), key=lambda kv: (-kv[1], kv[0]))))
    print("the copy's armour items by reading (an item once):")
    for r, n in sorted(overall.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>5}  {r}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
