#!/usr/bin/env python3
"""How often, and how much, Awakened PoE Trade's stats dataset moves.

Walks every commit that touched renderer/public/data/en/stats.ndjson in the
owner's clone (read-only: `git show` only) and records, per commit, the line
diff and the entry-level diff against the parent revision of the same file:
refs and trade ids added/removed, and surviving trade ids whose displayed text
changed (a rename that keeps the id).

Usage: python3 scripts/cadence.py   (from search/prior-art/)
"""

import csv
import datetime
import json
import os
import subprocess
import sys

CLONE = "/Users/tom/Development/GitHub/gerwaric/awakened-poe-trade"
PINNED = "ce551eb7a9b704fbdcc2478eebb26be8f91786c7"
PATH = "renderer/public/data/en/stats.ndjson"

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data")
PROV = (
    "# generated by scripts/cadence.py from "
    "`git log -- renderer/public/data/en/stats.ndjson` in "
    "awakened-poe-trade@ce551eb7 (read-only clone)"
)


def git(*args):
    return subprocess.run(
        ["git", "-C", CLONE, *args], capture_output=True, text=True
    ).stdout


def snapshot(rev):
    """refs, and trade id -> set of ref texts, at one revision."""
    text = git("show", f"{rev}:{PATH}")
    refs, by_id = set(), {}
    for line in text.split("\n"):
        if not line.strip():
            continue
        o = json.loads(line)
        for s in o["stats"] if "stats" in o else [o]:
            refs.add(s["ref"])
            for cat, lst in s["trade"]["ids"].items():
                for i in lst:
                    by_id.setdefault(i, set()).add(s["ref"])
    return refs, by_id


def main():
    head = git("rev-parse", "HEAD").strip()
    if head != PINNED:
        sys.exit(f"refusing: clone HEAD is {head}, expected {PINNED}")

    log = [
        l.split("|", 3)
        for l in git(
            "log", "--reverse", "--date=short", "--format=%h|%ad|%s", "--", PATH
        )
        .strip()
        .split("\n")
    ]
    numstat = {}
    cur = None
    for line in git(
        "log", "--date=short", "--format=C|%h", "--numstat", "--", PATH
    ).split("\n"):
        if line.startswith("C|"):
            cur = line[2:]
        elif line.strip() and cur:
            add, rem, _ = line.split("\t", 2)
            numstat[cur] = (add, rem)

    rows = []
    prev = None
    prev_date = None
    for h, date, subject in log:
        refs, by_id = snapshot(h)
        ids = set(by_id)
        add, rem = numstat.get(h, ("", ""))
        d = datetime.date.fromisoformat(date)
        rows.append(
            {
                "commit": h,
                "date": date,
                "days_since_previous": (d - prev_date).days if prev_date else "",
                "subject": subject,
                "lines_added": add,
                "lines_removed": rem,
                "refs_total": len(refs),
                "refs_added": len(refs - prev[0]) if prev else "",
                "refs_removed": len(prev[0] - refs) if prev else "",
                "trade_ids_total": len(ids),
                "trade_ids_added": len(ids - prev[1]) if prev else "",
                "trade_ids_removed": len(prev[1] - ids) if prev else "",
                "trade_ids_retexted": (
                    len([i for i in ids & prev[1] if by_id[i] != prev[2][i]])
                    if prev
                    else ""
                ),
            }
        )
        prev, prev_date = (refs, ids, by_id), d

    os.makedirs(DATA, exist_ok=True)
    with open(os.path.join(DATA, "cadence.csv"), "w", newline="", encoding="utf-8") as fh:
        fh.write(PROV + "\n")
        w = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)

    gaps = sorted(r["days_since_previous"] for r in rows if r["days_since_previous"] != "")
    removed = [r for r in rows if r["refs_removed"] not in ("", 0)]
    print("wrote data/cadence.csv")
    print(f"commits: {len(rows)}  first {rows[0]['date']}  last {rows[-1]['date']}")
    print(
        f"gap days: median {gaps[len(gaps)//2]}  min {gaps[0]}  max {gaps[-1]}"
        f"  mean {sum(gaps)/len(gaps):.0f}"
    )
    print(f"commits that removed at least one ref: {len(removed)}")
    biggest = max(rows[1:], key=lambda r: r["refs_added"])
    print(f"largest add: {biggest['commit']} {biggest['date']} +{biggest['refs_added']} refs")
    biggestr = max(rows[1:], key=lambda r: r["refs_removed"])
    print(
        f"largest removal: {biggestr['commit']} {biggestr['date']} "
        f"-{biggestr['refs_removed']} refs ({biggestr['subject']})"
    )
    print(f"refs at first snapshot {rows[0]['refs_total']}, at HEAD {rows[-1]['refs_total']}")
    retext = [r for r in rows[1:] if r["trade_ids_retexted"]]
    print(f"commits that re-texted at least one surviving trade id: {len(retext)}")
    worst = max(rows[1:], key=lambda r: r["trade_ids_retexted"])
    print(
        f"largest re-text: {worst['commit']} {worst['date']} "
        f"{worst['trade_ids_retexted']} ids kept their id, changed their text"
    )
    print(f"total re-texts across all commits: {sum(r['trade_ids_retexted'] for r in rows[1:])}")


if __name__ == "__main__":
    main()
