#!/usr/bin/env python3
"""Model and coverage of Awakened PoE Trade's stats dataset.

Reads the owner's clone (read-only, pinned commit) and the sibling tracks'
captures; writes data/stat-model.md and data/coverage.csv. Every count in the
track README comes from here or from scripts/cadence.py.

Usage: python3 scripts/stat-model.py   (from search/prior-art/)
"""

import collections
import csv
import json
import os
import re
import subprocess
import sys

CLONE = "/Users/tom/Development/GitHub/gerwaric/awakened-poe-trade"
PINNED = "ce551eb7a9b704fbdcc2478eebb26be8f91786c7"
STATS = os.path.join(CLONE, "renderer/public/data/en/stats.ndjson")

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEARCH = os.path.dirname(HERE)
CAPTURE = os.path.join(SEARCH, "trade-query/data/stats-2026-09-12.json")
COLLISIONS = os.path.join(SEARCH, "trade-query/data/stat-collisions.csv")
STATMAP = os.path.join(SEARCH, "repoe/data/trade-stat-map.csv")

DATA = os.path.join(HERE, "data")
PROV = (
    "generated by scripts/stat-model.py from "
    "awakened-poe-trade@ce551eb7 renderer/public/data/en/stats.ndjson, "
    "../trade-query/data/stats-2026-09-12.json, "
    "../trade-query/data/stat-collisions.csv, "
    "../repoe/data/trade-stat-map.csv"
)


def check_clone():
    head = subprocess.run(
        ["git", "-C", CLONE, "rev-parse", "HEAD"], capture_output=True, text=True
    ).stdout.strip()
    if head != PINNED:
        sys.exit(f"refusing: clone HEAD is {head}, expected {PINNED}")


def load_apt():
    """One record per ndjson line: (line_no, resolver_strat_or_None, [stats])."""
    out = []
    with open(STATS, encoding="utf-8") as fh:
        for n, line in enumerate(fh, 1):
            if not line.strip():
                continue
            o = json.loads(line)
            if "stats" in o:
                out.append((n, o["resolve"], o["stats"]))
            else:
                out.append((n, None, [o]))
    return out


def load_capture():
    cap = json.load(open(CAPTURE, encoding="utf-8"))
    ids = {}
    for grp in cap["result"]:
        for e in grp["entries"]:
            ids[e["id"]] = (grp["id"], e["text"], "option" in e)
    return ids


def main():
    check_clone()
    apt = load_apt()
    capture = load_capture()

    # ---- the model ------------------------------------------------------
    c = collections.Counter()
    matchers_per = collections.Counter()
    better = collections.Counter()
    strats = collections.Counter()
    group_size = collections.Counter()
    optional_keys = collections.Counter()
    id_owner = {}  # trade id -> list of (line_no, strat, ref, category, ids_in_cat)

    for line_no, resolve, stats in apt:
        c["lines"] += 1
        if resolve is not None:
            c["group_lines"] += 1
            strats[resolve["strat"]] += 1
            group_size[len(stats)] += 1
        else:
            c["plain_lines"] += 1
        for s in stats:
            c["entries"] += 1
            better[s["better"]] += 1
            for k in s:
                if k not in ("ref", "better", "matchers", "trade"):
                    optional_keys[k] += 1
            if s["trade"].get("option"):
                c["option_entries"] += 1
            if s["trade"].get("inverted"):
                c["inverted_entries"] += 1
            ids = s["trade"]["ids"]
            if len(ids) > 1:
                c["entries_ids_several_categories"] += 1
            if any(len(v) > 1 for v in ids.values()):
                c["entries_several_ids_one_category"] += 1
            matchers_per[len(s["matchers"])] += 1
            for m in s["matchers"]:
                c["matchers"] += 1
                if "value" in m:
                    c["matchers_value"] += 1
                if "advanced" in m:
                    c["matchers_advanced"] += 1
                if "negate" in m:
                    c["matchers_negate"] += 1
            for cat, lst in ids.items():
                for i in lst:
                    id_owner.setdefault(i, []).append(
                        (line_no, resolve, s["ref"], cat, tuple(lst))
                    )

    c["distinct_trade_ids"] = len(id_owner)
    c["trade_ids_unknown_to_capture"] = len([i for i in id_owner if i not in capture])

    # ---- coverage, per capture id ---------------------------------------
    # collisions: (category, trade text) that the capture serves with >1 id
    collisions = list(csv.DictReader(open(COLLISIONS, encoding="utf-8")))
    coll_by_id = {}
    for r in collisions:
        for i in r["ids"].split():
            coll_by_id[r["category"] + "." + i] = r

    # the export's text join: trade id -> the game's English template
    english = {}
    with open(STATMAP, encoding="utf-8") as fh:
        fh.readline()  # provenance line
        for r in csv.DictReader(fh):
            english[r["trade_id"]] = r["english"]

    def collision_verdict(r):
        """How APT handles one colliding (category, text) group."""
        cat = r["category"]
        ids = [cat + "." + i for i in r["ids"].split()]
        carried = [i for i in ids if i in id_owner]
        if not carried:
            return "none_carried"
        if len(carried) < len(ids):
            return "partly_carried"
        lines = {o[0] for i in ids for o in id_owner[i]}
        if len(lines) == 1:
            line_no = next(iter(lines))
            resolve = next(o[1] for i in ids for o in id_owner[i])
            if resolve is not None:
                return "group_" + resolve["strat"]
            return "several_ids_one_entry"
        return "separate_entries"

    verdicts = {}
    for r in collisions:
        verdicts[(r["category"], r["text"])] = collision_verdict(r)

    rows = []
    for trade_id, (cat, text, is_option) in sorted(capture.items()):
        owners = id_owner.get(trade_id)
        coll = coll_by_id.get(trade_id)
        rows.append(
            {
                "trade_id": trade_id,
                "category": cat,
                "capture_text": text,
                "capture_option": "yes" if is_option else "",
                "apt_carries": "yes" if owners else "no",
                "apt_ref": owners[0][2] if owners else "",
                "apt_container": ("group" if owners[0][1] else "plain") if owners else "",
                "apt_group_strat": (owners[0][1]["strat"] if owners and owners[0][1] else ""),
                "apt_ids_in_category": (len(owners[0][4]) if owners else ""),
                "apt_ref_equals_capture_text": (
                    "yes" if owners and owners[0][2] == text else "no"
                )
                if owners
                else "",
                "collision": "yes" if coll else "no",
                "collision_size": len(coll["ids"].split()) if coll else "",
                "collision_verdict": verdicts[(coll["category"], coll["text"])]
                if coll
                else "",
                "repoe_english": "yes" if english.get(trade_id) else "no",
            }
        )

    os.makedirs(DATA, exist_ok=True)
    out = os.path.join(DATA, "coverage.csv")
    with open(out, "w", newline="", encoding="utf-8") as fh:
        fh.write("# " + PROV + "\n")
        w = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)

    carried = collections.Counter()
    lacked = collections.Counter()
    for r in rows:
        (carried if r["apt_carries"] == "yes" else lacked)[r["category"]] += 1
    verdict_counts = collections.Counter(verdicts.values())

    # ---- the shape file --------------------------------------------------
    raw = open(STATS, encoding="utf-8").read().split("\n")

    def entry(n):
        return json.dumps(json.loads(raw[n - 1]), indent=1, ensure_ascii=False)

    def find_line(pred):
        for line_no, resolve, stats in apt:
            if pred(line_no, resolve, stats):
                return line_no
        return None

    plain = find_line(
        lambda n, r, s: r is None
        and s[0]["ref"] == "#% increased Attack Speed"
        and len(s[0]["trade"]["ids"]) > 1
    ) or find_line(lambda n, r, s: r is None and len(s[0]["matchers"]) == 2)
    twin = find_line(
        lambda n, r, s: r is not None
        and r["strat"] == "select"
        and s[0]["ref"] == "#% increased Armour"
    )
    several = find_line(
        lambda n, r, s: r is not None
        and r["strat"] == "trivial-merge"
        and s[0]["ref"] == "#% chance to Avoid being Chilled during Effect"
    )

    md = []
    md.append(PROV)
    md.append("")
    md.append("# The shape of one stats entry")
    md.append("")
    md.append(
        "`renderer/public/data/en/stats.ndjson` is one JSON object per line. A line is\n"
        "either a `Stat` or a `StatGroup` of several `Stat`s that share a displayed\n"
        "line; the TypeScript is `renderer/src/assets/data/interfaces.ts:3-54`.\n"
        "`ref` is English in every language file (`renderer/public/data/{en,ru,ko,cmn-Hant}`);\n"
        "only `matchers[].string` is translated."
    )
    md.append("")
    for title, n, note in (
        (
            "A plain stat",
            plain,
            "one line, one id per modifier category; the second matcher is the "
            "negated wording of the same stat.",
        ),
        (
            "A local/global twin",
            twin,
            "two stats with the *same* `ref` and the *same* matchers, told apart "
            "only by the item's category (`resolve.test`).",
        ),
        (
            "A several-ids stat",
            several,
            "two trade ids behind one displayed line; the group's resolver merges "
            "them into one entry's id list at match time "
            "(`stat-translations.ts:280-291`, `:318-330`).",
        ),
    ):
        md.append(f"## {title} — line {n}")
        md.append("")
        md.append(note)
        md.append("")
        md.append("```json")
        md.append(entry(n))
        md.append("```")
        md.append("")

    md.append("# Counts")
    md.append("")
    md.append("| Measure | Value |")
    md.append("| --- | --- |")
    md.append(f"| ndjson lines | {c['lines']} |")
    md.append(f"| of which `StatGroup` lines | {c['group_lines']} |")
    md.append(f"| stat entries (groups flattened) | {c['entries']} |")
    md.append(f"| matchers | {c['matchers']} |")
    md.append(
        "| matchers per entry | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(matchers_per.items()))
        + " |"
    )
    md.append(f"| matchers carrying `value` | {c['matchers_value']} |")
    md.append(f"| matchers carrying `advanced` | {c['matchers_advanced']} |")
    md.append(f"| matchers carrying `negate` | {c['matchers_negate']} |")
    md.append(
        f"| entries with several ids in one category | {c['entries_several_ids_one_category']} |"
    )
    md.append(
        f"| entries with ids in several categories | {c['entries_ids_several_categories']} |"
    )
    md.append(
        "| `better` | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(better.items()))
        + " |"
    )
    md.append(f"| entries with `trade.option` | {c['option_entries']} |")
    md.append(f"| entries with `trade.inverted` | {c['inverted_entries']} |")
    md.append(
        "| group resolvers | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(strats.items()))
        + " |"
    )
    md.append(
        "| stats per group | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(group_size.items()))
        + " |"
    )
    md.append(
        "| other optional keys | "
        + ", ".join(f"`{k}`: {v}" for k, v in optional_keys.most_common())
        + " |"
    )
    md.append(f"| distinct trade ids | {c['distinct_trade_ids']} |")
    md.append(
        f"| trade ids unknown to the 2026-09-12 capture | {c['trade_ids_unknown_to_capture']} |"
    )
    md.append("")
    md.append("# Coverage of the trade capture")
    md.append("")
    md.append("| Category | carried | lacked |")
    md.append("| --- | --- | --- |")
    for cat in sorted(set(carried) | set(lacked)):
        md.append(f"| {cat} | {carried[cat]} | {lacked[cat]} |")
    md.append(f"| **total** | **{sum(carried.values())}** | **{sum(lacked.values())}** |")
    md.append("")
    md.append("# The 380 collisions")
    md.append("")
    md.append("| Verdict | Groups |")
    md.append("| --- | --- |")
    for k, v in verdict_counts.most_common():
        md.append(f"| {k} | {v} |")
    md.append("")

    open(os.path.join(DATA, "stat-model.md"), "w", encoding="utf-8").write(
        "\n".join(md) + "\n"
    )

    print("wrote data/stat-model.md and data/coverage.csv")
    print("counts:", dict(c))
    print("carried:", dict(carried))
    print("lacked:", dict(lacked))
    print("collision verdicts:", dict(verdict_counts))
    opt_carried = sum(
        1 for r in rows if r["capture_option"] and r["apt_carries"] == "yes"
    )
    opt_total = sum(1 for r in rows if r["capture_option"])
    print(f"capture option-bearing ids: {opt_carried}/{opt_total} carried")
    reftext = sum(1 for r in rows if r["apt_ref_equals_capture_text"] == "yes")
    print(f"capture ids whose text equals the APT ref verbatim: {reftext}")
    noeng = sum(1 for r in rows if r["apt_carries"] == "yes" and r["repoe_english"] == "no")
    print(f"carried ids with no RePoE English template in the map: {noeng}")


if __name__ == "__main__":
    main()
