[package]
name = "acquisition-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "acq"
path = "src/main.rs"

[dependencies]
acquisition-core = { path = "../acquisition-core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
acquisition-store = { path = "../acquisition-store" }
clap.workspace = true
ratatui = "0.29"
