#!/usr/bin/env python3
"""What the stat-id identity can address, and what it cannot.

Inputs (read-only):
  raw/corpus.jsonl                             built by scripts/build-corpus.py
  ../repoe/data/template-vs-translation.csv    display template -> trade stat id, and the line's kind

Output (data/, regenerable):
  identity-coverage.csv   one row per mod array: lines, lines carrying a stat id, and the
                          equipment / gem / other split of the lines that carry none;
                          then one row per unaddressable template, the ten largest.
"""

import csv
import collections
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
NUM = re.compile(r"(?<![\d#])[-+]?\d+(?:\.\d+)?")
TVT = os.path.join(TRACK, "..", "repoe", "data", "template-vs-translation.csv")
OUT = os.path.join(TRACK, "data", "identity-coverage.csv")
HEADER = ("# generated by scripts/identity-coverage.py from raw/corpus.jsonl "
          "and ../repoe/data/template-vs-translation.csv")


def load_tvt():
    with open(TVT) as f:
        next(f)
        rows = list(csv.DictReader(f))
    stat, kind = {}, {}
    for r in rows:
        key = (r["array"], r["template"])
        ids = r["trade_ids"].split()
        if ids:
            stat[key] = ids[0].split(".", 1)[-1]
        eq, gem, oth = int(r["equipment_lines"]), int(r["gem_lines"]), int(r["other_lines"])
        kind[key] = "equipment" if eq >= max(gem, oth) else ("gem" if gem >= oth else "other")
    return stat, kind


def main():
    stat, kind = load_tvt()
    per = collections.defaultdict(lambda: collections.Counter())
    unmapped = collections.Counter()
    skipped = 0
    with open(os.path.join(TRACK, "raw", "corpus.jsonl")) as f:
        for ln in f:
            try:
                it = json.loads(ln)["i"]
            except (ValueError, KeyError, TypeError):
                skipped += 1
                continue
            for k, v in it.items():
                if not k.endswith("Mods") or not isinstance(v, list):
                    continue
                for e in v:
                    s = e.get("description") if isinstance(e, dict) else e
                    if not isinstance(s, str):
                        continue
                    t = NUM.sub("#", s).replace("\n", "\\n")
                    c = per[k]
                    c["lines"] += 1
                    if (k, t) in stat:
                        c["with_stat"] += 1
                    else:
                        c["without_stat"] += 1
                        c["no_stat_" + kind.get((k, t), "other")] += 1
                        unmapped[(k, t)] += 1
    with open(OUT, "w", newline="") as f:
        f.write(HEADER + "\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["row", "array", "template", "lines", "with_stat_id", "without_stat_id",
                    "without_equipment", "without_gem", "without_other"])
        for k in sorted(per, key=lambda k: -per[k]["lines"]):
            c = per[k]
            w.writerow(["array", k, "", c["lines"], c["with_stat"], c["without_stat"],
                        c["no_stat_equipment"], c["no_stat_gem"], c["no_stat_other"]])
        for (a, t), n in unmapped.most_common(10):
            w.writerow(["unaddressable", a, t, n, 0, n, "", "", ""])
    print(f"skipped {skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()
