#!/usr/bin/env python3
"""Read-only inspection of the seat projection, the way an agent would first meet it.

Input (read-only, `?mode=ro`; the owner's account data, never committed):
  raw/seat-projection.db   built by `cargo run --release --offline -- --seat` in bench/

Output (committed; the database itself is not):
  data/seat-projection.md  the DDL as sqlite_master keeps it, the row counts, the `kind`
                           histogram, and how many lines carry two numbers or more.
"""

import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACK = os.path.dirname(HERE)
DB = os.path.join(TRACK, "raw", "seat-projection.db")
OUT = os.path.join(TRACK, "data", "seat-projection.md")


def main():
    if not os.path.exists(DB):
        sys.exit(f"missing {DB}: run `cargo run --release --offline -- --seat` in bench/ first")
    db = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    ddl = [r[0] for r in db.execute(
        "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type DESC, name")]
    items, lines = (db.execute(f"SELECT count(*) FROM {t}").fetchone()[0] for t in ("items", "lines"))
    with_rarity = db.execute("SELECT count(rarity) FROM items").fetchone()[0]
    socketed = db.execute("SELECT count(socketed_in) FROM items").fetchone()[0]
    kinds = db.execute("SELECT kind, count(*) FROM lines GROUP BY kind ORDER BY 2 DESC").fetchall()
    multi = db.execute("SELECT count(*) FROM lines WHERE n >= 2").fetchone()[0]
    numbered = db.execute("SELECT count(*) FROM lines WHERE n >= 1").fetchone()[0]
    flagged = db.execute("SELECT count(*) FROM lines WHERE flags != ''").fetchone()[0]
    db.close()

    w = []
    w.append(f"<!-- generated by scripts/seat-projection-check.py from raw/seat-projection.db "
             f"({os.path.getsize(DB)} bytes), read-only -->\n")
    w.append("# The seat projection, as an agent first meets it\n")
    w.append("## Schema (verbatim from `sqlite_master`, comments and all)\n")
    w.append("```sql\n" + ";\n".join(ddl) + ";\n```\n")
    w.append("## Rows\n")
    w.append("| What | Count |\n| --- | ---: |\n")
    w.append(f"| `items` | {items:,} |\n")
    w.append(f"| — with a `rarity` GGG sent | {with_rarity:,} |\n")
    w.append(f"| — socketed gems (`socketed_in` not null) | {socketed:,} |\n")
    w.append(f"| `lines` | {lines:,} |\n")
    w.append(f"| — carrying at least one number | {numbered:,} |\n")
    w.append(f"| — carrying two or more (`n >= 2`: `n0`/`n1` both present) | {multi:,} |\n")
    w.append(f"| — carrying a GGG flag | {flagged:,} |\n")
    w.append("\n## `kind` histogram\n")
    w.append("| kind | lines |\n| --- | ---: |\n")
    for k, n in kinds:
        w.append(f"| `{k}` | {n:,} |\n")
    with open(OUT, "w") as f:
        f.write("".join(w))
    print(f"{OUT}: {items} items, {lines} lines, {len(kinds)} kinds", file=sys.stderr)


if __name__ == "__main__":
    main()
